/*
 * SEP Adams Bridge ML-DSA-87 NIST conformance KAT (keyGen + sigGen + sigVer).
 *
 * Drives the official NIST ACVP-Server ML-DSA-87 vectors and byte-compares
 * ABR's output against the ACVP expected result (true FIPS-204 known-answer
 * test), unlike the integration/self-consistency tests.
 *
 *   1. keyGen : ACVP seed (xi)                 -> byte-exact expected pk
 *   2. sigGen : ACVP sk + mu (deterministic)   -> byte-exact expected signature
 *   3. sigVer : ACVP pk + mu + sig             -> accept(valid) and reject(invalid)
 *
 * sigGen/sigVer use the external-mu interface (ACVP tgId 11): mu is the 64-byte
 * precomputed message representative, so the long-message / non-empty-context
 * groups are avoided and mu maps straight to MLDSA_EXTERNAL_MU with CTRL.EXTERNAL_MU.
 *
 * Vectors: abr_nist_vectors.h (generated by gen_abr_nist_vectors.py from NIST
 * ACVP-Server internalProjection.json). ABR I/O is little-endian 32-bit words.
 * The masking ENTROPY input is not part of the ACVP vector (side-channel path
 * only; must not change the functional output), so a fixed pattern is supplied.
 */

#include <stdint.h>
#include <stdio.h>

#include "och_sep_common.h"
#include "sep_outbound_filter.h"
#include "test_completion.h"
#include "abr_mldsa.h"
#include "abr_nist_vectors.h"

/* Reused readback buffer, sized to the largest output (signature, 1157 words). */
static uint32_t g_buf[NIST_SG_SIG_WORDS];

static int first_mismatch(const uint32_t *got, const uint32_t *exp, int n)
{
    for (int i = 0; i < n; i++) {
        if (got[i] != exp[i]) {
            return i;
        }
    }
    return -1;
}

/* Compare a byte string spread over words, masking the final partial word. */
static int bytes_mismatch(const uint32_t *got, const uint32_t *exp, int nbytes)
{
    int full = nbytes / 4;
    int rem = nbytes % 4;
    int m = first_mismatch(got, exp, full);
    if (m >= 0) {
        return m;
    }
    if (rem) {
        uint32_t mask = (1u << (rem * 8)) - 1u;
        if ((got[full] & mask) != (exp[full] & mask)) {
            return full;
        }
    }
    return -1;
}

static int kat_keygen(void)
{
    abr_write_array(ABR_MLDSA_SEED, nist_kg_seed, NIST_KG_SEED_WORDS);
    abr_write_array(ABR_MLDSA_ENTROPY, k_entropy, MLDSA_ENTROPY_WORDS);

    if (abr_run_command("keygen", ABR_CMD_KEYGEN) != 0) {
        return -1;
    }
    abr_read_array(ABR_MLDSA_PUBKEY, g_buf, NIST_KG_PK_WORDS);

    int m = first_mismatch(g_buf, nist_kg_pk, NIST_KG_PK_WORDS);
    if (m >= 0) {
        printf("  keyGen MISMATCH at word %d: got 0x%08x exp 0x%08x\n",
               m, g_buf[m], nist_kg_pk[m]);
        return -1;
    }
    printf("  keyGen: PK matches NIST pk (%d bytes)\n", NIST_KG_PK_BYTES);
    return 0;
}

static int kat_siggen(void)
{
    abr_write_array(ABR_MLDSA_PRIVKEY_IN, nist_sg_sk, NIST_SG_SK_WORDS);
    abr_write_array(ABR_MLDSA_EXTERNAL_MU, nist_sg_mu, NIST_SG_MU_WORDS);
    abr_write_array(ABR_MLDSA_SIGN_RND, k_sign_rnd, MLDSA_SIGN_RND_WORDS); /* zeros: deterministic */
    abr_write_array(ABR_MLDSA_ENTROPY, k_entropy, MLDSA_ENTROPY_WORDS);

    if (abr_run_command("siggen", ABR_CMD_SIGN | ABR_CTRL_EXTERNAL_MU) != 0) {
        return -1;
    }
    abr_read_array(ABR_MLDSA_SIGNATURE, g_buf, NIST_SG_SIG_WORDS);

    int m = bytes_mismatch(g_buf, nist_sg_sig, NIST_SG_SIG_BYTES);
    if (m >= 0) {
        printf("  sigGen MISMATCH at word %d: got 0x%08x exp 0x%08x\n",
               m, g_buf[m], nist_sg_sig[m]);
        return -1;
    }
    printf("  sigGen: signature matches NIST sig (%d bytes)\n", NIST_SG_SIG_BYTES);
    return 0;
}

/* Returns 1 if ABR accepts the signature as valid, 0 if it rejects it. */
static int abr_verify(const uint32_t *pk, const uint32_t *mu, const uint32_t *sig)
{
    if (abr_wait_ready() != 0) {
        return -1;
    }
    abr_write_array(ABR_MLDSA_PUBKEY, pk, NIST_SV_PK_WORDS);
    abr_write_array(ABR_MLDSA_EXTERNAL_MU, mu, NIST_SV_MU_WORDS);
    abr_write_array(ABR_MLDSA_SIGNATURE, sig, NIST_SV_SIG_WORDS);

    WRITE_REG(ABR_MLDSA_CTRL, ABR_CMD_VERIFY | ABR_CTRL_EXTERNAL_MU);
    if (poll_reg_timeout(ABR_MLDSA_STATUS, ABR_ST_VALID, ABR_ST_VALID,
                         ABR_POLL_TIMEOUT) != 0) {
        return 0; /* never produced a valid result -> treat as rejected */
    }
    if (READ_REG(ABR_MLDSA_STATUS) & ABR_ST_ERROR) {
        return 0;
    }
    uint32_t ver[MLDSA_CHASH_WORDS];
    abr_read_array(ABR_MLDSA_VERIFY_RES, ver, MLDSA_CHASH_WORDS);
    /* ML-DSA verify succeeds iff the recomputed c~ equals the signature's c~. */
    return abr_words_equal(ver, sig, MLDSA_CHASH_WORDS) ? 1 : 0;
}

static int kat_sigver(void)
{
    int ok = abr_verify(nist_sv_ok_pk, nist_sv_ok_mu, nist_sv_ok_sig);
    if (ok != NIST_SV_OK_VERDICT) {
        printf("  sigVer(valid) got %d, expected %d\n", ok, NIST_SV_OK_VERDICT);
        return -1;
    }
    if (abr_zeroize() != 0) {
        return -1;
    }
    int bad = abr_verify(nist_sv_bad_pk, nist_sv_bad_mu, nist_sv_bad_sig);
    if (bad != NIST_SV_BAD_VERDICT) {
        printf("  sigVer(invalid) got %d, expected %d\n", bad, NIST_SV_BAD_VERDICT);
        return -1;
    }
    printf("  sigVer: valid accepted, invalid rejected (matches NIST)\n");
    return 0;
}

int main(void)
{
    int pass = 1;

    sep_outbound_filter_init();

    printf("\n=== Adams Bridge ML-DSA-87 NIST conformance KAT (ACVP) ===\n");

    if (kat_keygen() != 0) {
        pass = 0;
    } else if (abr_zeroize() != 0) {
        pass = 0;
    } else if (kat_siggen() != 0) {
        pass = 0;
    } else if (abr_zeroize() != 0) {
        pass = 0;
    } else if (kat_sigver() != 0) {
        pass = 0;
    }

    if (pass) {
        printf("\n=== ABR NIST KAT PASSED (keyGen + sigGen + sigVer) ===\n");
        test_pass(0);
    } else {
        printf("\n=== ABR NIST KAT FAILED ===\n");
        test_fail(0);
    }

    while (1) {
        __asm__("wfi");
    }

    return pass ? 0 : -1;
}
