// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
// ROM metadata: version string and SHA-256 hash for self-reporting (C1).
//
// The build-time hash is inserted by tools/insert-rom-sha256.py after linking.
// It covers the ICCM content (code + metadata) and is stored here in .rodata
// (DCCM) because VeeR EL2's LSU cannot data-load from ICCM addresses.
// Since the hash covers ICCM and lives in DCCM, there is no circular dependency.

#include <stdint.h>
#include "bl0_version.h"

// ROM version string with semver + git hash (generated by scripts/bl0-version.py).
// Format: "SEP_BL0_vX.Y.Z+dev.N.gabcdef1234567890".
__attribute__((used, aligned(4))) const char g_rom_version[] = BL0_VERSION "\n";

// ROM SHA-256 hash string, patched at build time by insert-rom-sha256.py.
// Format: "sha256:<64-hex-chars>\0..." (80 bytes).
// Placeholder is all-zeros; the build script overwrites it.
__attribute__((used, aligned(4))) const char g_rom_sha256_str[80] = {0};

