#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Generate abr_nist_vectors.h from NIST ACVP-Server ML-DSA-87 vectors.

The golden inputs/outputs are the official NIST ACVP "internalProjection" files
(they contain both inputs and expected outputs). Download them first (the dev
machine has network access):

  base=https://raw.githubusercontent.com/usnistgov/ACVP-Server/master/gen-val/json-files
  curl -sSL -o /tmp/mldsa_keygen.json $base/ML-DSA-keyGen-FIPS204/internalProjection.json
  curl -sSL -o /tmp/mldsa_siggen.json $base/ML-DSA-sigGen-FIPS204/internalProjection.json
  curl -sSL -o /tmp/mldsa_sigver.json $base/ML-DSA-sigVer-FIPS204/internalProjection.json

ABR register I/O is little-endian 32-bit words with no byte-swap on the ML-DSA
register->core path (verified in abr_ctrl.sv), so an ACVP hex byte string maps
directly to a native uint32_t LE array, matching the SEP abr_write_array/
abr_read_array helpers. Outputs are FIPS-204 layout (PUBKEY=rho||t1,
SIGNATURE=c~||z||h). Default signing computes mu internally from the raw message
with an empty context, so the ACVP "message" maps straight to MLDSA_MSG.
"""
import json
import os
import sys

PARAM = "ML-DSA-87"
KG = "/tmp/mldsa_keygen.json"
SG = "/tmp/mldsa_siggen.json"
SV = "/tmp/mldsa_sigver.json"
OUT = os.path.join(os.path.dirname(__file__), "abr_nist_vectors.h")


def hex_to_words(h):
    """ACVP hex byte string -> (list[uint32] LE, byte_len)."""
    raw = bytes.fromhex(h)
    n = len(raw)
    pad = raw + b"\x00" * ((-n) % 4)
    words = [int.from_bytes(pad[i:i + 4], "little") for i in range(0, len(pad), 4)]
    return words, n


def find_group(path, tgid=None):
    d = json.load(open(path))
    for g in d["testGroups"]:
        if g.get("parameterSet") == PARAM and (tgid is None or g.get("tgId") == tgid):
            return g
    sys.exit(f"no {PARAM} group (tgId={tgid}) in {path}")


def emit(f, name, words, nbytes, comment):
    f.write(f"/* {comment} ({nbytes} bytes, {len(words)} words) */\n")
    f.write(f"static const uint32_t {name}[{len(words)}] = {{\n")
    for i in range(0, len(words), 8):
        f.write("    " + " ".join(f"0x{w:08x}u," for w in words[i:i + 8]) + "\n")
    f.write("};\n\n")


def main():
    f = open(OUT, "w")
    f.write("/* AUTO-GENERATED by gen_abr_nist_vectors.py from NIST ACVP-Server\n")
    f.write(" * ML-DSA-87 FIPS-204 vectors. DO NOT EDIT (regenerate via the script).\n")
    f.write(" * ABR I/O: little-endian 32-bit words; byte b -> word[b/4] bits (b%4)*8. */\n")
    f.write("#ifndef SEP_ABR_NIST_VECTORS_H\n#define SEP_ABR_NIST_VECTORS_H\n\n")
    f.write("#include <stdint.h>\n\n")

    # --- keyGen: seed (xi) -> expected pk ---
    g = find_group(KG)
    t = next(x for x in g["tests"] if "seed" in x and "pk" in x)
    sw, sn = hex_to_words(t["seed"])
    pw, pn = hex_to_words(t["pk"])
    f.write(f"/* keyGen  ACVP tcId {t['tcId']} */\n")
    emit(f, "nist_kg_seed", sw, sn, "keyGen seed xi")
    emit(f, "nist_kg_pk", pw, pn, "keyGen expected public key")
    f.write(f"#define NIST_KG_SEED_WORDS {len(sw)}\n")
    f.write(f"#define NIST_KG_PK_WORDS   {len(pw)}\n")
    f.write(f"#define NIST_KG_PK_BYTES   {pn}\n\n")

    # --- sigGen: deterministic external-mu (tgId 11): sk + mu -> expected sig ---
    g = find_group(SG, tgid=11)  # det=True, externalMu=True, internal iface
    t = g["tests"][0]
    skw, skn = hex_to_words(t["sk"])
    muw, mun = hex_to_words(t["mu"])
    sgw, sgn = hex_to_words(t["signature"])
    f.write(f"/* sigGen  ACVP tcId {t['tcId']} (deterministic, external-mu) */\n")
    emit(f, "nist_sg_sk", skw, skn, "sigGen private key (sk in)")
    emit(f, "nist_sg_mu", muw, mun, "sigGen precomputed mu")
    emit(f, "nist_sg_sig", sgw, sgn, "sigGen expected signature")
    f.write(f"#define NIST_SG_SK_WORDS  {len(skw)}\n")
    f.write(f"#define NIST_SG_MU_WORDS  {len(muw)}\n")
    f.write(f"#define NIST_SG_SIG_WORDS {len(sgw)}\n")
    f.write(f"#define NIST_SG_SIG_BYTES {sgn}\n\n")

    # --- sigVer: external-mu (tgId 11): pk + mu + sig -> expected verdict ---
    g = find_group(SV, tgid=11)
    good = next(x for x in g["tests"] if x.get("testPassed") is True)
    bad = next(x for x in g["tests"] if x.get("testPassed") is False)
    for tag, t in (("ok", good), ("bad", bad)):
        pkw, pkn = hex_to_words(t["pk"])
        muw, mun = hex_to_words(t["mu"])
        sgw, sgn = hex_to_words(t["signature"])
        verdict = 1 if t["testPassed"] else 0
        f.write(f"/* sigVer  ACVP tcId {t['tcId']} testPassed={t['testPassed']} */\n")
        emit(f, f"nist_sv_{tag}_pk", pkw, pkn, f"sigVer {tag} public key")
        emit(f, f"nist_sv_{tag}_mu", muw, mun, f"sigVer {tag} mu")
        emit(f, f"nist_sv_{tag}_sig", sgw, sgn, f"sigVer {tag} signature")
        f.write(f"#define NIST_SV_{tag.upper()}_VERDICT {verdict}\n\n")
    f.write("#define NIST_SV_PK_WORDS  648\n")
    f.write("#define NIST_SV_MU_WORDS  16\n")
    f.write("#define NIST_SV_SIG_WORDS 1157\n\n")

    f.write("#endif /* SEP_ABR_NIST_VECTORS_H */\n")
    f.close()
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
