#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Generate compact KM ROM KDF test vectors from the shared JSONL KAT file."""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterable


INPUT_BYTES = 192
TARGET_KEY_LENGTHS = (0, 1, 32, 64, 65, 128)
TARGET_OUTPUT_BITS = (8, 256, 264, 512)
LARGE_VECTOR = (32, 8192)


def decode_hex(record: dict[str, Any], field: str) -> bytes:
    """Decode one required hexadecimal record field."""
    value = record.get(field)
    if not isinstance(value, str):
        raise ValueError(f"sequence {record.get('seq')}: {field} is not a string")
    try:
        return bytes.fromhex(value)
    except ValueError as exc:
        raise ValueError(
            f"sequence {record.get('seq')}: {field} is not valid hexadecimal"
        ) from exc


def load_pure_vectors(path: Path) -> list[dict[str, Any]]:
    """Load and validate the pure KDF vectors from a JSON Lines file."""
    vectors: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as source:
        for line_number, line in enumerate(source, start=1):
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_number}: invalid JSON: {exc}") from exc
            if record.get("kind") != "pure":
                continue

            key = decode_hex(record, "key")
            kdf_input = decode_hex(record, "input")
            expected = decode_hex(record, "out")
            key_len = record.get("key_len")
            out_bits = record.get("L_bits")
            sequence = record.get("seq")

            if not isinstance(sequence, int):
                raise ValueError(f"{path}:{line_number}: seq is not an integer")
            if not isinstance(key_len, int) or key_len != len(key):
                raise ValueError(f"sequence {sequence}: key_len does not match key")
            if len(kdf_input) != INPUT_BYTES:
                raise ValueError(
                    f"sequence {sequence}: input is {len(kdf_input)} bytes, "
                    f"expected {INPUT_BYTES}"
                )
            if not isinstance(out_bits, int) or out_bits <= 0:
                raise ValueError(f"sequence {sequence}: L_bits is invalid")
            if len(expected) != (out_bits + 7) // 8:
                raise ValueError(
                    f"sequence {sequence}: output length does not match L_bits"
                )

            vectors.append(
                {
                    "seq": sequence,
                    "key": key,
                    "key_len": key_len,
                    "input": kdf_input,
                    "out_bits": out_bits,
                    "expected": expected,
                }
            )

    return sorted(vectors, key=lambda vector: int(vector["seq"]))


def select_vectors(vectors: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Select one deterministic vector for each required boundary case."""
    by_geometry: dict[tuple[int, int], dict[str, Any]] = {}
    for vector in vectors:
        geometry = (int(vector["key_len"]), int(vector["out_bits"]))
        by_geometry.setdefault(geometry, vector)

    geometries = [
        (key_len, out_bits)
        for key_len in TARGET_KEY_LENGTHS
        for out_bits in TARGET_OUTPUT_BITS
    ]
    geometries.append(LARGE_VECTOR)

    missing = [geometry for geometry in geometries if geometry not in by_geometry]
    if missing:
        formatted = ", ".join(f"key_len={key}, L_bits={bits}" for key, bits in missing)
        raise ValueError(f"missing required pure vectors: {formatted}")

    return [by_geometry[geometry] for geometry in geometries]


def format_bytes(data: bytes, indent: str = "        ") -> Iterable[str]:
    """Format a byte sequence as wrapped C initializer lines."""
    for offset in range(0, len(data), 8):
        chunk = data[offset : offset + 8]
        suffix = "," if offset + len(chunk) < len(data) else ""
        yield indent + ", ".join(f"0x{byte:02x}" for byte in chunk) + suffix


def emit_array(name: str, data: bytes) -> list[str]:
    """Emit one file-scope C byte array."""
    lines = [f"static const uint8_t {name}[] = {{"]
    lines.extend(format_bytes(data, indent="    "))
    lines.append("};")
    return lines


def generate_header(vectors: list[dict[str, Any]], source_name: str) -> str:
    """Render the selected vectors as a self-contained C header."""
    lines = [
        "/* Copyright 2026 Tenstorrent Inc. */",
        "/*",
        " * Generated by tools/gen_kdf_vectors.py from",
        f" * tt-ocah-kmkdf/{source_name}. Do not hand-edit.",
        " */",
        "",
        "#ifndef KDF_VECTORS_H",
        "#define KDF_VECTORS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#include \"rom_kdf.h\"",
        "",
        "struct kdf_test_vector {",
        "    const char *name;",
        "    const uint8_t *key;",
        "    uint32_t key_len;",
        "    uint8_t input[KM_KDF_INPUT_BYTES];",
        "    uint16_t out_bits;",
        "    const uint8_t *expected;",
        "    uint32_t expected_len;",
        "};",
        "",
    ]

    for vector in vectors:
        sequence = int(vector["seq"])
        key = vector["key"]
        expected = vector["expected"]
        if key:
            lines.extend(emit_array(f"kdf_vec_{sequence}_key", key))
        lines.extend(emit_array(f"kdf_vec_{sequence}_expected", expected))
        lines.append("")

    lines.append("static const struct kdf_test_vector kdf_test_vectors[] = {")
    for vector in vectors:
        sequence = int(vector["seq"])
        key_len = int(vector["key_len"])
        out_bits = int(vector["out_bits"])
        key_name = f"kdf_vec_{sequence}_key" if key_len != 0 else "NULL"
        expected_name = f"kdf_vec_{sequence}_expected"
        lines.extend(
            [
                "    {",
                f"        .name = \"seq{sequence} key{key_len} L{out_bits}\",",
                f"        .key = {key_name},",
                f"        .key_len = {key_len}u,",
                "        .input = {",
            ]
        )
        lines.extend(format_bytes(vector["input"], indent="            "))
        lines.extend(
            [
                "        },",
                f"        .out_bits = {out_bits}u,",
                f"        .expected = {expected_name},",
                f"        .expected_len = {len(vector['expected'])}u,",
                "    },",
            ]
        )
    lines.extend(
        [
            "};",
            "",
            "#define KDF_NUM_VECTORS \\",
            "    (sizeof(kdf_test_vectors) / sizeof(kdf_test_vectors[0]))",
            "",
            "#endif /* KDF_VECTORS_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Parse arguments and write the generated header to standard output."""
    parser = argparse.ArgumentParser(
        description="Generate curated C vectors for the KM ROM KDF firmware test."
    )
    parser.add_argument("jsonl", type=Path, help="tt-ocah-kmkdf KAT JSON Lines file")
    args = parser.parse_args()

    if not args.jsonl.is_file():
        parser.error(f"input file does not exist: {args.jsonl}")

    try:
        vectors = select_vectors(load_pure_vectors(args.jsonl))
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    sys.stdout.write(generate_header(vectors, args.jsonl.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
