/*******************************************************************************
 * Registers
 *
 * This file was auto-generated by this script:
 *     create_reg_rtl_peakrdl.py   (r2025-05-05: peakrdl 1.2.3,peakrdl-cheader 1.0.0,peakrdl-cli 1.2.3,peakrdl-html 2.10.1,peakrdl-ipxact 3.5.0,peakrdl-regblock 1.0.0,peakrdl-systemrdl 0.3.0,peakrdl-uvm 2.3.0)
 * ... from this input file:
 *     sep_lifecycle_ctrl.rdl
 * ... using this as the top address space:
 *     sep_lifecycle_ctrl
 * ... using this interface type:
 *     APB4
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

module tt_sep_lifecycle_ctrl_reg #(
    parameter int unsigned BASE_ADDR    = 0,            // Base address
    parameter int unsigned ADDR_W       = 13            // Bit width of address
) (
    // Global Interface
    input  logic                i_clk,
    input  logic                i_reset_n,

    // APB4 Bus
    input  logic                i_apb_psel,
    input  logic                i_apb_penable,
    input  logic                i_apb_pwrite,
    input  logic          [2:0] i_apb_pprot,
    input  logic   [ADDR_W-1:0] i_apb_paddr,
    input  logic         [31:0] i_apb_pwdata,
    input  logic          [3:0] i_apb_pstrb,
    output logic                o_apb_pready,
    output logic         [31:0] o_apb_prdata,
    output logic                o_apb_pslverr,

    // Hardware Writable Register Fields
    input  logic         [31:0] i_R_feat_ctrl_lo_F_feature_control_lo,
    input  logic         [31:0] i_R_feat_ctrl_hi_F_feature_control_hi,

    // Hardware Readable Register Fields
    output logic                o_R_demote_F_demote,
    output logic                o_R_demote_F_lock,
    output logic         [29:0] o_R_demote_F_rsvd,

    // Software Write-Enable Register Fields
    input  logic                i_R_demote_F_demote_swwe
);

// Bus Signals
// Register Block Local Address After Subtracting Base Address
logic   [ADDR_W-1:0] apb_paddr_local;

// PeakRDL Internal Signals
tt_sep_lifecycle_ctrl_reg_pkg::sep_lifecycle_ctrl__in_t in;
tt_sep_lifecycle_ctrl_reg_pkg::sep_lifecycle_ctrl__out_t out;


// PeakRDL Internal Signals Expansion
// For Hardware Writable Register Fields
assign in.FEAT_CTRL_LO.feature_control_lo.next = i_R_feat_ctrl_lo_F_feature_control_lo;
assign in.FEAT_CTRL_HI.feature_control_hi.next = i_R_feat_ctrl_hi_F_feature_control_hi;

// For Hardware Readable Register Fields
assign o_R_demote_F_demote = out.DEMOTE.demote.value;
assign o_R_demote_F_lock = out.DEMOTE.lock.value;
assign o_R_demote_F_rsvd = out.DEMOTE.rsvd.value;

// For Software Write-Enable Register Fields
assign in.DEMOTE.demote.swwe = i_R_demote_F_demote_swwe;



// Bus Interface Conversion
// Global to Local Address Subtraction
assign apb_paddr_local = i_apb_paddr - BASE_ADDR[ADDR_W-1:0];



// PeakRDL Submodule Instantiation
tt_sep_lifecycle_ctrl_reg_inner tt_sep_lifecycle_ctrl_reg_inner_block(
    .clk                    (i_clk),
    .rst_n                  (i_reset_n),
    .s_apb_psel             (i_apb_psel),
    .s_apb_penable          (i_apb_penable),
    .s_apb_pwrite           (i_apb_pwrite),
    .s_apb_pprot            (i_apb_pprot),
    .s_apb_paddr            (apb_paddr_local[12:0]),
    .s_apb_pwdata           (i_apb_pwdata),
    .s_apb_pstrb            (i_apb_pstrb),
    .s_apb_pready           (o_apb_pready),
    .s_apb_prdata           (o_apb_prdata),
    .s_apb_pslverr          (o_apb_pslverr),
    .hwif_in                (in),
    .hwif_out               (out)
);



// Assertions For Testing Register Properties
`ifdef ENABLE_REG_ASSERTION
//VCS coverage off

// For ONWRITE Register Fields
property p_R_demote_F_demote_woset;
    @(posedge i_clk) disable iff ((i_reset_n === 1'b0) || $fell(!i_reset_n, @(posedge i_clk)))
        ((i_apb_paddr == 13'h1000) && i_apb_psel && i_apb_penable && i_apb_pwrite) |=>
            tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.demote.value === $past(tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.demote.value | (i_apb_pwdata[0:0] & {{8{i_apb_pstrb[3]}}, {8{i_apb_pstrb[2]}}, {8{i_apb_pstrb[1]}}, {8{i_apb_pstrb[0]}}}[0:0]));
endproperty
a_R_demote_F_demote_woset: assert property(p_R_demote_F_demote_woset) else $error("Property p_R_demote_F_demote_woset failed!");


property p_R_demote_F_lock_woset;
    @(posedge i_clk) disable iff ((i_reset_n === 1'b0) || $fell(!i_reset_n, @(posedge i_clk)))
        ((i_apb_paddr == 13'h1000) && i_apb_psel && i_apb_penable && i_apb_pwrite) |=>
            tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.lock.value === $past(tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.lock.value | (i_apb_pwdata[1:1] & {{8{i_apb_pstrb[3]}}, {8{i_apb_pstrb[2]}}, {8{i_apb_pstrb[1]}}, {8{i_apb_pstrb[0]}}}[1:1]));
endproperty
a_R_demote_F_lock_woset: assert property(p_R_demote_F_lock_woset) else $error("Property p_R_demote_F_lock_woset failed!");


property p_R_demote_F_rsvd_woset;
    @(posedge i_clk) disable iff ((i_reset_n === 1'b0) || $fell(!i_reset_n, @(posedge i_clk)))
        ((i_apb_paddr == 13'h1000) && i_apb_psel && i_apb_penable && i_apb_pwrite) |=>
            tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.rsvd.value === $past(tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.rsvd.value | (i_apb_pwdata[31:2] & {{8{i_apb_pstrb[3]}}, {8{i_apb_pstrb[2]}}, {8{i_apb_pstrb[1]}}, {8{i_apb_pstrb[0]}}}[31:2]));
endproperty
a_R_demote_F_rsvd_woset: assert property(p_R_demote_F_rsvd_woset) else $error("Property p_R_demote_F_rsvd_woset failed!");




// For Software Write-Enable Register Fields
property p_R_demote_F_demote_swwe;
    @(posedge i_clk) disable iff ((i_reset_n === 1'b0) || $fell(!i_reset_n, @(posedge i_clk)))
        !i_R_demote_F_demote_swwe && ((i_apb_paddr == 13'h1000) && i_apb_psel && i_apb_penable && i_apb_pwrite) |=> $stable(tt_sep_lifecycle_ctrl_reg_inner_block.field_storage.DEMOTE.demote.value);
endproperty
a_R_demote_F_demote_swwe: assert property(p_R_demote_F_demote_swwe) else $error("Property p_R_demote_F_demote_swwe failed!");

//VCS coverage on
`endif

endmodule
