// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
/*
 * OTBN Nested Loops Test
 *
 * This test validates OTBN's nested loop functionality by executing a complex
 * loop structure and verifying both the mathematical result and instruction count.
 *
 * Test algorithm:
 * - Initialize accumulator x2 = 0, inner loop count x3 = 3
 * - Outer loop: 4 iterations (using loopi instruction)
 * - Each outer iteration: add 10 to accumulator
 * - Inner loop: 3 iterations (using loop instruction)
 * - Each inner iteration: add 1 to accumulator
 * - Expected result: 4×(10+3×1) = 52
 * - Expected instruction count: 28 (most complex INSN_CNT test in OpenTitan)
 *
 * Test vectors derived from OpenTitan's loops.s test, adapted for OCH platform.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "test_completion.h"
#include "otbn_loops_otbn.h"      // Generated by common_otbn infrastructure
#include "otbn_loops_test.h"      // Test definitions and constants
#include "sep_outbound_filter.h"
#include "och_sep_top_reg.h"

// OTBN status register values
#define OTBN_STATUS_IDLE        0x00
#define OTBN_STATUS_BUSY_EXECUTE 0x01

// OTBN command register values
#define OTBN_CMD_EXECUTE        0xD8
#define OTBN_CMD_SEC_WIPE_DMEM  0xC3
#define OTBN_CMD_SEC_WIPE_IMEM  0x1E

// Base address for OTBN in the OCH SEP memory map
#define OTBN_BASE_ADDR        OTBN_REG_MAP_BASE_ADDR

// OTBN memory window offsets (relative to OTBN_BASE_ADDR)
#define OTBN_IMEM_OFFSET      (OTBN_IMEM_MEM_BASE_ADDR - OTBN_REG_MAP_BASE_ADDR)   // 0x00004000
#define OTBN_DMEM_OFFSET      (OTBN_DMEM_MEM_BASE_ADDR - OTBN_REG_MAP_BASE_ADDR)   // 0x00008000
#define OTBN_CMD_OFFSET       OTBN_CMD_REG_OFFSET       // 0x00000010
#define OTBN_STATUS_OFFSET    OTBN_STATUS_REG_OFFSET    // 0x00000018
#define OTBN_ERR_BITS_OFFSET  OTBN_ERR_BITS_REG_OFFSET  // 0x0000001C
#define OTBN_LOAD_CHECKSUM_OFFSET OTBN_LOAD_CHECKSUM_REG_OFFSET // 0x00000028
#define OTBN_INSN_CNT_OFFSET      OTBN_INSN_CNT_REG_OFFSET      // 0x00000024

// Memory access helpers - EL2 CPU accessing OTBN through register interface
#define OTBN_REG(offset)  (*((volatile uint32_t *)(OTBN_BASE_ADDR + (offset))))
#define OTBN_IMEM(word)   (*((volatile uint32_t *)(OTBN_BASE_ADDR + OTBN_IMEM_OFFSET + ((word) * 4))))
#define OTBN_DMEM(word)   (*((volatile uint32_t *)(OTBN_BASE_ADDR + OTBN_DMEM_OFFSET + ((word) * 4))))

/**
 * Wait for OTBN to become idle
 */
static int otbn_wait_for_idle(void) {
    int timeout = 1000000;  // Large timeout for simulation environments

    while (timeout-- > 0) {
        uint32_t status = OTBN_REG(OTBN_STATUS_OFFSET);
        if (status == OTBN_STATUS_IDLE) {
            return 0;  // Success
        }
        // Add a small delay to prevent bus contention
        for (volatile int i = 0; i < 100; i++);
    }

    printf("ERROR: OTBN timeout waiting for idle state\n");
    return -1;  // Timeout
}


/**
 * Manually initialize OTBN DMEM with zeros
 * This ensures a clean, predictable memory state
 */
static int otbn_dmem_zero_init(void) {
    printf("Manually initializing OTBN DMEM with zeros\n");

    // Wait for OTBN to be idle before starting
    if (otbn_wait_for_idle() != 0) {
        printf("ERROR: OTBN not idle before DMEM initialization\n");
        return -1;
    }

    // Zero out all visible DMEM locations
    // DMEM has 768 visible 32-bit words (3KB) over the bus interface
    const uint32_t dmem_size_words = 768;
    const uint32_t zero_value = 0x00000000;

    printf("  Writing zeros to DMEM addresses 0x000 to 0x%03x...\n", (dmem_size_words - 1) * 4);

    for (uint32_t addr = 0; addr < dmem_size_words; addr++) {
        OTBN_DMEM(addr) = zero_value;
    }

    printf("  DMEM zero initialization complete\n");
    return 0;
}

/**
 * Load OTBN program from embedded data
 */
static int otbn_load_program(void) {
    printf("Loading OTBN program...\n");

    // Wait for OTBN to be idle
    if (otbn_wait_for_idle() != 0) {
        return -1;
    }

    // Get program size from generated headers
    uint32_t imem_words = otbn_otbn_loops_imem_words;
    uint32_t dmem_words = otbn_otbn_loops_dmem_words;

    printf("  IMEM size: %u words (%u bytes)\n", imem_words, imem_words * 4);
    printf("  DMEM size: %u words (%u bytes)\n", dmem_words, dmem_words * 4);

    if (imem_words == 0) {
        printf("ERROR: IMEM size is zero - check program compilation\n");
        return -1;
    }

    // Load IMEM
    printf("  Loading IMEM...\n");
    for (uint32_t i = 0; i < imem_words; i++) {
        OTBN_IMEM(i) = otbn_otbn_loops_imem[i];
    }

    // Load DMEM (constants and initialized data)
    if (dmem_words > 0) {
        printf("  Loading DMEM...\n");
        for (uint32_t i = 0; i < dmem_words; i++) {
            OTBN_DMEM(i) = otbn_otbn_loops_dmem[i];
        }
    }

    // Reset load checksum register to 0 after program loading
    OTBN_REG(OTBN_LOAD_CHECKSUM_OFFSET) = 0;

    printf("  Program loading complete\n");
    return 0;
}

/**
 * Execute OTBN program
 */
static int otbn_execute(void) {
    printf("Executing OTBN program...\n");

    // Clear any previous errors
    OTBN_REG(OTBN_ERR_BITS_OFFSET) = 0xFFFFFFFF;

    // Issue execute command
    OTBN_REG(OTBN_CMD_OFFSET) = OTBN_CMD_EXECUTE;

    // Wait for completion
    if (otbn_wait_for_idle() != 0) {
        return -1;
    }

    // Check for errors
    uint32_t err_bits = OTBN_REG(OTBN_ERR_BITS_OFFSET);
    if (err_bits != 0) {
        printf("ERROR: OTBN execution failed with error bits: 0x%08x\n", err_bits);
        return -1;
    }

    printf("  OTBN execution completed successfully\n");
    return 0;
}

/**
 * Read instruction count from OTBN INSN_CNT CSR
 * Focus purely on INSN_CNT validation as the only goal.
 */
static int otbn_read_results(uint32_t *insn_count) {
    printf("Reading INSN_CNT from OTBN...\n");

    // Wait for OTBN to be idle
    if (otbn_wait_for_idle() != 0) {
        return -1;
    }

    // Read the instruction count from CPU-side INSN_CNT register
    *insn_count = OTBN_REG(OTBN_INSN_CNT_OFFSET);
    printf("  Instruction count: %u (0x%08x)\n", *insn_count, *insn_count);

    return 0;
}

/**
 * Print detailed test results
 */
void otbn_loops_test_print_results(uint32_t insn_count) {
    printf("\n========================================\n");
    printf("OTBN INSN_CNT Validation Test Results\n");
    printf("========================================\n");

    printf("Instruction Count Verification:\n");
    printf("  Actual instruction count: %u\n", insn_count);
    printf("  Expected instruction count: %u\n", EXPECTED_INSN_COUNT);
    printf("  Count verification: %s\n", (insn_count == EXPECTED_INSN_COUNT) ? "PASS" : "FAIL");
    printf("  Note: Exact OpenTitan loops.exp instruction count\n");
    printf("  Read from CPU-side INSN_CNT register (0x%04x)\n", OTBN_INSN_CNT_OFFSET);

    printf("\nOverall Test Status: ");
    if (insn_count == EXPECTED_INSN_COUNT) {
        printf("PASS - INSN_CNT verification successful!\n");
    } else {
        printf("FAIL - INSN_CNT verification failed\n");
    }
    printf("========================================\n\n");
}

/**
 * Run the complete OTBN loops test
 */
otbn_loops_test_result_t otbn_loops_test_run(void) {
    printf("Starting OTBN INSN_CNT Validation Test\n");
    printf("======================================\n");

    // Step 1: Initialize DMEM with zeros
    if (otbn_dmem_zero_init() != 0) {
        return OTBN_LOOPS_TEST_FAIL_OTBN_ERROR;
    }

    // Step 2: Load OTBN program
    if (otbn_load_program() != 0) {
        return OTBN_LOOPS_TEST_FAIL_OTBN_ERROR;
    }

    // Step 3: Execute the program
    if (otbn_execute() != 0) {
        return OTBN_LOOPS_TEST_FAIL_OTBN_ERROR;
    }

    // Step 4: Read INSN_CNT
    uint32_t insn_count;
    if (otbn_read_results(&insn_count) != 0) {
        return OTBN_LOOPS_TEST_FAIL_OTBN_ERROR;
    }

    // Step 5: Print detailed results
    otbn_loops_test_print_results(insn_count);

    // Step 6: Determine test outcome - pure INSN_CNT validation
    if (insn_count != EXPECTED_INSN_COUNT) {
        return OTBN_LOOPS_TEST_FAIL_INSN_COUNT;
    }

    return OTBN_LOOPS_TEST_SUCCESS;
}

/**
 * Main test function
 */
int main(void) {
    // Initialize outbound filter to allow testpass mailbox access
    sep_outbound_filter_init();

    printf("\n");
    printf("******************************************\n");
    printf("*      OTBN INSN_CNT Validation Test    *\n");
    printf("*                                        *\n");
    printf("*   Validates INSN_CNT CSR accuracy     *\n");
    printf("*   Based on OpenTitan loops.s test     *\n");
    printf("******************************************\n\n");

    otbn_loops_test_result_t result = otbn_loops_test_run();

    printf("Final Test Result: ");
    switch (result) {
        case OTBN_LOOPS_TEST_SUCCESS:
            printf("SUCCESS - All tests passed!\n");
            break;

        case OTBN_LOOPS_TEST_FAIL_INSN_COUNT:
            printf("FAIL - Instruction count incorrect\n");
            break;
        case OTBN_LOOPS_TEST_FAIL_OTBN_ERROR:
            printf("FAIL - OTBN execution error\n");
            break;
        case OTBN_LOOPS_TEST_FAIL_TIMEOUT:
            printf("FAIL - Timeout waiting for OTBN\n");
            break;
        default:
            printf("FAIL - Unknown error\n");
            break;
    }

    if (result == OTBN_LOOPS_TEST_SUCCESS) {
        test_pass(0);
    } else {
        test_fail((int)result);
    }

    // Keep CPU alive after signaling completion.
    while (1) {
        __asm__("wfi");
    }
}