/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was auto-generated by this script:
 *       create_reg_sv_header.py   (r2025-06-03)
 * ... from this input file:
 *       km_mailbox_km.rdl
 * ... using this as the target address space:
 *       km_mailbox_km
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef KM_MAILBOX_KM_REG_SVH
`define KM_MAILBOX_KM_REG_SVH



//==============================================================================
// Addresses for Address Map: km_mailbox_km
//==============================================================================


localparam int unsigned KM_MAILBOX_KM_REG_MAP_BASE_ADDR                                                           = 32'h00000000;
localparam int unsigned KM_MAILBOX_KM_REG_MAP_SIZE                                                                = 32'h0000001C;


localparam int unsigned KM_WRITE_DATA_REG_OFFSET                                                                  = 32'h00000000;
localparam int unsigned KM_WRITE_DATA_REG_ADDR                                                                    = 32'h00000000;
localparam int unsigned KM_WRITE_SEPARATOR_REG_OFFSET                                                             = 32'h00000004;
localparam int unsigned KM_WRITE_SEPARATOR_REG_ADDR                                                               = 32'h00000004;
localparam int unsigned KM_READ_DATA_REG_OFFSET                                                                   = 32'h00000008;
localparam int unsigned KM_READ_DATA_REG_ADDR                                                                     = 32'h00000008;
localparam int unsigned KM_STATUS_REG_OFFSET                                                                      = 32'h0000000C;
localparam int unsigned KM_STATUS_REG_ADDR                                                                        = 32'h0000000C;
localparam int unsigned KM_IRQ_STATUS_REG_OFFSET                                                                  = 32'h00000010;
localparam int unsigned KM_IRQ_STATUS_REG_ADDR                                                                    = 32'h00000010;
localparam int unsigned KM_IRQ_ENABLE_REG_OFFSET                                                                  = 32'h00000014;
localparam int unsigned KM_IRQ_ENABLE_REG_ADDR                                                                    = 32'h00000014;
localparam int unsigned KM_CTRL_REG_OFFSET                                                                        = 32'h00000018;
localparam int unsigned KM_CTRL_REG_ADDR                                                                          = 32'h00000018;


//==============================================================================
// Default values for registers
//==============================================================================

localparam longint unsigned KM_MAILBOX_KM_WRITE_DATA_REG_REG_DEFAULT                                              = 32'h00000000;
localparam longint unsigned KM_MAILBOX_KM_WRITE_SEPARATOR_REG_REG_DEFAULT                                         = 32'h00000000;
localparam longint unsigned KM_MAILBOX_KM_READ_DATA_REG_REG_DEFAULT                                               = 32'h00000000;
localparam longint unsigned KM_MAILBOX_KM_STATUS_REG_REG_DEFAULT                                                  = 32'h00000005;
localparam longint unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_REG_DEFAULT                                              = 32'h00000000;
localparam longint unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_REG_DEFAULT                                              = 32'h00000000;
localparam longint unsigned KM_MAILBOX_KM_CTRL_REG_REG_DEFAULT                                                    = 32'h00000000;



//==============================================================================
// Bit Fields for Address Map: km_mailbox_km
//==============================================================================

localparam int unsigned KM_MAILBOX_KM_WRITE_DATA_REG_DATA_MASK                                                    = 32'hFFFFFFFF;
localparam int unsigned KM_MAILBOX_KM_WRITE_DATA_REG_DATA_SHIFT                                                   = 0;

localparam int unsigned KM_MAILBOX_KM_WRITE_SEPARATOR_REG_SET_MASK                                                = 32'h1;
localparam int unsigned KM_MAILBOX_KM_WRITE_SEPARATOR_REG_SET_SHIFT                                               = 0;

localparam int unsigned KM_MAILBOX_KM_WRITE_SEPARATOR_REG_RSVD_MASK                                               = 32'hFFFFFFFE;
localparam int unsigned KM_MAILBOX_KM_WRITE_SEPARATOR_REG_RSVD_SHIFT                                              = 1;

localparam int unsigned KM_MAILBOX_KM_READ_DATA_REG_DATA_MASK                                                     = 32'hFFFFFFFF;
localparam int unsigned KM_MAILBOX_KM_READ_DATA_REG_DATA_SHIFT                                                    = 0;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_EMPTY_MASK                                               = 32'h1;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_EMPTY_SHIFT                                              = 0;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_FULL_MASK                                                = 32'h2;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_FULL_SHIFT                                               = 1;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_EMPTY_MASK                                              = 32'h4;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_EMPTY_SHIFT                                             = 2;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_FULL_MASK                                               = 32'h8;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_FULL_SHIFT                                              = 3;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_DEPTH_MASK                                               = 32'hFF0;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_DEPTH_SHIFT                                              = 4;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_DEPTH_MASK                                              = 32'hFF000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_DEPTH_SHIFT                                             = 12;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_OVERFLOW_MASK                                            = 32'h100000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_OVERFLOW_SHIFT                                           = 20;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_OVERFLOW_MASK                                           = 32'h200000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_OVERFLOW_SHIFT                                          = 21;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_UNDERFLOW_MASK                                           = 32'h400000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_UNDERFLOW_SHIFT                                          = 22;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_UNDERFLOW_MASK                                          = 32'h800000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_UNDERFLOW_SHIFT                                         = 23;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_SEPARATOR_MASK                                           = 32'h1000000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_INBOUND_SEPARATOR_SHIFT                                          = 24;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_SEPARATOR_MASK                                          = 32'h2000000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_OUTBOUND_SEPARATOR_SHIFT                                         = 25;

localparam int unsigned KM_MAILBOX_KM_STATUS_REG_RSVD_MASK                                                        = 32'hFC000000;
localparam int unsigned KM_MAILBOX_KM_STATUS_REG_RSVD_SHIFT                                                       = 26;

localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_INBOUND_READ_DATA_AVAIL_MASK                                 = 32'h1;
localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_INBOUND_READ_DATA_AVAIL_SHIFT                                = 0;

localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_OUTBOUND_WRITE_SPACE_AVAIL_MASK                              = 32'h2;
localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_OUTBOUND_WRITE_SPACE_AVAIL_SHIFT                             = 1;

localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_OUTBOUND_OVERFLOW_MASK                                       = 32'h4;
localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_OUTBOUND_OVERFLOW_SHIFT                                      = 2;

localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_INBOUND_UNDERFLOW_MASK                                       = 32'h8;
localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_INBOUND_UNDERFLOW_SHIFT                                      = 3;

localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_FLUSHED_BY_SEP_MASK                                          = 32'h10;
localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_FLUSHED_BY_SEP_SHIFT                                         = 4;

localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_RSVD_MASK                                                    = 32'hFFFFFFE0;
localparam int unsigned KM_MAILBOX_KM_IRQ_STATUS_REG_RSVD_SHIFT                                                   = 5;

localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_INBOUND_READ_DATA_AVAIL_EN_MASK                              = 32'h1;
localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_INBOUND_READ_DATA_AVAIL_EN_SHIFT                             = 0;

localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_OUTBOUND_WRITE_SPACE_AVAIL_EN_MASK                           = 32'h2;
localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_OUTBOUND_WRITE_SPACE_AVAIL_EN_SHIFT                          = 1;

localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_OUTBOUND_OVERFLOW_EN_MASK                                    = 32'h4;
localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_OUTBOUND_OVERFLOW_EN_SHIFT                                   = 2;

localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_INBOUND_UNDERFLOW_EN_MASK                                    = 32'h8;
localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_INBOUND_UNDERFLOW_EN_SHIFT                                   = 3;

localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_FLUSHED_BY_SEP_EN_MASK                                       = 32'h10;
localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_FLUSHED_BY_SEP_EN_SHIFT                                      = 4;

localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_RSVD_MASK                                                    = 32'hFFFFFFE0;
localparam int unsigned KM_MAILBOX_KM_IRQ_ENABLE_REG_RSVD_SHIFT                                                   = 5;

localparam int unsigned KM_MAILBOX_KM_CTRL_REG_OUTBOUND_OVERFLOW_RESP_MASK                                        = 32'h1;
localparam int unsigned KM_MAILBOX_KM_CTRL_REG_OUTBOUND_OVERFLOW_RESP_SHIFT                                       = 0;

localparam int unsigned KM_MAILBOX_KM_CTRL_REG_INBOUND_UNDERFLOW_RESP_MASK                                        = 32'h2;
localparam int unsigned KM_MAILBOX_KM_CTRL_REG_INBOUND_UNDERFLOW_RESP_SHIFT                                       = 1;

localparam int unsigned KM_MAILBOX_KM_CTRL_REG_FLUSH_MASK                                                         = 32'h4;
localparam int unsigned KM_MAILBOX_KM_CTRL_REG_FLUSH_SHIFT                                                        = 2;

localparam int unsigned KM_MAILBOX_KM_CTRL_REG_RSVD_MASK                                                          = 32'hFFFFFFF8;
localparam int unsigned KM_MAILBOX_KM_CTRL_REG_RSVD_SHIFT                                                         = 3;





typedef struct packed {
    logic [31:0]   data ;
} km_mailbox_km_write_data_reg_reg_t;



typedef struct packed {
    logic [30:0]   rsvd ;
    logic [0:0]   set ;
} km_mailbox_km_write_separator_reg_reg_t;



typedef struct packed {
    logic [31:0]   data ;
} km_mailbox_km_read_data_reg_reg_t;



typedef struct packed {
    logic [5:0]   rsvd ;
    logic [0:0]   outbound_separator ;
    logic [0:0]   inbound_separator ;
    logic [0:0]   outbound_underflow ;
    logic [0:0]   inbound_underflow ;
    logic [0:0]   outbound_overflow ;
    logic [0:0]   inbound_overflow ;
    logic [7:0]   outbound_depth ;
    logic [7:0]   inbound_depth ;
    logic [0:0]   outbound_full ;
    logic [0:0]   outbound_empty ;
    logic [0:0]   inbound_full ;
    logic [0:0]   inbound_empty ;
} km_mailbox_km_status_reg_reg_t;



typedef struct packed {
    logic [26:0]   rsvd ;
    logic [0:0]   flushed_by_sep ;
    logic [0:0]   inbound_underflow ;
    logic [0:0]   outbound_overflow ;
    logic [0:0]   outbound_write_space_avail ;
    logic [0:0]   inbound_read_data_avail ;
} km_mailbox_km_irq_status_reg_reg_t;



typedef struct packed {
    logic [26:0]   rsvd ;
    logic [0:0]   flushed_by_sep_en ;
    logic [0:0]   inbound_underflow_en ;
    logic [0:0]   outbound_overflow_en ;
    logic [0:0]   outbound_write_space_avail_en ;
    logic [0:0]   inbound_read_data_avail_en ;
} km_mailbox_km_irq_enable_reg_reg_t;



typedef struct packed {
    logic [28:0]   rsvd ;
    logic [0:0]   flush ;
    logic [0:0]   inbound_underflow_resp ;
    logic [0:0]   outbound_overflow_resp ;
} km_mailbox_km_ctrl_reg_reg_t;



typedef struct packed {
    km_mailbox_km_ctrl_reg_reg_t km_ctrl;
    km_mailbox_km_irq_enable_reg_reg_t km_irq_enable;
    km_mailbox_km_irq_status_reg_reg_t km_irq_status;
    km_mailbox_km_status_reg_reg_t km_status;
    km_mailbox_km_read_data_reg_reg_t km_read_data;
    km_mailbox_km_write_separator_reg_reg_t km_write_separator;
    km_mailbox_km_write_data_reg_reg_t km_write_data;
} km_mailbox_km_regmap_t;

`endif
