/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was auto-generated by this script:
 *       create_reg_sv_header.py   (r2025-06-03)
 * ... from this input file:
 *       otbn_wrapper_key.rdl
 * ... using this as the target address space:
 *       otbn_wrapper_key
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef OTBN_WRAPPER_KEY_REG_SVH
`define OTBN_WRAPPER_KEY_REG_SVH



//==============================================================================
// Addresses for Address Map: otbn_wrapper_key
//==============================================================================


localparam int unsigned OTBN_WRAPPER_KEY_REG_MAP_BASE_ADDR                                                        = 32'h00000000;
localparam int unsigned OTBN_WRAPPER_KEY_REG_MAP_SIZE                                                             = 32'h00000064;


localparam int unsigned KEY_SHARE0_0__REG_OFFSET                                                                  = 32'h00000000;
localparam int unsigned KEY_SHARE0_0__REG_ADDR                                                                    = 32'h00000000;
localparam int unsigned KEY_SHARE0_1__REG_OFFSET                                                                  = 32'h00000004;
localparam int unsigned KEY_SHARE0_1__REG_ADDR                                                                    = 32'h00000004;
localparam int unsigned KEY_SHARE0_2__REG_OFFSET                                                                  = 32'h00000008;
localparam int unsigned KEY_SHARE0_2__REG_ADDR                                                                    = 32'h00000008;
localparam int unsigned KEY_SHARE0_3__REG_OFFSET                                                                  = 32'h0000000C;
localparam int unsigned KEY_SHARE0_3__REG_ADDR                                                                    = 32'h0000000C;
localparam int unsigned KEY_SHARE0_4__REG_OFFSET                                                                  = 32'h00000010;
localparam int unsigned KEY_SHARE0_4__REG_ADDR                                                                    = 32'h00000010;
localparam int unsigned KEY_SHARE0_5__REG_OFFSET                                                                  = 32'h00000014;
localparam int unsigned KEY_SHARE0_5__REG_ADDR                                                                    = 32'h00000014;
localparam int unsigned KEY_SHARE0_6__REG_OFFSET                                                                  = 32'h00000018;
localparam int unsigned KEY_SHARE0_6__REG_ADDR                                                                    = 32'h00000018;
localparam int unsigned KEY_SHARE0_7__REG_OFFSET                                                                  = 32'h0000001C;
localparam int unsigned KEY_SHARE0_7__REG_ADDR                                                                    = 32'h0000001C;
localparam int unsigned KEY_SHARE0_8__REG_OFFSET                                                                  = 32'h00000020;
localparam int unsigned KEY_SHARE0_8__REG_ADDR                                                                    = 32'h00000020;
localparam int unsigned KEY_SHARE0_9__REG_OFFSET                                                                  = 32'h00000024;
localparam int unsigned KEY_SHARE0_9__REG_ADDR                                                                    = 32'h00000024;
localparam int unsigned KEY_SHARE0_10__REG_OFFSET                                                                 = 32'h00000028;
localparam int unsigned KEY_SHARE0_10__REG_ADDR                                                                   = 32'h00000028;
localparam int unsigned KEY_SHARE0_11__REG_OFFSET                                                                 = 32'h0000002C;
localparam int unsigned KEY_SHARE0_11__REG_ADDR                                                                   = 32'h0000002C;
localparam int unsigned KEY_SHARE1_0__REG_OFFSET                                                                  = 32'h00000030;
localparam int unsigned KEY_SHARE1_0__REG_ADDR                                                                    = 32'h00000030;
localparam int unsigned KEY_SHARE1_1__REG_OFFSET                                                                  = 32'h00000034;
localparam int unsigned KEY_SHARE1_1__REG_ADDR                                                                    = 32'h00000034;
localparam int unsigned KEY_SHARE1_2__REG_OFFSET                                                                  = 32'h00000038;
localparam int unsigned KEY_SHARE1_2__REG_ADDR                                                                    = 32'h00000038;
localparam int unsigned KEY_SHARE1_3__REG_OFFSET                                                                  = 32'h0000003C;
localparam int unsigned KEY_SHARE1_3__REG_ADDR                                                                    = 32'h0000003C;
localparam int unsigned KEY_SHARE1_4__REG_OFFSET                                                                  = 32'h00000040;
localparam int unsigned KEY_SHARE1_4__REG_ADDR                                                                    = 32'h00000040;
localparam int unsigned KEY_SHARE1_5__REG_OFFSET                                                                  = 32'h00000044;
localparam int unsigned KEY_SHARE1_5__REG_ADDR                                                                    = 32'h00000044;
localparam int unsigned KEY_SHARE1_6__REG_OFFSET                                                                  = 32'h00000048;
localparam int unsigned KEY_SHARE1_6__REG_ADDR                                                                    = 32'h00000048;
localparam int unsigned KEY_SHARE1_7__REG_OFFSET                                                                  = 32'h0000004C;
localparam int unsigned KEY_SHARE1_7__REG_ADDR                                                                    = 32'h0000004C;
localparam int unsigned KEY_SHARE1_8__REG_OFFSET                                                                  = 32'h00000050;
localparam int unsigned KEY_SHARE1_8__REG_ADDR                                                                    = 32'h00000050;
localparam int unsigned KEY_SHARE1_9__REG_OFFSET                                                                  = 32'h00000054;
localparam int unsigned KEY_SHARE1_9__REG_ADDR                                                                    = 32'h00000054;
localparam int unsigned KEY_SHARE1_10__REG_OFFSET                                                                 = 32'h00000058;
localparam int unsigned KEY_SHARE1_10__REG_ADDR                                                                   = 32'h00000058;
localparam int unsigned KEY_SHARE1_11__REG_OFFSET                                                                 = 32'h0000005C;
localparam int unsigned KEY_SHARE1_11__REG_ADDR                                                                   = 32'h0000005C;
localparam int unsigned KEY_CTRL_REG_OFFSET                                                                       = 32'h00000060;
localparam int unsigned KEY_CTRL_REG_ADDR                                                                         = 32'h00000060;


//==============================================================================
// Default values for registers
//==============================================================================

localparam longint unsigned OTBN_WRAPPER_KEY_KEY_WORD_REG_REG_DEFAULT                                             = 32'h00000000;
localparam longint unsigned OTBN_WRAPPER_KEY_KEY_CTRL_REG_REG_DEFAULT                                             = 32'h00000000;



//==============================================================================
// Bit Fields for Address Map: otbn_wrapper_key
//==============================================================================

localparam int unsigned OTBN_WRAPPER_KEY_KEY_WORD_REG_DATA_MASK                                                   = 32'hFFFFFFFF;
localparam int unsigned OTBN_WRAPPER_KEY_KEY_WORD_REG_DATA_SHIFT                                                  = 0;

localparam int unsigned OTBN_WRAPPER_KEY_KEY_CTRL_REG_KEY_VALID_MASK                                              = 32'h1;
localparam int unsigned OTBN_WRAPPER_KEY_KEY_CTRL_REG_KEY_VALID_SHIFT                                             = 0;

localparam int unsigned OTBN_WRAPPER_KEY_KEY_CTRL_REG_RSVD_MASK                                                   = 32'hFFFFFFFE;
localparam int unsigned OTBN_WRAPPER_KEY_KEY_CTRL_REG_RSVD_SHIFT                                                  = 1;





typedef struct packed {
    logic [31:0]   data ;
} otbn_wrapper_key_key_word_reg_reg_t;



typedef struct packed {
    logic [30:0]   rsvd ;
    logic [0:0]   key_valid ;
} otbn_wrapper_key_key_ctrl_reg_reg_t;



typedef struct packed {
    otbn_wrapper_key_key_ctrl_reg_reg_t key_ctrl;
    otbn_wrapper_key_key_word_reg_reg_t [11:0] key_share1;
    otbn_wrapper_key_key_word_reg_reg_t [11:0] key_share0;
} otbn_wrapper_key_regmap_t;

`endif
