/*
 * Placeholder for the VeeR EL2 snapshot header.
 *
 * Upstream this file is generated by configs/veer.config in the Cores-VeeR-EL2
 * repo and describes the ICCM/DCCM/PIC geometry of the core.  The SEP VP tests
 * never read it: common.mk only lists it as a prerequisite, and the single
 * consumer (common/crt0_bl1.s) belongs to the BL1 flow, which the VP does not
 * run.  Generate the real snapshot and drop it here if you need that flow.
 */
#ifndef SEP_EL2_SNAPSHOT_DEFINES_H
#define SEP_EL2_SNAPSHOT_DEFINES_H
#endif
