// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package sep_reset_ctrl_reg_pkg;

    localparam SEP_RESET_CTRL_REG_DATA_WIDTH = 64;
    localparam SEP_RESET_CTRL_REG_MIN_ADDR_WIDTH = 4;
    localparam SEP_RESET_CTRL_REG_SIZE = 'h8;

    typedef struct {
        logic value;
    } sep_reset_ctrl__SW_RESET_N__km_sw_rst_n__out_t;

    typedef struct {
        logic value;
    } sep_reset_ctrl__SW_RESET_N__otbn_sw_rst_n__out_t;

    typedef struct {
        logic value;
    } sep_reset_ctrl__SW_RESET_N__aes_sw_rst_n__out_t;

    typedef struct {
        logic value;
    } sep_reset_ctrl__SW_RESET_N__hmac_sw_rst_n__out_t;

    typedef struct {
        logic value;
    } sep_reset_ctrl__SW_RESET_N__kmac_sw_rst_n__out_t;

    typedef struct {
        sep_reset_ctrl__SW_RESET_N__km_sw_rst_n__out_t km_sw_rst_n;
        sep_reset_ctrl__SW_RESET_N__otbn_sw_rst_n__out_t otbn_sw_rst_n;
        sep_reset_ctrl__SW_RESET_N__aes_sw_rst_n__out_t aes_sw_rst_n;
        sep_reset_ctrl__SW_RESET_N__hmac_sw_rst_n__out_t hmac_sw_rst_n;
        sep_reset_ctrl__SW_RESET_N__kmac_sw_rst_n__out_t kmac_sw_rst_n;
    } sep_reset_ctrl__SW_RESET_N__out_t;

    typedef struct {
        sep_reset_ctrl__SW_RESET_N__out_t SW_RESET_N;
    } sep_reset_ctrl__out_t;
endpackage
