// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module sep_reset_ctrl_reg (
        input wire clk,
        input wire arst_n,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [3:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [63:0] s_axil_wdata,
        input wire [7:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [3:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [63:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        output sep_reset_ctrl_reg_pkg::sep_reset_ctrl__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [63:0] cpuif_wr_data;
    logic [63:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [63:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [3:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [3:0] axil_awaddr;
    logic axil_wvalid;
    logic [63:0] axil_wdata;
    logic [7:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<8; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[3:3], 3'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[3:3], 3'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[3:3], 3'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    logic axil_resp_buffer_is_wr[2];
    logic axil_resp_buffer_err[2];
    logic [63:0] axil_resp_buffer_rdata[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer_is_wr[i] <= '0;
                axil_resp_buffer_err[i] <= '0;
                axil_resp_buffer_rdata[i] <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '0;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_rd_err;
                    axil_resp_buffer_rdata[axil_resp_wptr[0:0]] <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '1;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer_is_wr[axil_resp_rptr[0:0]]) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer_rdata[axil_resp_rptr[0:0]];
        if(axil_resp_buffer_err[axil_resp_rptr[0:0]]) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic SW_RESET_N;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [3:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [63:0] decoded_wr_data;
    logic [63:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.SW_RESET_N = cpuif_req_masked & (cpuif_addr == 4'h0);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } km_sw_rst_n;
            struct {
                logic next;
                logic load_next;
            } otbn_sw_rst_n;
            struct {
                logic next;
                logic load_next;
            } aes_sw_rst_n;
            struct {
                logic next;
                logic load_next;
            } hmac_sw_rst_n;
            struct {
                logic next;
                logic load_next;
            } kmac_sw_rst_n;
        } SW_RESET_N;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } km_sw_rst_n;
            struct {
                logic value;
            } otbn_sw_rst_n;
            struct {
                logic value;
            } aes_sw_rst_n;
            struct {
                logic value;
            } hmac_sw_rst_n;
            struct {
                logic value;
            } kmac_sw_rst_n;
        } SW_RESET_N;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: sep_reset_ctrl.SW_RESET_N.km_sw_rst_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SW_RESET_N.km_sw_rst_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.SW_RESET_N && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SW_RESET_N.km_sw_rst_n.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.SW_RESET_N.km_sw_rst_n.next = next_c;
        field_combo.SW_RESET_N.km_sw_rst_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.SW_RESET_N.km_sw_rst_n.value <= 1'h0;
        end else begin
            if(field_combo.SW_RESET_N.km_sw_rst_n.load_next) begin
                field_storage.SW_RESET_N.km_sw_rst_n.value <= field_combo.SW_RESET_N.km_sw_rst_n.next;
            end
        end
    end
    assign hwif_out.SW_RESET_N.km_sw_rst_n.value = field_storage.SW_RESET_N.km_sw_rst_n.value;
    // Field: sep_reset_ctrl.SW_RESET_N.otbn_sw_rst_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SW_RESET_N.otbn_sw_rst_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.SW_RESET_N && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SW_RESET_N.otbn_sw_rst_n.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.SW_RESET_N.otbn_sw_rst_n.next = next_c;
        field_combo.SW_RESET_N.otbn_sw_rst_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.SW_RESET_N.otbn_sw_rst_n.value <= 1'h1;
        end else begin
            if(field_combo.SW_RESET_N.otbn_sw_rst_n.load_next) begin
                field_storage.SW_RESET_N.otbn_sw_rst_n.value <= field_combo.SW_RESET_N.otbn_sw_rst_n.next;
            end
        end
    end
    assign hwif_out.SW_RESET_N.otbn_sw_rst_n.value = field_storage.SW_RESET_N.otbn_sw_rst_n.value;
    // Field: sep_reset_ctrl.SW_RESET_N.aes_sw_rst_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SW_RESET_N.aes_sw_rst_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.SW_RESET_N && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SW_RESET_N.aes_sw_rst_n.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.SW_RESET_N.aes_sw_rst_n.next = next_c;
        field_combo.SW_RESET_N.aes_sw_rst_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.SW_RESET_N.aes_sw_rst_n.value <= 1'h1;
        end else begin
            if(field_combo.SW_RESET_N.aes_sw_rst_n.load_next) begin
                field_storage.SW_RESET_N.aes_sw_rst_n.value <= field_combo.SW_RESET_N.aes_sw_rst_n.next;
            end
        end
    end
    assign hwif_out.SW_RESET_N.aes_sw_rst_n.value = field_storage.SW_RESET_N.aes_sw_rst_n.value;
    // Field: sep_reset_ctrl.SW_RESET_N.hmac_sw_rst_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SW_RESET_N.hmac_sw_rst_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.SW_RESET_N && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SW_RESET_N.hmac_sw_rst_n.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.SW_RESET_N.hmac_sw_rst_n.next = next_c;
        field_combo.SW_RESET_N.hmac_sw_rst_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.SW_RESET_N.hmac_sw_rst_n.value <= 1'h1;
        end else begin
            if(field_combo.SW_RESET_N.hmac_sw_rst_n.load_next) begin
                field_storage.SW_RESET_N.hmac_sw_rst_n.value <= field_combo.SW_RESET_N.hmac_sw_rst_n.next;
            end
        end
    end
    assign hwif_out.SW_RESET_N.hmac_sw_rst_n.value = field_storage.SW_RESET_N.hmac_sw_rst_n.value;
    // Field: sep_reset_ctrl.SW_RESET_N.kmac_sw_rst_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SW_RESET_N.kmac_sw_rst_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.SW_RESET_N && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SW_RESET_N.kmac_sw_rst_n.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.SW_RESET_N.kmac_sw_rst_n.next = next_c;
        field_combo.SW_RESET_N.kmac_sw_rst_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.SW_RESET_N.kmac_sw_rst_n.value <= 1'h1;
        end else begin
            if(field_combo.SW_RESET_N.kmac_sw_rst_n.load_next) begin
                field_storage.SW_RESET_N.kmac_sw_rst_n.value <= field_combo.SW_RESET_N.kmac_sw_rst_n.next;
            end
        end
    end
    assign hwif_out.SW_RESET_N.kmac_sw_rst_n.value = field_storage.SW_RESET_N.kmac_sw_rst_n.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [3:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [63:0] readback_data;
    always_comb begin
        automatic logic [63:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 4'h0) begin
            readback_data_var[0] = field_storage.SW_RESET_N.km_sw_rst_n.value;
            readback_data_var[1] = field_storage.SW_RESET_N.otbn_sw_rst_n.value;
            readback_data_var[2] = field_storage.SW_RESET_N.aes_sw_rst_n.value;
            readback_data_var[3] = field_storage.SW_RESET_N.hmac_sw_rst_n.value;
            readback_data_var[4] = field_storage.SW_RESET_N.kmac_sw_rst_n.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
