// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
/*
 * OTBN P256 ECDSA Signature Verification Test
 *
 * This test demonstrates P256 ECDSA signature verification using the OTBN coprocessor.
 * It uses test vectors from OpenTitan's assembly test suite to verify correct operation.
 *
 * Test vectors are sourced from:
 * opentitan/sw/otbn/crypto/tests/p256_ecdsa_verify_test.s
 *
 * The test:
 * 1. Loads message digest, signature components (r, s), and public key into OTBN DMEM
 * 2. Executes the P256 ECDSA verification algorithm in OTBN
 * 3. Reads back the derived x_r value and confirms that it matches the signature R component
 *
 * MIGRATED: Now uses OCH SEP register infrastructure with absolute addresses
 * from meta/registers/c/och_sep_top_reg.h instead of hardcoded base addresses.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "test_completion.h"
#include "p256_ecdsa_otbn.h"  // Generated by common_otbn infrastructure
#include "och_sep_top_reg.h"  // OCH SEP register map with absolute addresses
#include "och_sep_common.h"   // Register access macros (WRITE_REG/READ_REG)
#include "sep_outbound_filter.h"

// Mode constants (from OpenTitan run_p256.s)
#define MODE_VERIFY             0x1f8

// P256 scalar size
#define P256_SCALAR_WORDS       8

// OTBN status register values
#define OTBN_STATUS_IDLE        0x00
#define OTBN_STATUS_BUSY_EXECUTE 0x01

// OTBN command register values
#define OTBN_CMD_EXECUTE        0xD8
#define OTBN_CMD_SEC_WIPE_DMEM  0xC3
#define OTBN_CMD_SEC_WIPE_IMEM  0x1E

// ============================================================================
// Register and Memory Access - Using OCH SEP Common Macros
// ============================================================================
// Uses WRITE_REG/READ_REG macros from och_sep_common.h (similar to tt_sep's
// WRITE_EXT/READ_EXT), but without address offset since och_sep_top_reg.h
// already provides absolute addresses.
//
// tt_sep approach:
//   WRITE_EXT(addr, value)  -> adds SEP_EXT_BASE (0xc000_0000) to addr
//   READ_EXT(addr)          -> adds SEP_EXT_BASE (0xc000_0000) to addr
//
// och_sep approach:
//   WRITE_REG(addr, value)  -> uses addr directly (already absolute)
//   READ_REG(addr)          -> uses addr directly (already absolute)
// ============================================================================

// Memory access - word-indexed access to IMEM and DMEM
#define OTBN_IMEM(word)   READ_MEM_WORD(OTBN_IMEM_MEM_BASE_ADDR, word)
#define OTBN_DMEM(word)   READ_MEM_WORD(OTBN_DMEM_MEM_BASE_ADDR, word)
#define OTBN_IMEM_WRITE(word, value)   WRITE_MEM_WORD(OTBN_IMEM_MEM_BASE_ADDR, word, value)
#define OTBN_DMEM_WRITE(word, value)   WRITE_MEM_WORD(OTBN_DMEM_MEM_BASE_ADDR, word, value)

// OTBN DMEM offsets for P256 verification operation (extracted from ELF symbol table)
#define DMEM_MODE_OFFSET        OTBN_ADDR_T_INIT(p256_ecdsa, mode)      // mode (operation mode selection)
#define DMEM_OK_OFFSET          OTBN_ADDR_T_INIT(p256_ecdsa, ok)        // ok (verification result)
#define DMEM_MSG_OFFSET         OTBN_ADDR_T_INIT(p256_ecdsa, msg)       // msg (message digest to verify)
#define DMEM_R_OFFSET           OTBN_ADDR_T_INIT(p256_ecdsa, r)         // r (signature R component input)
#define DMEM_S_OFFSET           OTBN_ADDR_T_INIT(p256_ecdsa, s)         // s (signature S component input)
#define DMEM_X_OFFSET           OTBN_ADDR_T_INIT(p256_ecdsa, x)         // x (public key x-coordinate)
#define DMEM_Y_OFFSET           OTBN_ADDR_T_INIT(p256_ecdsa, y)         // y (public key y-coordinate)
#define DMEM_X_R_OFFSET         OTBN_ADDR_T_INIT(p256_ecdsa, x_r)       // x_r (recovered x-coordinate output)

// ============================================================================
// OpenTitan ECDSA P-256 Assembly Test Vector - Debug Analysis
// ============================================================================
//
// Source: opentitan/sw/otbn/crypto/tests/p256_ecdsa_verify_test.s
// These vectors are from OpenTitan's assembly test suite
// Message: "Hello OTBN." (SHA-256 digest)
// Goal: Debug why x_r ≠ R and fix the verification algorithm
//
// ============================================================================

// Test message hash - From OpenTitan assembly test (p256_ecdsa_verify_test.s)
// Input: SHA-256 digest of "Hello OTBN."
// Digest: 0x06d71207...4456fd21 (already in little-endian word format)
static const uint32_t test_message[P256_SCALAR_WORDS] = {
    0x4456fd21, 0x400bdd7d, 0xb54d7452, 0x17d015f1,
    0x90d4d90b, 0xb028ad8a, 0x6ce90fef, 0x06d71207
};

// Test signature R component - From OpenTitan assembly test
// Already in OTBN little-endian word format
static const uint32_t test_signature_r_otbn[P256_SCALAR_WORDS] = {
    0x80a9674a, 0x1147ea56, 0x0c7d87dd, 0x99504edd,
    0xbe064de2, 0x6b35843c, 0x7dd27f33, 0x815215ad
};

// Test signature S component - From OpenTitan assembly test
// Already in OTBN little-endian word format
static const uint32_t test_signature_s_otbn[P256_SCALAR_WORDS] = {
    0xc93fd605, 0xd0b1051e, 0xe90a6d17, 0x4dad9404,
    0x99e589ad, 0x86e30cd9, 0xc4440420, 0xa3991e01
};

// Test public key X component - From OpenTitan assembly test
// Already in OTBN little-endian word format
static const uint32_t test_public_key_x_otbn[P256_SCALAR_WORDS] = {
    0xbfa8c334, 0x9773b7b3, 0xf36b0689, 0x6ec0c0b2,
    0xdb6c8bf3, 0x1628ce58, 0xfacdc546, 0xb5511a6a
};

// Test public key Y component - From OpenTitan assembly test
// Already in OTBN little-endian word format
static const uint32_t test_public_key_y_otbn[P256_SCALAR_WORDS] = {
    0x9e008c2e, 0xa8707058, 0xab9c6924, 0x7f7a11d0,
    0xb53a17fa, 0x43dd09ea, 0x1f31c143, 0x42a1c697
};

/**
 * Wait for OTBN to become idle
 */
static int otbn_wait_for_idle(void) {
    int timeout = 1000000;  // Large timeout for simulation environments
    int print_counter = 0;  // Debug: print every 100k iterations

    while (timeout-- > 0) {
        uint32_t status = READ_REG(OTBN_STATUS_REG_ADDR);

        // Debug: Print status periodically
        if (++print_counter >= 100000) {
            printf("  [DEBUG] Waiting for OTBN idle... status=0x%02x (expect 0x%02x), timeout=%d\n",
                   status, OTBN_STATUS_IDLE, timeout);
            print_counter = 0;
        }

        if (status == OTBN_STATUS_IDLE) {
            return 0;  // Success
        }
        // Add a small delay to prevent bus contention
        for (volatile int i = 0; i < 100; i++);
    }

    printf("ERROR: OTBN timeout waiting for idle state\n");
    return -1;  // Timeout
}


/**
 * Manually initialize OTBN DMEM with zeros
 * This ensures a clean, predictable memory state
 */
static int otbn_dmem_zero_init(void) {
    printf("Manually initializing OTBN DMEM with zeros\n");

    // Wait for OTBN to be idle before starting
    if (otbn_wait_for_idle() != 0) {
        printf("ERROR: OTBN not idle before DMEM initialization\n");
        return -1;
    }

    // Zero out all visible DMEM locations
    // DMEM has 768 visible 32-bit words (3KB) over the bus interface
    const uint32_t dmem_size_words = 768;
    const uint32_t zero_value = 0x00000000;

    printf("  Writing zeros to DMEM addresses 0x000 to 0x%03x...\n", (dmem_size_words - 1) * 4);

    for (uint32_t addr = 0; addr < dmem_size_words; addr++) {
        OTBN_DMEM_WRITE(addr, zero_value);
    }

    // Reset the checksum register to 0 after DMEM initialization
    printf("  Resetting LOAD_CHECKSUM register to 0...\n");
    WRITE_REG(OTBN_LOAD_CHECKSUM_REG_ADDR, 0x00000000);

    printf("OTBN DMEM zero initialization completed (%u words written)\n", dmem_size_words);
    return 0;
}

/**
 * Load OTBN instruction memory with P256 verification program
 */
static int otbn_load_program(void) {
    // Load IMEM (instruction memory)
    size_t imem_words = otbn_p256_ecdsa_imem_words;
    printf("Loading OTBN IMEM: %zu words\n", imem_words);

    for (size_t i = 0; i < imem_words; i++) {
        OTBN_IMEM_WRITE(i, otbn_p256_ecdsa_imem[i]);
    }

    // Load DMEM (data memory)
    size_t dmem_words = otbn_p256_ecdsa_dmem_words;
    printf("Loading OTBN DMEM: %zu words (includes P256 domain parameters)\n", dmem_words);

    for (size_t i = 0; i < dmem_words; i++) {
        OTBN_DMEM_WRITE(i, otbn_p256_ecdsa_dmem[i]);
    }

    // Verify the checksum if available
    if (OTBN_P256_ECDSA_EXPECTED_CRC != 0) {
        uint32_t actual_crc = READ_REG(OTBN_LOAD_CHECKSUM_REG_ADDR);
        printf("Expected CRC: 0x%08x\n", OTBN_P256_ECDSA_EXPECTED_CRC);
        printf("Actual CRC:   0x%08x\n", actual_crc);

        if (actual_crc == OTBN_P256_ECDSA_EXPECTED_CRC) {
            printf("CRC validation PASSED\n");
        } else {
            printf("CRC validation FAILED\n");
            return -1;
        }
    }

    printf("OTBN program loaded successfully (IMEM + DMEM with domain parameters)\n");
    return 0;
}

/**
 * Write data to OTBN DMEM at specified offset
 */
static int otbn_write_dmem(uint32_t offset, const uint32_t* data, size_t word_count) {
    for (size_t i = 0; i < word_count; i++) {
        // Calculate word address in DMEM
        uint32_t word_addr = (offset + i * 4) / 4;
        OTBN_DMEM_WRITE(word_addr, data[i]);
    }
    return 0;
}

/**
 * Read data from OTBN DMEM at specified offset
 */
static int otbn_read_dmem(uint32_t offset, uint32_t* data, size_t word_count) {
    for (size_t i = 0; i < word_count; i++) {
        // Calculate word address in DMEM
        uint32_t word_addr = (offset + i * 4) / 4;
        data[i] = OTBN_DMEM(word_addr);
    }
    return 0;
}

/**
 * Setup test inputs for P256 ECDSA verification
 */
static int setup_verification_inputs(void) {
    printf("Setting up ECDSA verification test inputs...\n");

    // Set operation mode to verification
    uint32_t mode = MODE_VERIFY;
    if (otbn_write_dmem(DMEM_MODE_OFFSET, &mode, 1) != 0) {
        return -1;
    }
    printf("Set operation mode to VERIFY (0x%03x) at DMEM offset 0x%03x\n",
           mode, DMEM_MODE_OFFSET);

    // Print message digest
    printf("test_message: ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", test_message[i]);
    }
    printf("\n");

    if (otbn_write_dmem(DMEM_MSG_OFFSET, test_message, P256_SCALAR_WORDS) != 0) {
        return -1;
    }
    printf("Wrote message digest to DMEM offset 0x%03x\n", DMEM_MSG_OFFSET);

    // Print signature R component
    printf("test_signature_r_otbn: ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", test_signature_r_otbn[i]);
    }
    printf("\n");

    // Write signature R component
    if (otbn_write_dmem(DMEM_R_OFFSET, test_signature_r_otbn, P256_SCALAR_WORDS) != 0) {
        return -1;
    }
    printf("Wrote signature R component to DMEM offset 0x%03x\n", DMEM_R_OFFSET);

    // Print signature S component
    printf("test_signature_s_otbn: ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", test_signature_s_otbn[i]);
    }
    printf("\n");

    // Write signature S component
    if (otbn_write_dmem(DMEM_S_OFFSET, test_signature_s_otbn, P256_SCALAR_WORDS) != 0) {
        return -1;
    }
    printf("Wrote signature S component to DMEM offset 0x%03x\n", DMEM_S_OFFSET);

    // Print public key X component
    printf("test_public_key_x_otbn: ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", test_public_key_x_otbn[i]);
    }
    printf("\n");

    // Write public key X component
    if (otbn_write_dmem(DMEM_X_OFFSET, test_public_key_x_otbn, P256_SCALAR_WORDS) != 0) {
        return -1;
    }
    printf("Wrote public key X component to DMEM offset 0x%03x\n", DMEM_X_OFFSET);

    // Print public key Y component
    printf("test_public_key_y_otbn: ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", test_public_key_y_otbn[i]);
    }
    printf("\n");

    // Write public key Y component
    if (otbn_write_dmem(DMEM_Y_OFFSET, test_public_key_y_otbn, P256_SCALAR_WORDS) != 0) {
        return -1;
    }
    printf("Wrote public key Y component to DMEM offset 0x%03x\n", DMEM_Y_OFFSET);

    return 0;
}

/**
 * Helper function to compare two uint32_t arrays and print results
 */
static int compare_arrays(const uint32_t* expected, const uint32_t* actual, size_t count, const char* name) {
    int match = 1;
    for (size_t i = 0; i < count; i++) {
        if (expected[i] != actual[i]) {
            match = 0;
            break;
        }
    }

    printf("%s: %s\n", name, match ? "MATCH" : "MISMATCH");

    if (!match) {
        printf("  Expected: ");
        for (size_t i = 0; i < count; i++) {
            printf("%08x ", expected[i]);
        }
        printf("\n  Actual:   ");
        for (size_t i = 0; i < count; i++) {
            printf("%08x ", actual[i]);
        }
        printf("\n");
    }
    return match;
}

/**
 * Verify input data by reading back from DMEM and comparing with expected values
 */
static int verify_input_data(void) {
    printf("\n=== DMEM Input Data Verification ===\n");

    int errors = 0;
    uint32_t readback_data[P256_SCALAR_WORDS];

    // 1. Verify mode
    uint32_t readback_mode;
    if (otbn_read_dmem(DMEM_MODE_OFFSET, &readback_mode, 1) != 0) {
        printf("ERROR: Failed to read back mode - READ OPERATION FAILED\n");
        return -1;
    }
    uint32_t expected_mode = MODE_VERIFY;
    printf("Mode: %s (expected 0x%08x, actual 0x%08x)\n",
           (readback_mode == expected_mode) ? "MATCH" : "MISMATCH",
           expected_mode, readback_mode);
    if (readback_mode != expected_mode) {
        printf("  ERROR: Failed to read back Mode\n");
        errors++;
    }

    // 2. Verify message digest
    if (otbn_read_dmem(DMEM_MSG_OFFSET, readback_data, P256_SCALAR_WORDS) != 0) {
        printf("ERROR: Failed to read back message digest\n");
        return -1;
    }
    // Compare with original test vector
    if (!compare_arrays(test_message, readback_data, P256_SCALAR_WORDS, "Message Digest")) {
        errors++;
    }

    // 3. Verify signature R component
    if (otbn_read_dmem(DMEM_R_OFFSET, readback_data, P256_SCALAR_WORDS) != 0) {
        printf("ERROR: Failed to read back signature R\n");
        return -1;
    }
    // Compare with original test vector
    if (!compare_arrays(test_signature_r_otbn, readback_data, P256_SCALAR_WORDS, "Signature R")) {
        errors++;
    }

    // 4. Verify signature S component
    if (otbn_read_dmem(DMEM_S_OFFSET, readback_data, P256_SCALAR_WORDS) != 0) {
        printf("ERROR: Failed to read back signature S\n");
        return -1;
    }
    // Compare with original test vector
    if (!compare_arrays(test_signature_s_otbn, readback_data, P256_SCALAR_WORDS, "Signature S")) {
        errors++;
    }

    // 5. Verify public key X component
    if (otbn_read_dmem(DMEM_X_OFFSET, readback_data, P256_SCALAR_WORDS) != 0) {
        printf("ERROR: Failed to read back public key X\n");
        return -1;
    }
    // Compare with original test vector
    if (!compare_arrays(test_public_key_x_otbn, readback_data, P256_SCALAR_WORDS, "Public Key X")) {
        errors++;
    }

    // 6. Verify public key Y component
    if (otbn_read_dmem(DMEM_Y_OFFSET, readback_data, P256_SCALAR_WORDS) != 0) {
        printf("ERROR: Failed to read back public key Y\n");
        return -1;
    }
    // Compare with original test vector
    if (!compare_arrays(test_public_key_y_otbn, readback_data, P256_SCALAR_WORDS, "Public Key Y")) {
        errors++;
    }

    printf("=== Input Verification Summary ===\n");
    printf("Total errors: %d\n", errors);
    if (errors == 0) {
        printf("SUCCESS: All input data verified correctly!\n");
    } else {
        printf("FAILED: Input data verification found %d mismatches\n", errors);
    }
    printf("\n");

    return (errors == 0) ? 0 : -1;
}

/**
 * Execute OTBN P256 verification operation
 */
static int execute_verification(void) {
    printf("Executing OTBN P256 ECDSA verification...\n");

    // Debug: Check status before sending command
    uint32_t status_before = READ_REG(OTBN_STATUS_REG_ADDR);
    printf("  [DEBUG] OTBN status before execute: 0x%02x\n", status_before);
    printf("  [DEBUG] Writing 0x%02x to OTBN_CMD_REG (addr=0x%08x)\n",
           OTBN_CMD_EXECUTE, OTBN_CMD_REG_ADDR);

    // Send execute command
    WRITE_REG(OTBN_CMD_REG_ADDR, OTBN_CMD_EXECUTE);

    // Debug: Check status after sending command
    uint32_t status_after = READ_REG(OTBN_STATUS_REG_ADDR);
    printf("  [DEBUG] OTBN status after execute: 0x%02x\n", status_after);

    // Wait for completion
    if (otbn_wait_for_idle() != 0) {
        return -1;
    }

    // Check for errors
    uint32_t err_bits = READ_REG(OTBN_ERR_BITS_REG_ADDR);
    if (err_bits != 0) {
        printf("ERROR: OTBN execution failed with error bits: 0x%08x\n", err_bits);
        return -1;
    }

    printf("OTBN verification completed successfully\n");
    return 0;
}

/**
 * Check verification results
 */
static int check_verification_results(void) {
    printf("Checking verification results...\n");

    // Debug: Print all the memory offsets we're using
    printf("Debug: Memory offsets:\n");
    printf("  DMEM_MODE_OFFSET = 0x%03x\n", DMEM_MODE_OFFSET);
    printf("  DMEM_OK_OFFSET   = 0x%03x\n", DMEM_OK_OFFSET);
    printf("  DMEM_X_R_OFFSET  = 0x%03x\n", DMEM_X_R_OFFSET);

    // Read the 'ok' status flag
    uint32_t ok_status;
    if (otbn_read_dmem(DMEM_OK_OFFSET, &ok_status, 1) != 0) {
        return -1;
    }

    // Debug: Also read mode to see what's there
    uint32_t mode_value;
    if (otbn_read_dmem(DMEM_MODE_OFFSET, &mode_value, 1) != 0) {
        return -1;
    }
    printf("Debug: Mode value at 0x%03x = 0x%08x\n", DMEM_MODE_OFFSET, mode_value);

    // Read the recovered x-coordinate
    uint32_t x_r_result[P256_SCALAR_WORDS];
    if (otbn_read_dmem(DMEM_X_R_OFFSET, x_r_result, P256_SCALAR_WORDS) != 0) {
        return -1;
    }

    printf("OK status: 0x%08x\n", ok_status);

    printf("Recovered x_r (raw OTBN format): ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", x_r_result[i]);
    }
    printf("\n");

    // printf("Recovered x_r (big-endian display): ");
    // for (int i = P256_SCALAR_WORDS - 1; i >= 0; i--) {
    //     printf("%08x", x_r_result[i]);
    // }
    // printf("\n");

    // Use original R for comparison
    printf("Expected R (OTBN format): ");
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        printf("%08x ", test_signature_r_otbn[i]);
    }
    printf("\n");

    // printf("Expected R (big-endian display): ");
    // for (int i = P256_SCALAR_WORDS - 1; i >= 0; i--) {
    //     printf("%08x", test_signature_r_otbn[i]);
    // }
    // printf("\n");

    // Check if ok_status indicates success (should be hardened boolean for valid signature)
    // Expected: 0x739 = HARDENED_BOOL_TRUE_XOR_COUNTER (0x639) XOR 256 (loop counter)
    const uint32_t EXPECTED_OK_VALUE = 0x739;  // HARDENED_BOOL_TRUE_XOR_COUNTER XOR 256
    if (ok_status != EXPECTED_OK_VALUE) {
        printf("ERROR: OK status indicates verification FAILED\n");
        printf("       Expected: 0x%08x (HARDENED_BOOL_TRUE_XOR_COUNTER XOR 256)\n", EXPECTED_OK_VALUE);
        printf("       Actual:   0x%08x\n", ok_status);
        return -1;
    }
    printf("Verification basic input data checks PASSED (OK status = 0x%08x)\n", ok_status);

    // Check if recovered x_r matches the signature R component
    int r_match = 1;
    for (int i = 0; i < P256_SCALAR_WORDS; i++) {
        if (x_r_result[i] != test_signature_r_otbn[i]) {
            r_match = 0;
            break;
        }
    }

    if (!r_match) {
        printf("ERROR: Recovered x_r does not match signature R component\n");
        return -1;
    }

    printf("SUCCESS: Signature verification PASSED!\n");
    printf("  - OK status: VALID (0x%08x)\n", ok_status);
    printf("  - x_r matches R component\n");

    return 0;
}

/**
 * Main test function
 */
int main(void) {
    // Initialize outbound filter to allow testpass mailbox access
    sep_outbound_filter_init();

    printf("=== OTBN P256 ECDSA Signature Verification Test ===\n");
    printf("Using OpenTitan test vectors\n\n");

    int rc = 0;

    // Manually initialize OTBN DMEM with zeros
    // FIXME: This is a hack because a 32-bit transaction on the 64-bit bus is not correctly
    // mapped to a single 32-bit transaction by axi_lite_dw_converter.
    if (otbn_dmem_zero_init() != 0) {
        printf("FAILED: OTBN DMEM zero initialization failed\n");
        rc = -1;
        goto done;
    }

    // Load OTBN program
    if (otbn_load_program() != 0) {
        printf("FAILED: Could not load OTBN program\n");
        rc = -1;
        goto done;
    }

    // Setup test inputs
    if (setup_verification_inputs() != 0) {
        printf("FAILED: Could not setup verification inputs\n");
        rc = -1;
        goto done;
    }

    // Verify input data by reading back from DMEM
    if (verify_input_data() != 0) {
        printf("FAILED: Input data verification failed\n");
        rc = -1;
        goto done;
    }

    // Execute verification
    if (execute_verification() != 0) {
        printf("FAILED: OTBN execution failed\n");
        rc = -1;
        goto done;
    }

    // Check results
    if (check_verification_results() != 0) {
        printf("FAILED: Verification result check failed\n");
        rc = -1;
        goto done;
    }

    printf("\n=== Test PASSED ===\n");
    rc = 0;

done:
    if (rc == 0) {
        test_pass(0);
    } else {
        test_fail(1);
    }

    // Keep CPU alive after signaling completion.
    while (1) {
        __asm__("wfi");
    }
}