TEST = kmac_shake128_test
export TEST

EXT_C_FLAGS += -march=rv32imc -mabi=ilp32

EXT_INCS += -I$(OCH_ROOT)/meta/registers/c
EXT_INCS += -I$(OCH_ROOT)/fw/sep/tests/common

all: $(TEST).elf

include $(OCH_ROOT)/fw/sep/tests/common/common.mk


.PHONY: help
help:
	@echo "KMAC Test: $(TEST)"
	@echo "Targets: all, clean"

.PHONY: clean
clean:
	rm -f *.o *.elf *.hex *.dis *.sym *.su *.map
