# SPDX-License-Identifier: Apache-2.0
# Board defconfig already enables printk / UART0.  Keep this fragment empty
# of interrupt-driven UART so the poke app stays on the polling console.
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2048
