#include "AVBBus_basetest.h"

AVBBus_basetest::Register_Property_t reg_map[21] = {
{AVBBus_basetest::AVS_FSM_RESET_OFFSET, AVBBus_basetest::AVS_FSM_RESET_READ, AVBBus_basetest::AVS_FSM_RESET_WRITE, AVBBus_basetest::AVS_FSM_RESET_RESET, "AVS_FSM_RESET"}, 
{AVBBus_basetest::AVS_CTRL_OFFSET, AVBBus_basetest::AVS_CTRL_READ, AVBBus_basetest::AVS_CTRL_WRITE, AVBBus_basetest::AVS_CTRL_RESET, "AVS_CTRL"}, 
{AVBBus_basetest::AVS_CMD_OFFSET, AVBBus_basetest::AVS_CMD_READ, AVBBus_basetest::AVS_CMD_WRITE, AVBBus_basetest::AVS_CMD_RESET, "AVS_CMD"}, 
{AVBBus_basetest::AVS_READBACK_OFFSET, AVBBus_basetest::AVS_READBACK_READ, AVBBus_basetest::AVS_READBACK_WRITE, AVBBus_basetest::AVS_READBACK_RESET, "AVS_READBACK"}, 
{AVBBus_basetest::AVS_TARGET_ACKS_OFFSET, AVBBus_basetest::AVS_TARGET_ACKS_READ, AVBBus_basetest::AVS_TARGET_ACKS_WRITE, AVBBus_basetest::AVS_TARGET_ACKS_RESET, "AVS_TARGET_ACKS"}, 
{AVBBus_basetest::AVS_LATEST_TARGET_SUBFRAME_OFFSET, AVBBus_basetest::AVS_LATEST_TARGET_SUBFRAME_READ, AVBBus_basetest::AVS_LATEST_TARGET_SUBFRAME_WRITE, AVBBus_basetest::AVS_LATEST_TARGET_SUBFRAME_RESET, "AVS_LATEST_TARGET_SUBFRAME"}, 
{AVBBus_basetest::AVS_LATEST_TARGET_ACKS_OFFSET, AVBBus_basetest::AVS_LATEST_TARGET_ACKS_READ, AVBBus_basetest::AVS_LATEST_TARGET_ACKS_WRITE, AVBBus_basetest::AVS_LATEST_TARGET_ACKS_RESET, "AVS_LATEST_TARGET_ACKS"}, 
{AVBBus_basetest::AVS_NORMAL_STATUS_OFFSET, AVBBus_basetest::AVS_NORMAL_STATUS_READ, AVBBus_basetest::AVS_NORMAL_STATUS_WRITE, AVBBus_basetest::AVS_NORMAL_STATUS_RESET, "AVS_NORMAL_STATUS"}, 
{AVBBus_basetest::AVS_CONTROLLER_STATUS_OFFSET, AVBBus_basetest::AVS_CONTROLLER_STATUS_READ, AVBBus_basetest::AVS_CONTROLLER_STATUS_WRITE, AVBBus_basetest::AVS_CONTROLLER_STATUS_RESET, "AVS_CONTROLLER_STATUS"}, 
{AVBBus_basetest::AVS_TOTAL_RETRIES_OFFSET, AVBBus_basetest::AVS_TOTAL_RETRIES_READ, AVBBus_basetest::AVS_TOTAL_RETRIES_WRITE, AVBBus_basetest::AVS_TOTAL_RETRIES_RESET, "AVS_TOTAL_RETRIES"}, 
{AVBBus_basetest::AVS_FIFOS_STATUS_OFFSET, AVBBus_basetest::AVS_FIFOS_STATUS_READ, AVBBus_basetest::AVS_FIFOS_STATUS_WRITE, AVBBus_basetest::AVS_FIFOS_STATUS_RESET, "AVS_FIFOS_STATUS"}, 
{AVBBus_basetest::AVS_INTERRUPT_OFFSET, AVBBus_basetest::AVS_INTERRUPT_READ, AVBBus_basetest::AVS_INTERRUPT_WRITE, AVBBus_basetest::AVS_INTERRUPT_RESET, "AVS_INTERRUPT"}, 
{AVBBus_basetest::AVS_INTERRUPT_MASK_OFFSET, AVBBus_basetest::AVS_INTERRUPT_MASK_READ, AVBBus_basetest::AVS_INTERRUPT_MASK_WRITE, AVBBus_basetest::AVS_INTERRUPT_MASK_RESET, "AVS_INTERRUPT_MASK"}, 
{AVBBus_basetest::AVS_INTERRUPT_TEST_OFFSET, AVBBus_basetest::AVS_INTERRUPT_TEST_READ, AVBBus_basetest::AVS_INTERRUPT_TEST_WRITE, AVBBus_basetest::AVS_INTERRUPT_TEST_RESET, "AVS_INTERRUPT_TEST"}, 
{AVBBus_basetest::AVS_TARGET_ISSUED_INTERRUPT_IDS_OFFSET, AVBBus_basetest::AVS_TARGET_ISSUED_INTERRUPT_IDS_READ, AVBBus_basetest::AVS_TARGET_ISSUED_INTERRUPT_IDS_WRITE, AVBBus_basetest::AVS_TARGET_ISSUED_INTERRUPT_IDS_RESET, "AVS_TARGET_ISSUED_INTERRUPT_IDS"}, 
{AVBBus_basetest::AVS_TARGET_UNRESPONSIVE_BAD_FRAME_INT_IDS_OFFSET, AVBBus_basetest::AVS_TARGET_UNRESPONSIVE_BAD_FRAME_INT_IDS_READ, AVBBus_basetest::AVS_TARGET_UNRESPONSIVE_BAD_FRAME_INT_IDS_WRITE, AVBBus_basetest::AVS_TARGET_UNRESPONSIVE_BAD_FRAME_INT_IDS_RESET, "AVS_TARGET_UNRESPONSIVE_BAD_FRAME_INT_IDS"}, 
{AVBBus_basetest::AVS_TARGET_BAD_CRC_INT_IDS_OFFSET, AVBBus_basetest::AVS_TARGET_BAD_CRC_INT_IDS_READ, AVBBus_basetest::AVS_TARGET_BAD_CRC_INT_IDS_WRITE, AVBBus_basetest::AVS_TARGET_BAD_CRC_INT_IDS_RESET, "AVS_TARGET_BAD_CRC_INT_IDS"}, 
{AVBBus_basetest::AVS_RETRY_CFG_OFFSET, AVBBus_basetest::AVS_RETRY_CFG_READ, AVBBus_basetest::AVS_RETRY_CFG_WRITE, AVBBus_basetest::AVS_RETRY_CFG_RESET, "AVS_RETRY_CFG"}, 
{AVBBus_basetest::AVS_CLK_CFG_OFFSET, AVBBus_basetest::AVS_CLK_CFG_READ, AVBBus_basetest::AVS_CLK_CFG_WRITE, AVBBus_basetest::AVS_CLK_CFG_RESET, "AVS_CLK_CFG"}, 
{AVBBus_basetest::AVS_THROTTLE_CFG_OFFSET, AVBBus_basetest::AVS_THROTTLE_CFG_READ, AVBBus_basetest::AVS_THROTTLE_CFG_WRITE, AVBBus_basetest::AVS_THROTTLE_CFG_RESET, "AVS_THROTTLE_CFG"}, 
{AVBBus_basetest::AVS_CONFIG_OFFSET, AVBBus_basetest::AVS_CONFIG_READ, AVBBus_basetest::AVS_CONFIG_WRITE, AVBBus_basetest::AVS_CONFIG_RESET, "AVS_CONFIG"}};