// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package km_kpv_kpvlp_reg_pkg;

    localparam KM_KPV_KPVLP_REG_DATA_WIDTH = 32;
    localparam KM_KPV_KPVLP_REG_MIN_ADDR_WIDTH = 12;
    localparam KM_KPV_KPVLP_REG_SIZE = 'h884;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } km_kpv_kpvlp__kpvlp_key_entry_rf__external__in_t;

    typedef struct {
        logic [2:0] next;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__extend__in_t;

    typedef struct {
        logic [7:0] next;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__dest_valid__in_t;

    typedef struct {
        logic [3:0] next;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__last_dword__in_t;

    typedef struct {
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__extend__in_t extend;
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__dest_valid__in_t dest_valid;
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__last_dword__in_t last_dword;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__in_t;

    typedef struct {
        logic [31:0] next;
    } km_kpv_kpvlp__kpvlp_status_reg__unlock_sep__in_t;

    typedef struct {
        km_kpv_kpvlp__kpvlp_status_reg__unlock_sep__in_t unlock_sep;
    } km_kpv_kpvlp__kpvlp_status_reg__in_t;

    typedef struct {
        km_kpv_kpvlp__kpvlp_key_entry_rf__external__in_t KPVLP_KEY_ENTRY[32];
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__in_t KPVLP_CTRL[32];
        km_kpv_kpvlp__kpvlp_status_reg__in_t KPVLP_STATUS;
    } km_kpv_kpvlp__in_t;

    typedef struct {
        logic req;
        logic [5:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } km_kpv_kpvlp__kpvlp_key_entry_rf__external__out_t;

    typedef struct {
        logic [2:0] value;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__extend__out_t;

    typedef struct {
        logic [7:0] value;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__dest_valid__out_t;

    typedef struct {
        logic [3:0] value;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__last_dword__out_t;

    typedef struct {
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__extend__out_t extend;
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__dest_valid__out_t dest_valid;
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__last_dword__out_t last_dword;
    } km_kpv_kpvlp__kpvlp_ctrl_writable_reg__out_t;

    typedef struct {
        km_kpv_kpvlp__kpvlp_key_entry_rf__external__out_t KPVLP_KEY_ENTRY[32];
        km_kpv_kpvlp__kpvlp_ctrl_writable_reg__out_t KPVLP_CTRL[32];
    } km_kpv_kpvlp__out_t;
endpackage
