// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#include "efuse_basetest.h"

// Full register map for the combined sep_efuse model.
// Shadow (0x000-0x3FC), INTERFACE_CTRL (0x400-0x418), EFUSE_MMR (0x500-0x56C).
efuse_basetest::Register_Property_t reg_map[] = {
    // Shadow registers
    {sep_efuse::LOCKS_LO_OFFSET,              efuse_basetest::LOCKS_LO_READ,              efuse_basetest::LOCKS_LO_WRITE,              efuse_basetest::LOCKS_LO_RESET,              "LOCKS_LO"},
    {sep_efuse::LOCKS_HI_OFFSET,              efuse_basetest::LOCKS_HI_READ,              efuse_basetest::LOCKS_HI_WRITE,              efuse_basetest::LOCKS_HI_RESET,              "LOCKS_HI"},
    {sep_efuse::LOCKS_SPARE_OFFSET,           efuse_basetest::LOCKS_LO_READ,               efuse_basetest::LOCKS_LO_WRITE,               efuse_basetest::LOCKS_LO_RESET,               "LOCKS_SPARE"},
    {sep_efuse::LC_STATE_OFFSET,              efuse_basetest::LC_STATE_READ,              efuse_basetest::LC_STATE_WRITE,              efuse_basetest::LC_STATE_RESET,              "LC_STATE"},
    {sep_efuse::SBOOT_DIS_OFFSET,             efuse_basetest::SBOOT_DIS_READ,             efuse_basetest::SBOOT_DIS_WRITE,             efuse_basetest::SBOOT_DIS_RESET,             "SBOOT_DIS"},
    {sep_efuse::TRANSIENT_RMA_EN_OFFSET,      efuse_basetest::TRANSIENT_RMA_EN_READ,      efuse_basetest::TRANSIENT_RMA_EN_WRITE,      efuse_basetest::TRANSIENT_RMA_EN_RESET,      "TRANSIENT_RMA_EN"},
    {sep_efuse::SIP_DIS_LO_OFFSET,            efuse_basetest::SIP_DIS_LO_READ,            efuse_basetest::SIP_DIS_LO_WRITE,            efuse_basetest::SIP_DIS_LO_RESET,            "SIP_DIS_LO"},
    {sep_efuse::SIP_DIS_HI_OFFSET,            efuse_basetest::SIP_DIS_HI_READ,            efuse_basetest::SIP_DIS_HI_WRITE,            efuse_basetest::SIP_DIS_HI_RESET,            "SIP_DIS_HI"},
    {sep_efuse::SYS_DIS_LO_OFFSET,            efuse_basetest::SYS_DIS_LO_READ,            efuse_basetest::SYS_DIS_LO_WRITE,            efuse_basetest::SYS_DIS_LO_RESET,            "SYS_DIS_LO"},
    {sep_efuse::SYS_DIS_HI_OFFSET,            efuse_basetest::SYS_DIS_HI_READ,            efuse_basetest::SYS_DIS_HI_WRITE,            efuse_basetest::SYS_DIS_HI_RESET,            "SYS_DIS_HI"},
    {sep_efuse::RMA_SIP_TOKEN_OFFSET,         efuse_basetest::RMA_SIP_TOKEN_READ,         efuse_basetest::RMA_SIP_TOKEN_WRITE,         efuse_basetest::RMA_SIP_TOKEN_RESET,         "RMA_SIP_TOKEN"},
    {sep_efuse::RMA_CHIPLET_TOKEN_OFFSET,     efuse_basetest::RMA_CHIPLET_TOKEN_READ,     efuse_basetest::RMA_CHIPLET_TOKEN_WRITE,     efuse_basetest::RMA_CHIPLET_TOKEN_RESET,     "RMA_CHIPLET_TOKEN"},
    {sep_efuse::CLASS_KEY_OFFSET,             efuse_basetest::CLASS_KEY_READ,             efuse_basetest::CLASS_KEY_WRITE,             efuse_basetest::CLASS_KEY_RESET,             "CLASS_KEY"},
    {sep_efuse::CHIPLET_PUBK_REVOKE_OFFSET,   efuse_basetest::CHIPLET_PUBK_REVOKE_READ,   efuse_basetest::CHIPLET_PUBK_REVOKE_WRITE,   efuse_basetest::CHIPLET_PUBK_REVOKE_RESET,   "CHIPLET_PUBK_REVOKE"},
    {sep_efuse::BL1_VERSION_OFFSET,           efuse_basetest::BL1_VERSION_READ,           efuse_basetest::BL1_VERSION_WRITE,           efuse_basetest::BL1_VERSION_RESET,           "BL1_VERSION"},
    {sep_efuse::BL2_VERSION_OFFSET,           efuse_basetest::BL2_VERSION_READ,           efuse_basetest::BL2_VERSION_WRITE,           efuse_basetest::BL2_VERSION_RESET,           "BL2_VERSION"},
    {sep_efuse::CHIPLET_UID_OFFSET,           efuse_basetest::CHIPLET_UID_READ,           efuse_basetest::CHIPLET_UID_WRITE,           efuse_basetest::CHIPLET_UID_RESET,           "CHIPLET_UID"},
    {sep_efuse::SIP_PUBK_HASH0_OFFSET,              efuse_basetest::SIP_PUBK_HASH0_READ,              efuse_basetest::SIP_PUBK_HASH0_WRITE,              efuse_basetest::SIP_PUBK_HASH0_RESET,              "SIP_PUBK_HASH0"},
    {sep_efuse::SIP_UID_OFFSET,               efuse_basetest::SIP_UID_READ,               efuse_basetest::SIP_UID_WRITE,               efuse_basetest::SIP_UID_RESET,               "SIP_UID"},
    {sep_efuse::SYS_PUBK_HASH_OFFSET,              efuse_basetest::SYS_PUBK_HASH_READ,              efuse_basetest::SYS_PUBK_HASH_WRITE,              efuse_basetest::SYS_PUBK_HASH_RESET,              "SYS_PUBK_HASH"},
    {sep_efuse::SYS_UID_OFFSET,               efuse_basetest::SYS_UID_READ,               efuse_basetest::SYS_UID_WRITE,               efuse_basetest::SYS_UID_RESET,               "SYS_UID"},
    {sep_efuse::STATUS_RPT_OFFSET,            efuse_basetest::STATUS_RPT_READ,            efuse_basetest::STATUS_RPT_WRITE,            efuse_basetest::STATUS_RPT_RESET,            "STATUS_RPT"},
    {sep_efuse::SEP_ROM_CTRL_OFFSET,          efuse_basetest::SEP_ROM_CTRL_READ,          efuse_basetest::SEP_ROM_CTRL_WRITE,          efuse_basetest::SEP_ROM_CTRL_RESET,          "SEP_ROM_CTRL"},
    {sep_efuse::SYSCLK_FREQ_MHZ_OFFSET, efuse_basetest::SYSCLK_FREQ_MHZ_READ, efuse_basetest::SYSCLK_FREQ_MHZ_WRITE, efuse_basetest::SYSCLK_FREQ_MHZ_RESET, "SYSCLK_FREQ_MHZ"},
    {sep_efuse::CHIPLET_PUBK_HASH0_OFFSET, efuse_basetest::CHIPLET_PUBK_HASH0_READ, efuse_basetest::CHIPLET_PUBK_HASH0_WRITE, efuse_basetest::CHIPLET_PUBK_HASH0_RESET, "CHIPLET_PUBK_HASH0"},
    {sep_efuse::CHIPLET_PUBK_HASH1_OFFSET, efuse_basetest::CHIPLET_PUBK_HASH1_READ, efuse_basetest::CHIPLET_PUBK_HASH1_WRITE, efuse_basetest::CHIPLET_PUBK_HASH1_RESET, "CHIPLET_PUBK_HASH1"},
    {sep_efuse::REQUIRED_SIGNERS_OFFSET, efuse_basetest::REQUIRED_SIGNERS_READ, efuse_basetest::REQUIRED_SIGNERS_WRITE, efuse_basetest::REQUIRED_SIGNERS_RESET, "REQUIRED_SIGNERS"},
    {sep_efuse::REQUIRED_ALGS_OFFSET, efuse_basetest::REQUIRED_ALGS_READ, efuse_basetest::REQUIRED_ALGS_WRITE, efuse_basetest::REQUIRED_ALGS_RESET, "REQUIRED_ALGS"},
    {sep_efuse::CHIPLET_PUBK_PQC_HASH0_OFFSET, efuse_basetest::CHIPLET_PUBK_PQC_HASH0_READ, efuse_basetest::CHIPLET_PUBK_PQC_HASH0_WRITE, efuse_basetest::CHIPLET_PUBK_PQC_HASH0_RESET, "CHIPLET_PUBK_PQC_HASH0"},
    {sep_efuse::CHIPLET_PUBK_PQC_HASH1_OFFSET, efuse_basetest::CHIPLET_PUBK_PQC_HASH1_READ, efuse_basetest::CHIPLET_PUBK_PQC_HASH1_WRITE, efuse_basetest::CHIPLET_PUBK_PQC_HASH1_RESET, "CHIPLET_PUBK_PQC_HASH1"},
    {sep_efuse::SIP_PUBK_PQC_HASH0_OFFSET, efuse_basetest::SIP_PUBK_PQC_HASH0_READ, efuse_basetest::SIP_PUBK_PQC_HASH0_WRITE, efuse_basetest::SIP_PUBK_PQC_HASH0_RESET, "SIP_PUBK_PQC_HASH0"},
    {sep_efuse::SYS_PUBK_PQC_HASH_OFFSET, efuse_basetest::SYS_PUBK_PQC_HASH_READ, efuse_basetest::SYS_PUBK_PQC_HASH_WRITE, efuse_basetest::SYS_PUBK_PQC_HASH_RESET, "SYS_PUBK_PQC_HASH"},
    {sep_efuse::SIP_PUBK_HASH1_OFFSET, efuse_basetest::SIP_PUBK_HASH1_READ, efuse_basetest::SIP_PUBK_HASH1_WRITE, efuse_basetest::SIP_PUBK_HASH1_RESET, "SIP_PUBK_HASH1"},
    {sep_efuse::SIP_PUBK_PQC_HASH1_OFFSET, efuse_basetest::SIP_PUBK_PQC_HASH1_READ, efuse_basetest::SIP_PUBK_PQC_HASH1_WRITE, efuse_basetest::SIP_PUBK_PQC_HASH1_RESET, "SIP_PUBK_PQC_HASH1"},
    {sep_efuse::SEP_CHIPLET_ID_OFFSET, efuse_basetest::SEP_CHIPLET_ID_READ, efuse_basetest::SEP_CHIPLET_ID_WRITE, efuse_basetest::SEP_CHIPLET_ID_RESET, "SEP_CHIPLET_ID"},
    {sep_efuse::SEP_SIP_ID_OFFSET, efuse_basetest::SEP_SIP_ID_READ, efuse_basetest::SEP_SIP_ID_WRITE, efuse_basetest::SEP_SIP_ID_RESET, "SEP_SIP_ID"},
    {sep_efuse::SEP_SYS_ID_OFFSET, efuse_basetest::SEP_SYS_ID_READ, efuse_basetest::SEP_SYS_ID_WRITE, efuse_basetest::SEP_SYS_ID_RESET, "SEP_SYS_ID"},
    {sep_efuse::SPARE0_OFFSET, efuse_basetest::SPARE0_READ, efuse_basetest::SPARE0_WRITE, efuse_basetest::SPARE0_RESET, "SPARE0"},
    {sep_efuse::SPARE1_OFFSET, efuse_basetest::SPARE1_READ, efuse_basetest::SPARE1_WRITE, efuse_basetest::SPARE1_RESET, "SPARE1"},
    {sep_efuse::SPARE2_OFFSET, efuse_basetest::SPARE2_READ, efuse_basetest::SPARE2_WRITE, efuse_basetest::SPARE2_RESET, "SPARE2"},
    {sep_efuse::SPARE3_OFFSET, efuse_basetest::SPARE3_READ, efuse_basetest::SPARE3_WRITE, efuse_basetest::SPARE3_RESET, "SPARE3"},
    {sep_efuse::SPARE4_OFFSET, efuse_basetest::SPARE4_READ, efuse_basetest::SPARE4_WRITE, efuse_basetest::SPARE4_RESET, "SPARE4"},
    {sep_efuse::SPARE5_OFFSET, efuse_basetest::SPARE5_READ, efuse_basetest::SPARE5_WRITE, efuse_basetest::SPARE5_RESET, "SPARE5"},
    {sep_efuse::SPARE6_OFFSET, efuse_basetest::SPARE6_READ, efuse_basetest::SPARE6_WRITE, efuse_basetest::SPARE6_RESET, "SPARE6"},
    {sep_efuse::SPARE7_OFFSET, efuse_basetest::SPARE7_READ, efuse_basetest::SPARE7_WRITE, efuse_basetest::SPARE7_RESET, "SPARE7"},
    {sep_efuse::SPARE8_OFFSET, efuse_basetest::SPARE7_READ, efuse_basetest::SPARE7_WRITE, efuse_basetest::SPARE7_RESET, "SPARE8"},
    // EFUSE_INTERFACE_CTRL
    {sep_efuse::EFUSE_INTERFACE_CTRL_STATUS_OFFSET,       efuse_basetest::EFUSE_INTF_STATUS_READ,       efuse_basetest::EFUSE_INTF_STATUS_WRITE,       efuse_basetest::EFUSE_INTF_STATUS_RESET,       "EFUSE_INTF_STATUS"},
    {sep_efuse::EFUSE_PROGRAM_CTRL_OFFSET,        efuse_basetest::EFUSE_PROGRAM_CTRL_READ,        efuse_basetest::EFUSE_PROGRAM_CTRL_WRITE,        efuse_basetest::EFUSE_PROGRAM_CTRL_RESET,        "EFUSE_PROGRAM_CTRL"},
    {sep_efuse::EFUSE_READ_CTRL_OFFSET,         efuse_basetest::EFUSE_READ_CTRL_READ,         efuse_basetest::EFUSE_READ_CTRL_WRITE,         efuse_basetest::EFUSE_READ_CTRL_RESET,         "EFUSE_READ_CTRL"},
    {sep_efuse::EFUSE_PROGRAM_INTERFACE_RD_DATA_OFFSET, efuse_basetest::EFUSE_PROG_INTF_RD_DATA_READ, efuse_basetest::EFUSE_PROG_INTF_RD_DATA_WRITE, efuse_basetest::EFUSE_PROG_INTF_RD_DATA_RESET, "EFUSE_PROG_INTF_RD_DATA"},
    {sep_efuse::EFUSE_READ_INTERFACE_RD_DATA_OFFSET, efuse_basetest::EFUSE_READ_INTF_RD_DATA_READ, efuse_basetest::EFUSE_READ_INTF_RD_DATA_WRITE, efuse_basetest::EFUSE_READ_INTF_RD_DATA_RESET, "EFUSE_READ_INTF_RD_DATA"},
    {sep_efuse::EFUSE_READ_REQ_TIMEOUT_OFFSET,  efuse_basetest::EFUSE_READ_REQ_TIMEOUT_READ,  efuse_basetest::EFUSE_READ_REQ_TIMEOUT_WRITE,  efuse_basetest::EFUSE_READ_REQ_TIMEOUT_RESET,  "EFUSE_READ_REQ_TIMEOUT"},
    {sep_efuse::EFUSE_PROGRAM_REQ_TIMEOUT_OFFSET,  efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_READ,  efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_WRITE,  efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_RESET,  "EFUSE_PROG_REQ_TIMEOUT"},
    // EFUSE_MMR
    {sep_efuse::RMA_SIP_TOKEN_I_OFFSET,         efuse_basetest::RMA_SIP_TOKEN_I_READ,         efuse_basetest::RMA_SIP_TOKEN_I_WRITE,         efuse_basetest::RMA_SIP_TOKEN_I_RESET,         "RMA_SIP_TOKEN_I"},
    {sep_efuse::RMA_CHIPLET_TOKEN_I_OFFSET,     efuse_basetest::RMA_CHIPLET_TOKEN_I_READ,     efuse_basetest::RMA_CHIPLET_TOKEN_I_WRITE,     efuse_basetest::RMA_CHIPLET_TOKEN_I_RESET,     "RMA_CHIPLET_TOKEN_I"},
    {sep_efuse::SEC_DISABLE_TOKEN_I_OFFSET,     efuse_basetest::SEC_DISABLE_TOKEN_I_READ,     efuse_basetest::SEC_DISABLE_TOKEN_I_WRITE,     efuse_basetest::SEC_DISABLE_TOKEN_I_RESET,     "SEC_DISABLE_TOKEN_I"},
    {sep_efuse::TOKEN_EOP_OFFSET,               efuse_basetest::TOKEN_EOP_READ,               efuse_basetest::TOKEN_EOP_WRITE,               efuse_basetest::TOKEN_EOP_RESET,               "TOKEN_EOP"},
    {sep_efuse::RMA_SIP_TOKEN_MATCH_OFFSET,     efuse_basetest::RMA_SIP_TOKEN_MATCH_READ,     efuse_basetest::RMA_SIP_TOKEN_MATCH_WRITE,     efuse_basetest::RMA_SIP_TOKEN_MATCH_RESET,     "RMA_SIP_TOKEN_MATCH"},
    {sep_efuse::RMA_CHIPLET_TOKEN_MATCH_OFFSET, efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_READ, efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_WRITE, efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_RESET, "RMA_CHIPLET_TOKEN_MATCH"},
    {sep_efuse::SEC_DISABLE_TOKEN_MATCH_OFFSET, efuse_basetest::SEC_DISABLE_TOKEN_MATCH_READ, efuse_basetest::SEC_DISABLE_TOKEN_MATCH_WRITE, efuse_basetest::SEC_DISABLE_TOKEN_MATCH_RESET, "SEC_DISABLE_TOKEN_MATCH"},
};
