// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package filter_ctrl_reg_pkg;

    localparam FILTER_CTRL_REG_DATA_WIDTH = 64;
    localparam FILTER_CTRL_REG_MIN_ADDR_WIDTH = 5;
    localparam FILTER_CTRL_REG_SIZE = 'h18;

    typedef struct {
        logic [2:0] next;
    } filter_ctrl__FILTER_CONFIG__data_bus_width__in_t;

    typedef struct {
        filter_ctrl__FILTER_CONFIG__data_bus_width__in_t data_bus_width;
    } filter_ctrl__FILTER_CONFIG__in_t;

    typedef struct {
        logic [55:0] next;
    } filter_ctrl__START_ADDR__start_addr__in_t;

    typedef struct {
        filter_ctrl__START_ADDR__start_addr__in_t start_addr;
    } filter_ctrl__START_ADDR__in_t;

    typedef struct {
        logic [55:0] next;
    } filter_ctrl__END_ADDR__end_addr__in_t;

    typedef struct {
        filter_ctrl__END_ADDR__end_addr__in_t end_addr;
    } filter_ctrl__END_ADDR__in_t;

    typedef struct {
        filter_ctrl__FILTER_CONFIG__in_t FILTER_CONFIG;
        filter_ctrl__START_ADDR__in_t START_ADDR;
        filter_ctrl__END_ADDR__in_t END_ADDR;
    } filter_ctrl__in_t;

    typedef struct {
        logic value;
    } filter_ctrl__FILTER_CONFIG__read_allowed__out_t;

    typedef struct {
        logic value;
    } filter_ctrl__FILTER_CONFIG__write_allowed__out_t;

    typedef struct {
        logic value;
    } filter_ctrl__FILTER_CONFIG__entry_enabled__out_t;

    typedef struct {
        logic value;
    } filter_ctrl__FILTER_CONFIG__allow_ns__out_t;

    typedef struct {
        logic [3:0] value;
    } filter_ctrl__FILTER_CONFIG__src_id__out_t;

    typedef struct {
        logic [3:0] value;
    } filter_ctrl__FILTER_CONFIG__group_id__out_t;

    typedef struct {
        logic value;
    } filter_ctrl__FILTER_CONFIG__allow_burst__out_t;

    typedef struct {
        logic value;
    } filter_ctrl__FILTER_CONFIG__locked__out_t;

    typedef struct {
        filter_ctrl__FILTER_CONFIG__read_allowed__out_t read_allowed;
        filter_ctrl__FILTER_CONFIG__write_allowed__out_t write_allowed;
        filter_ctrl__FILTER_CONFIG__entry_enabled__out_t entry_enabled;
        filter_ctrl__FILTER_CONFIG__allow_ns__out_t allow_ns;
        filter_ctrl__FILTER_CONFIG__src_id__out_t src_id;
        filter_ctrl__FILTER_CONFIG__group_id__out_t group_id;
        filter_ctrl__FILTER_CONFIG__allow_burst__out_t allow_burst;
        filter_ctrl__FILTER_CONFIG__locked__out_t locked;
    } filter_ctrl__FILTER_CONFIG__out_t;

    typedef struct {
        logic [55:0] value;
    } filter_ctrl__START_ADDR__start_addr__out_t;

    typedef struct {
        filter_ctrl__START_ADDR__start_addr__out_t start_addr;
    } filter_ctrl__START_ADDR__out_t;

    typedef struct {
        logic [55:0] value;
    } filter_ctrl__END_ADDR__end_addr__out_t;

    typedef struct {
        filter_ctrl__END_ADDR__end_addr__out_t end_addr;
    } filter_ctrl__END_ADDR__out_t;

    typedef struct {
        filter_ctrl__FILTER_CONFIG__out_t FILTER_CONFIG;
        filter_ctrl__START_ADDR__out_t START_ADDR;
        filter_ctrl__END_ADDR__out_t END_ADDR;
    } filter_ctrl__out_t;
endpackage
