#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
# =============================================================================
# setup_dependencies.sh — build the one dependency that cannot be copied.
#
# Everything else fw/sep/tests needs from the tt-oca-hw tree is vendored next to
# this script (meta/, dv/, vendor/).  The C library is not: the tests use
# picolibc's tinystdio (init_stdout.c installs a FDEV_SETUP_STREAM stdout) and
# link with --specs=picolibc.specs, and no RISC-V toolchain ships it.  Upstream
# gets it from the VeeR EL2 repo (bender checkout + tools/picolibc.mk); here it
# is built straight from the picolibc release so no VeeR checkout is needed.
#
# Produces the layout fw/sep/tests/common/common.mk expects under RV_ROOT:
#
#   el2/third_party/picolibc/install/picolibc.specs
#   el2/third_party/picolibc/install/picolibc/<triple>/include/...
#   el2/third_party/picolibc/install/picolibc/<triple>/lib/rv32imac/ilp32/...
#   el2/snapshots/sep/defines.h        (stub; see below)
#   el2/tools/picolibc.mk              (shim invoked by common.mk)
#
# Usage:
#   ./setup_dependencies.sh            # build if missing
#   ./setup_dependencies.sh --force    # rebuild from scratch
#
# Requirements: git, python3 (for meson/ninja in a throwaway venv) and a RISC-V
# bare-metal toolchain.  Nothing is installed outside this directory.
# =============================================================================

set -euo pipefail

DEPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${DEPS_DIR}/build"
EL2_DIR="${DEPS_DIR}/el2"
INSTALL_DIR="${EL2_DIR}/third_party/picolibc/install"

PICOLIBC_VERSION="${PICOLIBC_VERSION:-1.8.10}"
PICOLIBC_SRC="${BUILD_DIR}/picolibc-src"
PICOLIBC_BUILD="${BUILD_DIR}/picolibc-build"
TOOLENV="${BUILD_DIR}/.toolenv"

# Multilib variants to build.  Older toolchains ship rv32imac/ilp32 (what
# common.mk used to link with).  xPack GCC 15+ dropped that directory and
# ships rv32imc/ilp32 instead.  Leave MULTILIBS unset to pick from the
# compiler; set it only to force a list.
MULTILIBS="${MULTILIBS:-}"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

log() { echo "[setup_dependencies] $*"; }
die() { echo "[setup_dependencies] ERROR: $*" >&2; exit 1; }

# -----------------------------------------------------------------------------
# Toolchain
# -----------------------------------------------------------------------------
detect_prefix() {
    local p
    if [ -n "${GCC_PREFIX:-}" ] && command -v "${GCC_PREFIX}-gcc" >/dev/null 2>&1; then
        echo "${GCC_PREFIX}"
        return 0
    fi
    for p in riscv64-unknown-elf riscv64-elf riscv-none-elf riscv64-linux-gnu riscv-none-embed; do
        if command -v "${p}-gcc" >/dev/null 2>&1; then
            echo "${p}"
            return 0
        fi
    done
    return 1
}

TRIPLE="$(detect_prefix)" || die "no RISC-V toolchain in PATH (brew install riscv64-elf-gcc / apt install gcc-riscv64-unknown-elf)"
log "toolchain: ${TRIPLE}-gcc"

# Prefer the historical VeeR set; skip any directory this GCC does not ship
# (xPack 15: no rv32imac/ilp32 — "Unavailable multilib: rv32imac/ilp32").
if [ -z "${MULTILIBS}" ]; then
    available="$("${TRIPLE}-gcc" -print-multi-lib | cut -d';' -f1)"
    chosen=""
    for lib in rv32imac/ilp32 rv32imc/ilp32 rv32im/ilp32; do
        if printf '%s\n' "${available}" | grep -qx "${lib}"; then
            chosen="${chosen:+${chosen},}${lib}"
        fi
    done
    [ -n "${chosen}" ] || die "${TRIPLE}-gcc has no rv32im* / ilp32 multilib"
    MULTILIBS="${chosen}"
fi
log "multilibs: ${MULTILIBS}"

if [ "${FORCE}" -eq 1 ]; then
    rm -rf "${PICOLIBC_BUILD}" "${INSTALL_DIR}"
fi

# -----------------------------------------------------------------------------
# Stubs that stand in for the VeeR EL2 checkout
#
# Only crt0_bl1.s (the BL1 flow, not used by the VP tests) actually includes
# defines.h; common.mk just lists it as a prerequisite of every object, so a
# placeholder is enough to keep the VP builds honest.
# -----------------------------------------------------------------------------
write_el2_stubs() {
    mkdir -p "${EL2_DIR}/snapshots/sep" "${EL2_DIR}/tools"

    if [ ! -f "${EL2_DIR}/snapshots/sep/defines.h" ]; then
        cat > "${EL2_DIR}/snapshots/sep/defines.h" <<'EOF'
/*
 * Placeholder for the VeeR EL2 snapshot header.
 *
 * Upstream this file is generated by configs/veer.config in the Cores-VeeR-EL2
 * repo and describes the ICCM/DCCM/PIC geometry of the core.  The SEP VP tests
 * never read it: common.mk only lists it as a prerequisite, and the single
 * consumer (common/crt0_bl1.s) belongs to the BL1 flow, which the VP does not
 * run.  Generate the real snapshot and drop it here if you need that flow.
 */
#ifndef SEP_EL2_SNAPSHOT_DEFINES_H
#define SEP_EL2_SNAPSHOT_DEFINES_H
#endif
EOF
        log "wrote snapshot stub: ${EL2_DIR}/snapshots/sep/defines.h"
    fi

    # common.mk runs `$(MAKE) -f $(RV_ROOT)/tools/picolibc.mk all` as a
    # prerequisite of every object file.  Upstream that builds picolibc; here it
    # only has to confirm the prebuilt install is present.
    cat > "${EL2_DIR}/tools/picolibc.mk" <<'EOF'
# Stand-in for the VeeR EL2 picolibc makefile.
#
# common.mk calls this on every build.  picolibc is built once by
# dependencies/setup_dependencies.sh, so all this needs to do is fail loudly if
# that has not happened yet.
PICOLIBC_INSTALL := $(dir $(lastword $(MAKEFILE_LIST)))../third_party/picolibc/install
SETUP_SCRIPT     := $(dir $(lastword $(MAKEFILE_LIST)))../../setup_dependencies.sh

.PHONY: all
all:
	@test -f "$(PICOLIBC_INSTALL)/picolibc.specs" || { \
	  echo "picolibc is not built yet. Run: $(SETUP_SCRIPT)" >&2; \
	  exit 1; \
	}
EOF
    log "wrote picolibc.mk shim: ${EL2_DIR}/tools/picolibc.mk"
}

# -----------------------------------------------------------------------------
# meson + ninja, in a venv so nothing is installed system-wide
# -----------------------------------------------------------------------------
ensure_venv() {
    # A venv records its own location in every script shebang, so one that came
    # from a differently named directory is dead weight: pip fails with "bad
    # interpreter".  bin/python3 is only a symlink and keeps working, so probe
    # pip instead — that is what breaks.
    if [ -e "${TOOLENV}" ] && ! "${TOOLENV}/bin/pip" --version >/dev/null 2>&1; then
        log "venv in ${TOOLENV} is stale (checkout moved?); recreating"
        rm -rf "${TOOLENV}"
    fi

    if [ ! -x "${TOOLENV}/bin/python3" ]; then
        log "creating build-tool venv in ${TOOLENV}"
        command -v python3 >/dev/null 2>&1 || die "python3 is required to build the dependencies"
        mkdir -p "${BUILD_DIR}"
        python3 -m venv "${TOOLENV}"
        "${TOOLENV}/bin/pip" install --quiet --upgrade pip
    fi
}

# meson/ninja build picolibc.  The otbn_* tests additionally run two python
# tools: the vendored OpenTitan assembler (util/otbn_as.py, needs PyYAML) and
# generate_otbn_c.py, which reads the resulting ELF with pyelftools.
ensure_build_tools() {
    ensure_venv
    local want=""
    command -v meson >/dev/null 2>&1 || want="meson"
    command -v ninja >/dev/null 2>&1 || want="${want} ninja"
    "${TOOLENV}/bin/python3" -c 'import yaml' 2>/dev/null || want="${want} pyyaml"
    "${TOOLENV}/bin/python3" -c 'import elftools' 2>/dev/null || want="${want} pyelftools"
    if [ -n "${want# }" ]; then
        log "installing into venv:${want}"
        # shellcheck disable=SC2086
        "${TOOLENV}/bin/pip" install --quiet ${want}
    fi
    export PATH="${TOOLENV}/bin:${PATH}"
    log "using meson $(meson --version) / ninja $(ninja --version)"
}

# -----------------------------------------------------------------------------
# picolibc
# -----------------------------------------------------------------------------
fetch_picolibc() {
    if [ -d "${PICOLIBC_SRC}/.git" ]; then
        log "picolibc source already present (${PICOLIBC_SRC})"
        return 0
    fi
    mkdir -p "${BUILD_DIR}"
    log "cloning picolibc ${PICOLIBC_VERSION}"
    git clone --depth 1 --branch "${PICOLIBC_VERSION}" \
        https://github.com/picolibc/picolibc.git "${PICOLIBC_SRC}"
}

write_cross_file() {
    local cross="${BUILD_DIR}/cross-${TRIPLE}.txt"
    cat > "${cross}" <<EOF
# Generated by setup_dependencies.sh for ${TRIPLE}.
[binaries]
c = ['${TRIPLE}-gcc', '-nostdlib']
cpp = ['${TRIPLE}-g++', '-nostdlib']
ar = '${TRIPLE}-ar'
as = '${TRIPLE}-as'
strip = '${TRIPLE}-strip'
nm = '${TRIPLE}-nm'

[host_machine]
system = 'unknown'
cpu_family = 'riscv64'
cpu = 'riscv'
endian = 'little'

[properties]
c_args = [ '-msave-restore' ]
skip_sanity_check = true
default_flash_addr = '0x80000000'
default_flash_size = '0x00400000'
default_ram_addr   = '0x80400000'
default_ram_size   = '0x00200000'
EOF
    echo "${cross}"
}

build_picolibc() {
    if [ -f "${INSTALL_DIR}/picolibc.specs" ] && [ "${FORCE}" -eq 0 ]; then
        log "picolibc already installed (${INSTALL_DIR}); use --force to rebuild"
        return 0
    fi

    fetch_picolibc

    local cross multilib_arg
    cross="$(write_cross_file)"
    multilib_arg="$(echo "${MULTILIBS}" | tr ',' '\n' | sed "s/.*/'&'/" | paste -sd, -)"

    log "configuring picolibc (multilibs: ${MULTILIBS})"
    rm -rf "${PICOLIBC_BUILD}"
    # The -D options below mirror the upstream recipe these tests were built
    # against (Cores-VeeR-EL2/upstream/tools/picolibc.mk); the firmware assumes
    # that configuration rather than picolibc's defaults.
    #
    # thread-local-storage is the load-bearing one: it defaults to 'picolibc',
    # which puts _rand_next (and friends) in .tdata addressed off tp. common/crt0.s
    # never initialises tp, so the first such access stores to address 0 and takes
    # a bus error. Turning TLS off makes them ordinary .data symbols.
    #
    # io-long-long defaults to false, which drops the %ll conversions several
    # tests print 64-bit values with.
    meson setup "${PICOLIBC_BUILD}" "${PICOLIBC_SRC}" \
        --cross-file "${cross}" \
        --prefix "${INSTALL_DIR}" \
        -Dincludedir="picolibc/${TRIPLE}/include" \
        -Dlibdir="picolibc/${TRIPLE}/lib" \
        -Dspecsdir="${INSTALL_DIR}" \
        -Dmultilib-list="[${multilib_arg}]" \
        -Dthread-local-storage=false \
        -Dio-long-long=true \
        -Dformat-default=integer \
        -Dpicocrt=false \
        -Datomic-ungetc=false \
        -Dtests=false

    log "building picolibc"
    meson compile -C "${PICOLIBC_BUILD}"
    meson install -C "${PICOLIBC_BUILD}"
}

# meson bakes the install path into picolibc.specs as absolute -isystem and -L
# options, so renaming or moving this checkout breaks the link step with a
# confusing "cannot find -lc".  Point the specs back at wherever the install
# actually is; cheap enough to redo on every run.
relocate_specs() {
    local specs="${INSTALL_DIR}/picolibc.specs" tmp
    [ -f "${specs}" ] || return 0

    tmp="${specs}.new"
    sed -E "s#/[^ }:;]*/third_party/picolibc/install#${INSTALL_DIR}#g" \
        "${specs}" > "${tmp}"

    if cmp -s "${tmp}" "${specs}"; then
        rm -f "${tmp}"
    else
        mv "${tmp}" "${specs}"
        log "relocated picolibc.specs to ${INSTALL_DIR}"
    fi
}

# 17 tests link with --oslib=dummyhost, which picolibc.specs turns into
# -ldummyhost.  Upstream's picolibc build ships that library; the released
# picolibc does not, and its libnosys provides the same host-call stubs, so
# alias one onto the other rather than patching 17 Makefiles.
add_dummyhost_alias() {
    local lib
    for lib in $(find "${INSTALL_DIR}" -name libnosys.a 2>/dev/null); do
        cp -f "${lib}" "$(dirname "${lib}")/libdummyhost.a"
    done
    log "aliased libdummyhost.a -> libnosys.a"
}

# The include/lib directories are named after the toolchain prefix, which
# differs per host (riscv64-elf on Homebrew, riscv64-unknown-elf elsewhere).
# Alias the other spellings so one install serves whichever GCC_PREFIX is used.
add_triple_aliases() {
    local base="${INSTALL_DIR}/picolibc" alias
    for alias in riscv64-unknown-elf riscv64-elf riscv-none-elf; do
        [ "${alias}" = "${TRIPLE}" ] && continue
        [ -e "${base}/${alias}" ] && continue
        ln -sfn "${TRIPLE}" "${base}/${alias}"
    done
}

write_el2_stubs
ensure_build_tools
build_picolibc
relocate_specs
add_dummyhost_alias
add_triple_aliases

log "done."
log "  picolibc : ${INSTALL_DIR}"
log "  RV_ROOT  : ${EL2_DIR}"
