#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
# Build and test the sep_efuse model.
#
# Usage:
#   ./run_tests.sh              # Release build + run tests (default)
#   ./run_tests.sh --debug      # Debug build + run tests
#   ./run_tests.sh --asan       # AddressSanitizer build + run tests
#   ./run_tests.sh --coverage   # Coverage build + lcov report
#   ./run_tests.sh --ctest      # Run via CTest with verbose output
#   ./run_tests.sh --docs      # Build Doxygen documentation
#   ./run_tests.sh --cppcheck  # Run cppcheck static analysis
#   ./run_tests.sh --clean      # Remove build directory before building
#
# Flags may be combined, e.g.: ./run_tests.sh --debug --clean

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_TYPE="Release"
RUN_CTEST=false
RUN_DOCS=false
RUN_CPPCHECK=false
CLEAN=false

for arg in "$@"; do
  case "$arg" in
    --debug)    BUILD_TYPE="Debug" ;;
    --asan)     BUILD_TYPE="ASAN" ;;
    --coverage) BUILD_TYPE="Coverage" ;;
    --ctest)    RUN_CTEST=true ;;
    --docs)     RUN_DOCS=true ;;
    --cppcheck) RUN_CPPCHECK=true ;;
    --clean)    CLEAN=true ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

BUILD_DIR="${SCRIPT_DIR}/build/$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')"

if ${CLEAN}; then
  echo "Cleaning ${BUILD_DIR} ..."
  rm -rf "${BUILD_DIR}"
fi

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../setup_build_env.sh"
peripheral_setup_build_env || exit 1

if ! ${CLEAN} && peripheral_cache_stale "${BUILD_DIR}"; then
  echo "Removing stale cmake cache (install paths or C++ standard changed) ..."
  rm -rf "${BUILD_DIR}"
fi

mkdir -p "${BUILD_DIR}"
cmake -S "${SCRIPT_DIR}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DBUILD_TESTS=ON \
  "${CMAKE_EXTRA_ARGS[@]}"

cmake --build "${BUILD_DIR}" --parallel "$(peripheral_parallel_jobs)"

echo ""
if ${RUN_DOCS}; then
  cmake --build "${BUILD_DIR}" --target efuse_docs
elif ${RUN_CPPCHECK}; then
  cmake --build "${BUILD_DIR}" --target efuse_cppcheck
elif [ "${BUILD_TYPE}" = "Coverage" ]; then
  cmake --build "${BUILD_DIR}" --target coverage
  peripheral_enforce_coverage_gate "${BUILD_DIR}"
elif ${RUN_CTEST}; then
  ctest --test-dir "${BUILD_DIR}" --output-on-failure -V
else
  "${BUILD_DIR}/bin/efuse_test"

  # secure_tm is a strap latched at reset, so it cannot be exercised from inside a
  # run that started without it. A second run with it set covers that mode; the
  # testbench sees the parameter and runs only the secure-mode checks.
  SECURE_INI="${BUILD_DIR}/accellera_config_secure_tm.ini"
  {
    echo "# Auto-generated by run_tests.sh: secure test mode strap asserted."
    echo "[string]"
    echo "instance_prefix: testbench.efuse_dut"
    echo "chiplet_uid: [2684354560, 2684354561, 2684354562, 2684354563, 2684354564, 2684354565, 2684354566, 2684354567]"
    echo "[int]"
    echo "verbosity: 2"
    echo "[bool]"
    echo "secure_tm: true"
  } > "${SECURE_INI}"

  echo ""
  "${BUILD_DIR}/bin/efuse_test" "${SECURE_INI}"
fi
