// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
/*
 * OTBN otbn_loops Application Binary
 *
 * Generated by common_otbn infrastructure using:
 * - hw/ip/och_otbn/util/otbn_as.py for assembly
 * - Static linker script (otbn_app.ld)
 * - OpenTitan CRC algorithm for validation
 * - Standard RISC-V objcopy for binary extraction
 * - Symbol address extraction from ELF
 *
 * This replaces custom Python build scripts with reusable Makefile flow.
 */

#include "otbn_loops_otbn.h"

/* IMEM: OTBN instruction memory */
const uint32_t otbn_otbn_loops_imem[] = {
    0x418d4101, 0x0030127b, 0x807b0129, 0x01050001, 0x00730001, 0x00000000, 
};
const size_t otbn_otbn_loops_imem_words = 6;



/* DMEM: OTBN data memory initialization */
const uint32_t otbn_otbn_loops_dmem[] = {0x00000000};
const size_t otbn_otbn_loops_dmem_words = 1;

