// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#pragma once

/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was AUTO-GENERATED by this script:
 *       create_reg_c_header.py   (r2025-06-03)
 * ... from this input file:
 *       otbn_cpu_csr.rdl
 * ... using this as the target address space:
 *       otbn_cpu_csr
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/




//==============================================================================
// Addresses for Address Map: otbn_cpu_csr
//==============================================================================


#define OTBN_CPU_CSR_REG_MAP_BASE_ADDR  (0x00000000)
#define OTBN_CPU_CSR_REG_MAP_SIZE       (0x00008C00)

#define INTR_STATE_REG_OFFSET                                                             (0x00000000)
#define INTR_STATE_REG_ADDR                                                               (0x00000000)
#define INTR_ENABLE_REG_OFFSET                                                            (0x00000004)
#define INTR_ENABLE_REG_ADDR                                                              (0x00000004)
#define INTR_TEST_REG_OFFSET                                                              (0x00000008)
#define INTR_TEST_REG_ADDR                                                                (0x00000008)
#define ALERT_TEST_REG_OFFSET                                                             (0x0000000C)
#define ALERT_TEST_REG_ADDR                                                               (0x0000000C)
#define CMD_REG_OFFSET                                                                    (0x00000010)
#define CMD_REG_ADDR                                                                      (0x00000010)
#define CTRL_REG_OFFSET                                                                   (0x00000014)
#define CTRL_REG_ADDR                                                                     (0x00000014)
#define STATUS_REG_OFFSET                                                                 (0x00000018)
#define STATUS_REG_ADDR                                                                   (0x00000018)
#define ERR_BITS_REG_OFFSET                                                               (0x0000001C)
#define ERR_BITS_REG_ADDR                                                                 (0x0000001C)
#define FATAL_ALERT_CAUSE_REG_OFFSET                                                      (0x00000020)
#define FATAL_ALERT_CAUSE_REG_ADDR                                                        (0x00000020)
#define INSN_CNT_REG_OFFSET                                                               (0x00000024)
#define INSN_CNT_REG_ADDR                                                                 (0x00000024)
#define LOAD_CHECKSUM_REG_OFFSET                                                          (0x00000028)
#define LOAD_CHECKSUM_REG_ADDR                                                            (0x00000028)


//==============================================================================
// Memory: IMEM
//==============================================================================

#define IMEM_MEM_BASE_ADDR  (0x00004000)
#define IMEM_MEM_SIZE       (0x00002000)



//==============================================================================
// Memory: DMEM
//==============================================================================

#define DMEM_MEM_BASE_ADDR  (0x00008000)
#define DMEM_MEM_SIZE       (0x00000C00)



#ifndef __ASSEMBLER__

#include <stdint.h>

//==============================================================================
// Structs for Address Map: otbn_cpu_csr
//==============================================================================


typedef struct {
    uint32_t done : 1;
} OTBN_CPU_CSR_INTR_STATE_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_INTR_STATE_reg_t f;
} OTBN_CPU_CSR_INTR_STATE_reg_u;

#define OTBN_CPU_CSR_INTR_STATE_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t done : 1;
} OTBN_CPU_CSR_INTR_ENABLE_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_INTR_ENABLE_reg_t f;
} OTBN_CPU_CSR_INTR_ENABLE_reg_u;

#define OTBN_CPU_CSR_INTR_ENABLE_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t done : 1;
} OTBN_CPU_CSR_INTR_TEST_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_INTR_TEST_reg_t f;
} OTBN_CPU_CSR_INTR_TEST_reg_u;

#define OTBN_CPU_CSR_INTR_TEST_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t fatal : 1;
    uint32_t recov : 1;
} OTBN_CPU_CSR_ALERT_TEST_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_ALERT_TEST_reg_t f;
} OTBN_CPU_CSR_ALERT_TEST_reg_u;

#define OTBN_CPU_CSR_ALERT_TEST_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t cmd : 8;
} OTBN_CPU_CSR_CMD_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_CMD_reg_t f;
} OTBN_CPU_CSR_CMD_reg_u;

#define OTBN_CPU_CSR_CMD_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t software_errs_fatal : 1;
} OTBN_CPU_CSR_CTRL_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_CTRL_reg_t f;
} OTBN_CPU_CSR_CTRL_reg_u;

#define OTBN_CPU_CSR_CTRL_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t status : 8;
} OTBN_CPU_CSR_STATUS_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_STATUS_reg_t f;
} OTBN_CPU_CSR_STATUS_reg_u;

#define OTBN_CPU_CSR_STATUS_REG_DEFAULT (0x00000004)


typedef struct {
    uint32_t bad_data_addr : 1;
    uint32_t bad_insn_addr : 1;
    uint32_t call_stack : 1;
    uint32_t illegal_insn : 1;
    uint32_t loop : 1;
    uint32_t key_invalid : 1;
    uint32_t rnd_rep_chk_fail : 1;
    uint32_t rnd_fips_chk_fail : 1;
    uint32_t rsvd_0 : 8;
    uint32_t imem_intg_violation : 1;
    uint32_t dmem_intg_violation : 1;
    uint32_t reg_intg_violation : 1;
    uint32_t bus_intg_violation : 1;
    uint32_t bad_internal_state : 1;
    uint32_t illegal_bus_access : 1;
    uint32_t lifecycle_escalation : 1;
    uint32_t fatal_software : 1;
} OTBN_CPU_CSR_ERR_BITS_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_ERR_BITS_reg_t f;
} OTBN_CPU_CSR_ERR_BITS_reg_u;

#define OTBN_CPU_CSR_ERR_BITS_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t imem_intg_violation : 1;
    uint32_t dmem_intg_violation : 1;
    uint32_t reg_intg_violation : 1;
    uint32_t bus_intg_violation : 1;
    uint32_t bad_internal_state : 1;
    uint32_t illegal_bus_access : 1;
    uint32_t lifecycle_escalation : 1;
    uint32_t fatal_software : 1;
} OTBN_CPU_CSR_FATAL_ALERT_CAUSE_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_FATAL_ALERT_CAUSE_reg_t f;
} OTBN_CPU_CSR_FATAL_ALERT_CAUSE_reg_u;

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t insn_cnt : 32;
} OTBN_CPU_CSR_INSN_CNT_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_INSN_CNT_reg_t f;
} OTBN_CPU_CSR_INSN_CNT_reg_u;

#define OTBN_CPU_CSR_INSN_CNT_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t checksum : 32;
} OTBN_CPU_CSR_LOAD_CHECKSUM_reg_t;

typedef union {
    uint32_t val;
    OTBN_CPU_CSR_LOAD_CHECKSUM_reg_t f;
} OTBN_CPU_CSR_LOAD_CHECKSUM_reg_u;

#define OTBN_CPU_CSR_LOAD_CHECKSUM_REG_DEFAULT (0x00000000)


typedef struct {
    OTBN_CPU_CSR_INTR_STATE_reg_u intr_state;
    OTBN_CPU_CSR_INTR_ENABLE_reg_u intr_enable;
    OTBN_CPU_CSR_INTR_TEST_reg_u intr_test;
    OTBN_CPU_CSR_ALERT_TEST_reg_u alert_test;
    OTBN_CPU_CSR_CMD_reg_u cmd;
    OTBN_CPU_CSR_CTRL_reg_u ctrl;
    OTBN_CPU_CSR_STATUS_reg_u status;
    OTBN_CPU_CSR_ERR_BITS_reg_u err_bits;
    OTBN_CPU_CSR_FATAL_ALERT_CAUSE_reg_u fatal_alert_cause;
    OTBN_CPU_CSR_INSN_CNT_reg_u insn_cnt;
    OTBN_CPU_CSR_LOAD_CHECKSUM_reg_u load_checksum;
} otbn_cpu_csr_regmap_t;

#endif // __ASSEMBLER__

//==============================================================================
// Bit Fields for Address Map: otbn_cpu_csr
//==============================================================================

#define OTBN_CPU_CSR_INTR_STATE_DONE_MASK  0x1
#define OTBN_CPU_CSR_INTR_STATE_DONE_SHIFT 0

#define OTBN_CPU_CSR_INTR_ENABLE_DONE_MASK  0x1
#define OTBN_CPU_CSR_INTR_ENABLE_DONE_SHIFT 0

#define OTBN_CPU_CSR_INTR_TEST_DONE_MASK  0x1
#define OTBN_CPU_CSR_INTR_TEST_DONE_SHIFT 0

#define OTBN_CPU_CSR_ALERT_TEST_FATAL_MASK  0x1
#define OTBN_CPU_CSR_ALERT_TEST_FATAL_SHIFT 0

#define OTBN_CPU_CSR_ALERT_TEST_RECOV_MASK  0x2
#define OTBN_CPU_CSR_ALERT_TEST_RECOV_SHIFT 1

#define OTBN_CPU_CSR_CMD_CMD_MASK  0xFF
#define OTBN_CPU_CSR_CMD_CMD_SHIFT 0

#define OTBN_CPU_CSR_CTRL_SOFTWARE_ERRS_FATAL_MASK  0x1
#define OTBN_CPU_CSR_CTRL_SOFTWARE_ERRS_FATAL_SHIFT 0

#define OTBN_CPU_CSR_STATUS_STATUS_MASK  0xFF
#define OTBN_CPU_CSR_STATUS_STATUS_SHIFT 0

#define OTBN_CPU_CSR_ERR_BITS_BAD_DATA_ADDR_MASK  0x1
#define OTBN_CPU_CSR_ERR_BITS_BAD_DATA_ADDR_SHIFT 0

#define OTBN_CPU_CSR_ERR_BITS_BAD_INSN_ADDR_MASK  0x2
#define OTBN_CPU_CSR_ERR_BITS_BAD_INSN_ADDR_SHIFT 1

#define OTBN_CPU_CSR_ERR_BITS_CALL_STACK_MASK  0x4
#define OTBN_CPU_CSR_ERR_BITS_CALL_STACK_SHIFT 2

#define OTBN_CPU_CSR_ERR_BITS_ILLEGAL_INSN_MASK  0x8
#define OTBN_CPU_CSR_ERR_BITS_ILLEGAL_INSN_SHIFT 3

#define OTBN_CPU_CSR_ERR_BITS_LOOP_MASK  0x10
#define OTBN_CPU_CSR_ERR_BITS_LOOP_SHIFT 4

#define OTBN_CPU_CSR_ERR_BITS_KEY_INVALID_MASK  0x20
#define OTBN_CPU_CSR_ERR_BITS_KEY_INVALID_SHIFT 5

#define OTBN_CPU_CSR_ERR_BITS_RND_REP_CHK_FAIL_MASK  0x40
#define OTBN_CPU_CSR_ERR_BITS_RND_REP_CHK_FAIL_SHIFT 6

#define OTBN_CPU_CSR_ERR_BITS_RND_FIPS_CHK_FAIL_MASK  0x80
#define OTBN_CPU_CSR_ERR_BITS_RND_FIPS_CHK_FAIL_SHIFT 7

#define OTBN_CPU_CSR_ERR_BITS_IMEM_INTG_VIOLATION_MASK  0x10000
#define OTBN_CPU_CSR_ERR_BITS_IMEM_INTG_VIOLATION_SHIFT 16

#define OTBN_CPU_CSR_ERR_BITS_DMEM_INTG_VIOLATION_MASK  0x20000
#define OTBN_CPU_CSR_ERR_BITS_DMEM_INTG_VIOLATION_SHIFT 17

#define OTBN_CPU_CSR_ERR_BITS_REG_INTG_VIOLATION_MASK  0x40000
#define OTBN_CPU_CSR_ERR_BITS_REG_INTG_VIOLATION_SHIFT 18

#define OTBN_CPU_CSR_ERR_BITS_BUS_INTG_VIOLATION_MASK  0x80000
#define OTBN_CPU_CSR_ERR_BITS_BUS_INTG_VIOLATION_SHIFT 19

#define OTBN_CPU_CSR_ERR_BITS_BAD_INTERNAL_STATE_MASK  0x100000
#define OTBN_CPU_CSR_ERR_BITS_BAD_INTERNAL_STATE_SHIFT 20

#define OTBN_CPU_CSR_ERR_BITS_ILLEGAL_BUS_ACCESS_MASK  0x200000
#define OTBN_CPU_CSR_ERR_BITS_ILLEGAL_BUS_ACCESS_SHIFT 21

#define OTBN_CPU_CSR_ERR_BITS_LIFECYCLE_ESCALATION_MASK  0x400000
#define OTBN_CPU_CSR_ERR_BITS_LIFECYCLE_ESCALATION_SHIFT 22

#define OTBN_CPU_CSR_ERR_BITS_FATAL_SOFTWARE_MASK  0x800000
#define OTBN_CPU_CSR_ERR_BITS_FATAL_SOFTWARE_SHIFT 23

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_IMEM_INTG_VIOLATION_MASK  0x1
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_IMEM_INTG_VIOLATION_SHIFT 0

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_DMEM_INTG_VIOLATION_MASK  0x2
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_DMEM_INTG_VIOLATION_SHIFT 1

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_REG_INTG_VIOLATION_MASK  0x4
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_REG_INTG_VIOLATION_SHIFT 2

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_BUS_INTG_VIOLATION_MASK  0x8
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_BUS_INTG_VIOLATION_SHIFT 3

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_BAD_INTERNAL_STATE_MASK  0x10
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_BAD_INTERNAL_STATE_SHIFT 4

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_ILLEGAL_BUS_ACCESS_MASK  0x20
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_ILLEGAL_BUS_ACCESS_SHIFT 5

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_LIFECYCLE_ESCALATION_MASK  0x40
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_LIFECYCLE_ESCALATION_SHIFT 6

#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_FATAL_SOFTWARE_MASK  0x80
#define OTBN_CPU_CSR_FATAL_ALERT_CAUSE_FATAL_SOFTWARE_SHIFT 7

#define OTBN_CPU_CSR_INSN_CNT_INSN_CNT_MASK  0xFFFFFFFF
#define OTBN_CPU_CSR_INSN_CNT_INSN_CNT_SHIFT 0

#define OTBN_CPU_CSR_LOAD_CHECKSUM_CHECKSUM_MASK  0xFFFFFFFF
#define OTBN_CPU_CSR_LOAD_CHECKSUM_CHECKSUM_SHIFT 0

