// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#pragma once
#include <stdint.h>
#include <stddef.h>

/* Generated by common_otbn infrastructure using OpenTitan build tools */

/* Expected CRC checksum (matches OTBN LOAD_CHECKSUM register) */
#define OTBN_OTBN_LOOPS_EXPECTED_CRC 0x9598d8d6U

/* OTBN symbol addresses (OpenTitan-style) */
#define _otbn_remote_app_otbn_loops__dmem_data_start ((const uint32_t*)0x0)
#define _otbn_remote_app_otbn_loops__imem_end ((const uint32_t*)0x18)
#define _otbn_remote_app_otbn_loops__imem_start ((const uint32_t*)0x0)
#define _otbn_remote_app_otbn_loops__imem_size ((const uint32_t*)0x18)
#define _otbn_remote_app_otbn_loops__start ((const uint32_t*)0x0)
#define _otbn_remote_app_otbn_loops__dmem_bss_start ((const uint32_t*)0x0)
#define _otbn_remote_app_otbn_loops__dmem_data_end ((const uint32_t*)0x0)
#define _otbn_remote_app_otbn_loops__dmem_bss_end ((const uint32_t*)0x0)
#define _otbn_remote_app_otbn_loops__dmem_bss_offset ((const uint32_t*)0x0)

/* OpenTitan-compatible macros for otbn_loops */
#define OTBN_DECLARE_SYMBOL_ADDR(app, sym) /* Already declared above */
#define OTBN_ADDR_T_INIT(app, sym) ((uint32_t)_otbn_remote_app_##app##_##sym)

/* OTBN memory arrays */
extern const uint32_t otbn_otbn_loops_imem[];
extern const size_t otbn_otbn_loops_imem_words;
extern const uint32_t otbn_otbn_loops_dmem[];
extern const size_t otbn_otbn_loops_dmem_words;

