/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was auto-generated by this script:
 *       create_reg_sv_header.py   (r2025-06-03)
 * ... from this input file:
 *       entropy_source.rdl
 * ... using this as the target address space:
 *       entropy_source
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef ENTROPY_SOURCE_REG_SVH
`define ENTROPY_SOURCE_REG_SVH



//==============================================================================
// Addresses for Address Map: entropy_source
//==============================================================================


localparam int unsigned ENTROPY_SOURCE_REG_MAP_BASE_ADDR                                                          = 32'h00000000;
localparam int unsigned ENTROPY_SOURCE_REG_MAP_SIZE                                                               = 32'h00000154;


localparam int unsigned COMPONENT_ID_REG_OFFSET                                                                   = 32'h00000000;
localparam int unsigned COMPONENT_ID_REG_ADDR                                                                     = 32'h00000000;
localparam int unsigned CTRL_REG_OFFSET                                                                           = 32'h00000004;
localparam int unsigned CTRL_REG_ADDR                                                                             = 32'h00000004;
localparam int unsigned STATUS_REG_OFFSET                                                                         = 32'h00000008;
localparam int unsigned STATUS_REG_ADDR                                                                           = 32'h00000008;
localparam int unsigned DEBUG_CTRL_REG_OFFSET                                                                     = 32'h0000000C;
localparam int unsigned DEBUG_CTRL_REG_ADDR                                                                       = 32'h0000000C;
localparam int unsigned INTR_STATUS_REG_OFFSET                                                                    = 32'h00000010;
localparam int unsigned INTR_STATUS_REG_ADDR                                                                      = 32'h00000010;
localparam int unsigned INTR_ENABLE_REG_OFFSET                                                                    = 32'h00000014;
localparam int unsigned INTR_ENABLE_REG_ADDR                                                                      = 32'h00000014;
localparam int unsigned INTR_TEST_REG_OFFSET                                                                      = 32'h00000018;
localparam int unsigned INTR_TEST_REG_ADDR                                                                        = 32'h00000018;
localparam int unsigned SHA256_STATUS_REG_OFFSET                                                                  = 32'h0000001C;
localparam int unsigned SHA256_STATUS_REG_ADDR                                                                    = 32'h0000001C;
localparam int unsigned FIFO_CTRL_REG_OFFSET                                                                      = 32'h00000020;
localparam int unsigned FIFO_CTRL_REG_ADDR                                                                        = 32'h00000020;
localparam int unsigned FIFO_STATUS_REG_OFFSET                                                                    = 32'h00000024;
localparam int unsigned FIFO_STATUS_REG_ADDR                                                                      = 32'h00000024;
localparam int unsigned FIFO_RDATA_REG_OFFSET                                                                     = 32'h00000028;
localparam int unsigned FIFO_RDATA_REG_ADDR                                                                       = 32'h00000028;
localparam int unsigned HEALTH_TEST_CTRL_REG_OFFSET                                                               = 32'h00000030;
localparam int unsigned HEALTH_TEST_CTRL_REG_ADDR                                                                 = 32'h00000030;
localparam int unsigned HEALTH_TEST_WINDOW_SIZE_REG_OFFSET                                                        = 32'h00000034;
localparam int unsigned HEALTH_TEST_WINDOW_SIZE_REG_ADDR                                                          = 32'h00000034;
localparam int unsigned MARKOV_TEST_PROB_THRESHOLDS_REG_OFFSET                                                    = 32'h00000038;
localparam int unsigned MARKOV_TEST_PROB_THRESHOLDS_REG_ADDR                                                      = 32'h00000038;
localparam int unsigned HEALTH_TEST_STATUS_REG_OFFSET                                                             = 32'h00000040;
localparam int unsigned HEALTH_TEST_STATUS_REG_ADDR                                                               = 32'h00000040;
localparam int unsigned REPETITION_TEST_COUNT_REG_OFFSET                                                          = 32'h00000044;
localparam int unsigned REPETITION_TEST_COUNT_REG_ADDR                                                            = 32'h00000044;
localparam int unsigned APT_PATTERN_COUNT_1BIT_REG_OFFSET                                                         = 32'h00000050;
localparam int unsigned APT_PATTERN_COUNT_1BIT_REG_ADDR                                                           = 32'h00000050;
localparam int unsigned APT_PATTERN_COUNT_2BIT_REG_OFFSET                                                         = 32'h00000054;
localparam int unsigned APT_PATTERN_COUNT_2BIT_REG_ADDR                                                           = 32'h00000054;
localparam int unsigned APT_PATTERN_COUNT_3BIT_REG_OFFSET                                                         = 32'h00000058;
localparam int unsigned APT_PATTERN_COUNT_3BIT_REG_ADDR                                                           = 32'h00000058;
localparam int unsigned APT_PATTERN_COUNT_4BIT_REG_OFFSET                                                         = 32'h0000005C;
localparam int unsigned APT_PATTERN_COUNT_4BIT_REG_ADDR                                                           = 32'h0000005C;
localparam int unsigned APT_PROPORTION_1BIT_REG_OFFSET                                                            = 32'h00000060;
localparam int unsigned APT_PROPORTION_1BIT_REG_ADDR                                                              = 32'h00000060;
localparam int unsigned APT_PROPORTION_2BIT_REG_OFFSET                                                            = 32'h00000064;
localparam int unsigned APT_PROPORTION_2BIT_REG_ADDR                                                              = 32'h00000064;
localparam int unsigned APT_PROPORTION_3BIT_REG_OFFSET                                                            = 32'h00000068;
localparam int unsigned APT_PROPORTION_3BIT_REG_ADDR                                                              = 32'h00000068;
localparam int unsigned APT_PROPORTION_4BIT_REG_OFFSET                                                            = 32'h0000006C;
localparam int unsigned APT_PROPORTION_4BIT_REG_ADDR                                                              = 32'h0000006C;
localparam int unsigned MARKOV_TEST_COUNTS_0_REG_OFFSET                                                           = 32'h00000080;
localparam int unsigned MARKOV_TEST_COUNTS_0_REG_ADDR                                                             = 32'h00000080;
localparam int unsigned MARKOV_TEST_COUNTS_1_REG_OFFSET                                                           = 32'h00000084;
localparam int unsigned MARKOV_TEST_COUNTS_1_REG_ADDR                                                             = 32'h00000084;
localparam int unsigned MARKOV_TEST_PROBABILITIES_REG_OFFSET                                                      = 32'h00000088;
localparam int unsigned MARKOV_TEST_PROBABILITIES_REG_ADDR                                                        = 32'h00000088;
localparam int unsigned RING_OSC_ENABLE_REG_OFFSET                                                                = 32'h00000090;
localparam int unsigned RING_OSC_ENABLE_REG_ADDR                                                                  = 32'h00000090;
localparam int unsigned RING_OSC_TUNE_REG_OFFSET                                                                  = 32'h00000094;
localparam int unsigned RING_OSC_TUNE_REG_ADDR                                                                    = 32'h00000094;
localparam int unsigned RING_OSC_CTRL_REG_OFFSET                                                                  = 32'h00000098;
localparam int unsigned RING_OSC_CTRL_REG_ADDR                                                                    = 32'h00000098;
localparam int unsigned DECORRELATOR_CTRL_REG_OFFSET                                                              = 32'h000000A0;
localparam int unsigned DECORRELATOR_CTRL_REG_ADDR                                                                = 32'h000000A0;
localparam int unsigned DECORRELATOR_MASK_REG_OFFSET                                                              = 32'h000000A4;
localparam int unsigned DECORRELATOR_MASK_REG_ADDR                                                                = 32'h000000A4;
localparam int unsigned STARTUP_CTRL_REG_OFFSET                                                                   = 32'h000000B0;
localparam int unsigned STARTUP_CTRL_REG_ADDR                                                                     = 32'h000000B0;
localparam int unsigned GENERATOR_0_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000C0;
localparam int unsigned GENERATOR_0_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000C0;
localparam int unsigned GENERATOR_1_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000C4;
localparam int unsigned GENERATOR_1_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000C4;
localparam int unsigned GENERATOR_2_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000C8;
localparam int unsigned GENERATOR_2_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000C8;
localparam int unsigned GENERATOR_3_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000CC;
localparam int unsigned GENERATOR_3_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000CC;
localparam int unsigned GENERATOR_4_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000D0;
localparam int unsigned GENERATOR_4_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000D0;
localparam int unsigned GENERATOR_5_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000D4;
localparam int unsigned GENERATOR_5_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000D4;
localparam int unsigned GENERATOR_6_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000D8;
localparam int unsigned GENERATOR_6_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000D8;
localparam int unsigned GENERATOR_7_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000DC;
localparam int unsigned GENERATOR_7_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000DC;
localparam int unsigned GENERATOR_8_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000E0;
localparam int unsigned GENERATOR_8_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000E0;
localparam int unsigned GENERATOR_9_HEALTH_STATUS_REG_OFFSET                                                      = 32'h000000E4;
localparam int unsigned GENERATOR_9_HEALTH_STATUS_REG_ADDR                                                        = 32'h000000E4;
localparam int unsigned GENERATOR_10_HEALTH_STATUS_REG_OFFSET                                                     = 32'h000000E8;
localparam int unsigned GENERATOR_10_HEALTH_STATUS_REG_ADDR                                                       = 32'h000000E8;
localparam int unsigned GENERATOR_11_HEALTH_STATUS_REG_OFFSET                                                     = 32'h000000EC;
localparam int unsigned GENERATOR_11_HEALTH_STATUS_REG_ADDR                                                       = 32'h000000EC;
localparam int unsigned GENERATOR_0_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000100;
localparam int unsigned GENERATOR_0_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000100;
localparam int unsigned GENERATOR_1_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000104;
localparam int unsigned GENERATOR_1_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000104;
localparam int unsigned GENERATOR_2_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000108;
localparam int unsigned GENERATOR_2_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000108;
localparam int unsigned GENERATOR_3_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h0000010C;
localparam int unsigned GENERATOR_3_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h0000010C;
localparam int unsigned GENERATOR_4_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000110;
localparam int unsigned GENERATOR_4_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000110;
localparam int unsigned GENERATOR_5_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000114;
localparam int unsigned GENERATOR_5_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000114;
localparam int unsigned GENERATOR_6_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000118;
localparam int unsigned GENERATOR_6_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000118;
localparam int unsigned GENERATOR_7_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h0000011C;
localparam int unsigned GENERATOR_7_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h0000011C;
localparam int unsigned GENERATOR_8_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000120;
localparam int unsigned GENERATOR_8_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000120;
localparam int unsigned GENERATOR_9_SAMPLE_CLK_CONFIG_REG_OFFSET                                                  = 32'h00000124;
localparam int unsigned GENERATOR_9_SAMPLE_CLK_CONFIG_REG_ADDR                                                    = 32'h00000124;
localparam int unsigned GENERATOR_10_SAMPLE_CLK_CONFIG_REG_OFFSET                                                 = 32'h00000128;
localparam int unsigned GENERATOR_10_SAMPLE_CLK_CONFIG_REG_ADDR                                                   = 32'h00000128;
localparam int unsigned GENERATOR_11_SAMPLE_CLK_CONFIG_REG_OFFSET                                                 = 32'h0000012C;
localparam int unsigned GENERATOR_11_SAMPLE_CLK_CONFIG_REG_ADDR                                                   = 32'h0000012C;
localparam int unsigned HT_WATERMARK_NUM_REG_OFFSET                                                               = 32'h00000130;
localparam int unsigned HT_WATERMARK_NUM_REG_ADDR                                                                 = 32'h00000130;
localparam int unsigned HT_WATERMARK_REG_OFFSET                                                                   = 32'h00000134;
localparam int unsigned HT_WATERMARK_REG_ADDR                                                                     = 32'h00000134;
localparam int unsigned REPCNT_TOTAL_FAILS_REG_OFFSET                                                             = 32'h00000138;
localparam int unsigned REPCNT_TOTAL_FAILS_REG_ADDR                                                               = 32'h00000138;
localparam int unsigned APT_HI_TOTAL_FAILS_REG_OFFSET                                                             = 32'h0000013C;
localparam int unsigned APT_HI_TOTAL_FAILS_REG_ADDR                                                               = 32'h0000013C;
localparam int unsigned APT_LO_TOTAL_FAILS_REG_OFFSET                                                             = 32'h00000140;
localparam int unsigned APT_LO_TOTAL_FAILS_REG_ADDR                                                               = 32'h00000140;
localparam int unsigned MARKOV_HI_TOTAL_FAILS_REG_OFFSET                                                          = 32'h00000144;
localparam int unsigned MARKOV_HI_TOTAL_FAILS_REG_ADDR                                                            = 32'h00000144;
localparam int unsigned MARKOV_LO_TOTAL_FAILS_REG_OFFSET                                                          = 32'h00000148;
localparam int unsigned MARKOV_LO_TOTAL_FAILS_REG_ADDR                                                            = 32'h00000148;
localparam int unsigned ALERT_SUMMARY_FAIL_COUNTS_REG_OFFSET                                                      = 32'h0000014C;
localparam int unsigned ALERT_SUMMARY_FAIL_COUNTS_REG_ADDR                                                        = 32'h0000014C;
localparam int unsigned ALERT_FAIL_COUNTS_REG_OFFSET                                                              = 32'h00000150;
localparam int unsigned ALERT_FAIL_COUNTS_REG_ADDR                                                                = 32'h00000150;


//==============================================================================
// Default values for registers
//==============================================================================

localparam longint unsigned ENTROPY_SOURCE_COMPONENT_ID_REG_DEFAULT                                               = 32'h01000001;
localparam longint unsigned ENTROPY_SOURCE_CTRL_REG_DEFAULT                                                       = 32'h10000000;
localparam longint unsigned ENTROPY_SOURCE_STATUS_REG_DEFAULT                                                     = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_DEBUG_CTRL_REG_DEFAULT                                                 = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_INTR_STATUS_REG_DEFAULT                                                = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_INTR_ENABLE_REG_DEFAULT                                                = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_INTR_TEST_REG_DEFAULT                                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_SHA256_STATUS_REG_DEFAULT                                              = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_FIFO_CTRL_REG_DEFAULT                                                  = 32'h00000001;
localparam longint unsigned ENTROPY_SOURCE_FIFO_STATUS_REG_DEFAULT                                                = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_FIFO_RDATA_REG_DEFAULT                                                 = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_HEALTH_TEST_CTRL_REG_DEFAULT                                           = 32'h00001907;
localparam longint unsigned ENTROPY_SOURCE_HEALTH_TEST_WINDOW_SIZE_REG_DEFAULT                                    = 32'h00000800;
localparam longint unsigned ENTROPY_SOURCE_MARKOV_TEST_PROB_THRESHOLDS_REG_DEFAULT                                = 32'h006404B0;
localparam longint unsigned ENTROPY_SOURCE_HEALTH_TEST_STATUS_REG_DEFAULT                                         = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_REPETITION_TEST_COUNT_REG_DEFAULT                                      = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_REG_DEFAULT                                     = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_REG_DEFAULT                                     = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_REG_DEFAULT                                     = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_REG_DEFAULT                                     = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_PROPORTION_1BIT_REG_DEFAULT                                        = 32'h000004B0;
localparam longint unsigned ENTROPY_SOURCE_APT_PROPORTION_2BIT_REG_DEFAULT                                        = 32'h00000080;
localparam longint unsigned ENTROPY_SOURCE_APT_PROPORTION_3BIT_REG_DEFAULT                                        = 32'h00000040;
localparam longint unsigned ENTROPY_SOURCE_APT_PROPORTION_4BIT_REG_DEFAULT                                        = 32'h00000020;
localparam longint unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_0_REG_DEFAULT                                       = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_1_REG_DEFAULT                                       = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_RING_OSC_ENABLE_REG_DEFAULT                                            = 32'h00FFFFFF;
localparam longint unsigned ENTROPY_SOURCE_RING_OSC_TUNE_REG_DEFAULT                                              = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_RING_OSC_CTRL_REG_DEFAULT                                              = 32'h00000FFF;
localparam longint unsigned ENTROPY_SOURCE_DECORRELATOR_CTRL_REG_DEFAULT                                          = 32'h0003F000;
localparam longint unsigned ENTROPY_SOURCE_DECORRELATOR_MASK_REG_DEFAULT                                          = 32'h000000FF;
localparam longint unsigned ENTROPY_SOURCE_STARTUP_CTRL_REG_DEFAULT                                               = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_0_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_1_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_2_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_3_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_4_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_5_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_6_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_7_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_8_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_9_HEALTH_STATUS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_10_HEALTH_STATUS_REG_DEFAULT                                 = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_11_HEALTH_STATUS_REG_DEFAULT                                 = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_0_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_1_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_2_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000001;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_3_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000001;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_4_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000002;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_5_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000002;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_6_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_7_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_8_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000001;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_9_SAMPLE_CLK_CONFIG_REG_DEFAULT                              = 32'h00000001;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_10_SAMPLE_CLK_CONFIG_REG_DEFAULT                             = 32'h00000002;
localparam longint unsigned ENTROPY_SOURCE_GENERATOR_11_SAMPLE_CLK_CONFIG_REG_DEFAULT                             = 32'h00000002;
localparam longint unsigned ENTROPY_SOURCE_HT_WATERMARK_NUM_REG_DEFAULT                                           = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_HT_WATERMARK_REG_DEFAULT                                               = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_REPCNT_TOTAL_FAILS_REG_DEFAULT                                         = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_HI_TOTAL_FAILS_REG_DEFAULT                                         = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_APT_LO_TOTAL_FAILS_REG_DEFAULT                                         = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_MARKOV_HI_TOTAL_FAILS_REG_DEFAULT                                      = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_MARKOV_LO_TOTAL_FAILS_REG_DEFAULT                                      = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_ALERT_SUMMARY_FAIL_COUNTS_REG_DEFAULT                                  = 32'h00000000;
localparam longint unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_REG_DEFAULT                                          = 32'h00000000;



//==============================================================================
// Bit Fields for Address Map: entropy_source
//==============================================================================

localparam int unsigned ENTROPY_SOURCE_COMPONENT_ID_NAME_MASK                                                     = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_COMPONENT_ID_NAME_SHIFT                                                    = 0;

localparam int unsigned ENTROPY_SOURCE_COMPONENT_ID_MINOR_VERSION_MASK                                            = 32'hF000000;
localparam int unsigned ENTROPY_SOURCE_COMPONENT_ID_MINOR_VERSION_SHIFT                                           = 24;

localparam int unsigned ENTROPY_SOURCE_COMPONENT_ID_MAJOR_VERSION_MASK                                            = 32'hF0000000;
localparam int unsigned ENTROPY_SOURCE_COMPONENT_ID_MAJOR_VERSION_SHIFT                                           = 28;

localparam int unsigned ENTROPY_SOURCE_CTRL_RESET_MASK                                                            = 32'h1;
localparam int unsigned ENTROPY_SOURCE_CTRL_RESET_SHIFT                                                           = 0;

localparam int unsigned ENTROPY_SOURCE_CTRL_AUTOTUNE_ENABLE_MASK                                                  = 32'h10;
localparam int unsigned ENTROPY_SOURCE_CTRL_AUTOTUNE_ENABLE_SHIFT                                                 = 4;

localparam int unsigned ENTROPY_SOURCE_CTRL_BYPASS_ENTROPY_COMPRESSOR_MASK                                        = 32'h100;
localparam int unsigned ENTROPY_SOURCE_CTRL_BYPASS_ENTROPY_COMPRESSOR_SHIFT                                       = 8;

localparam int unsigned ENTROPY_SOURCE_CTRL_DOWNSAMPLE_RATE_MASK                                                  = 32'h3FF0000;
localparam int unsigned ENTROPY_SOURCE_CTRL_DOWNSAMPLE_RATE_SHIFT                                                 = 16;

localparam int unsigned ENTROPY_SOURCE_CTRL_SHA256_WHITENING_ENABLE_MASK                                          = 32'h10000000;
localparam int unsigned ENTROPY_SOURCE_CTRL_SHA256_WHITENING_ENABLE_SHIFT                                         = 28;

localparam int unsigned ENTROPY_SOURCE_STATUS_RSVD_MASK                                                           = 32'h1;
localparam int unsigned ENTROPY_SOURCE_STATUS_RSVD_SHIFT                                                          = 0;

localparam int unsigned ENTROPY_SOURCE_DEBUG_CTRL_SELECT_SIGNAL_MASK                                              = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_DEBUG_CTRL_SELECT_SIGNAL_SHIFT                                             = 0;

localparam int unsigned ENTROPY_SOURCE_DEBUG_CTRL_SELECT_FREQ_DIV_MASK                                            = 32'h700;
localparam int unsigned ENTROPY_SOURCE_DEBUG_CTRL_SELECT_FREQ_DIV_SHIFT                                           = 8;

localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_HEALTH_TEST_FAILED_MASK                                        = 32'h1;
localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_HEALTH_TEST_FAILED_SHIFT                                       = 0;

localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_FIFO_ERROR_MASK                                                = 32'h10;
localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_FIFO_ERROR_SHIFT                                               = 4;

localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_FIFO_OVERFLOW_MASK                                             = 32'h100;
localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_FIFO_OVERFLOW_SHIFT                                            = 8;

localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_FIFO_UNDERFLOW_MASK                                            = 32'h1000;
localparam int unsigned ENTROPY_SOURCE_INTR_STATUS_FIFO_UNDERFLOW_SHIFT                                           = 12;

localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_HEALTH_TEST_FAILED_MASK                                        = 32'h1;
localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_HEALTH_TEST_FAILED_SHIFT                                       = 0;

localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_FIFO_ERROR_MASK                                                = 32'h10;
localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_FIFO_ERROR_SHIFT                                               = 4;

localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_FIFO_OVERFLOW_MASK                                             = 32'h100;
localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_FIFO_OVERFLOW_SHIFT                                            = 8;

localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_FIFO_UNDERFLOW_MASK                                            = 32'h1000;
localparam int unsigned ENTROPY_SOURCE_INTR_ENABLE_FIFO_UNDERFLOW_SHIFT                                           = 12;

localparam int unsigned ENTROPY_SOURCE_INTR_TEST_HEALTH_TEST_FAILED_MASK                                          = 32'h1;
localparam int unsigned ENTROPY_SOURCE_INTR_TEST_HEALTH_TEST_FAILED_SHIFT                                         = 0;

localparam int unsigned ENTROPY_SOURCE_INTR_TEST_FIFO_ERROR_MASK                                                  = 32'h10;
localparam int unsigned ENTROPY_SOURCE_INTR_TEST_FIFO_ERROR_SHIFT                                                 = 4;

localparam int unsigned ENTROPY_SOURCE_INTR_TEST_FIFO_OVERFLOW_MASK                                               = 32'h100;
localparam int unsigned ENTROPY_SOURCE_INTR_TEST_FIFO_OVERFLOW_SHIFT                                              = 8;

localparam int unsigned ENTROPY_SOURCE_INTR_TEST_FIFO_UNDERFLOW_MASK                                              = 32'h1000;
localparam int unsigned ENTROPY_SOURCE_INTR_TEST_FIFO_UNDERFLOW_SHIFT                                             = 12;

localparam int unsigned ENTROPY_SOURCE_SHA256_STATUS_BUSY_MASK                                                    = 32'h1;
localparam int unsigned ENTROPY_SOURCE_SHA256_STATUS_BUSY_SHIFT                                                   = 0;

localparam int unsigned ENTROPY_SOURCE_SHA256_STATUS_INPUT_COUNT_MASK                                             = 32'hF0;
localparam int unsigned ENTROPY_SOURCE_SHA256_STATUS_INPUT_COUNT_SHIFT                                            = 4;

localparam int unsigned ENTROPY_SOURCE_SHA256_STATUS_OUTPUT_COUNT_MASK                                            = 32'h700;
localparam int unsigned ENTROPY_SOURCE_SHA256_STATUS_OUTPUT_COUNT_SHIFT                                           = 8;

localparam int unsigned ENTROPY_SOURCE_FIFO_CTRL_ENABLE_MASK                                                      = 32'h1;
localparam int unsigned ENTROPY_SOURCE_FIFO_CTRL_ENABLE_SHIFT                                                     = 0;

localparam int unsigned ENTROPY_SOURCE_FIFO_CTRL_ENTROPY_CHURN_ENABLE_MASK                                        = 32'h10;
localparam int unsigned ENTROPY_SOURCE_FIFO_CTRL_ENTROPY_CHURN_ENABLE_SHIFT                                       = 4;

localparam int unsigned ENTROPY_SOURCE_FIFO_STATUS_LEVEL_MASK                                                     = 32'h7F;
localparam int unsigned ENTROPY_SOURCE_FIFO_STATUS_LEVEL_SHIFT                                                    = 0;

localparam int unsigned ENTROPY_SOURCE_FIFO_STATUS_WPTR_MASK                                                      = 32'h1F00;
localparam int unsigned ENTROPY_SOURCE_FIFO_STATUS_WPTR_SHIFT                                                     = 8;

localparam int unsigned ENTROPY_SOURCE_FIFO_STATUS_RPTR_MASK                                                      = 32'h1F0000;
localparam int unsigned ENTROPY_SOURCE_FIFO_STATUS_RPTR_SHIFT                                                     = 16;

localparam int unsigned ENTROPY_SOURCE_FIFO_RDATA_RDATA_MASK                                                      = 32'hFFFFFFFF;
localparam int unsigned ENTROPY_SOURCE_FIFO_RDATA_RDATA_SHIFT                                                     = 0;

localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_CTRL_ENABLE_MASK                                               = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_CTRL_ENABLE_SHIFT                                              = 0;

localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_CTRL_REPETITION_LIMIT_MASK                                     = 32'hFF00;
localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_CTRL_REPETITION_LIMIT_SHIFT                                    = 8;

localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_WINDOW_SIZE_SIZE_MASK                                          = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_WINDOW_SIZE_SIZE_SHIFT                                         = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROB_THRESHOLDS_PROB_01_THRESHOLD_MASK                         = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROB_THRESHOLDS_PROB_01_THRESHOLD_SHIFT                        = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROB_THRESHOLDS_PROB_10_THRESHOLD_MASK                         = 32'hFFFF0000;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROB_THRESHOLDS_PROB_10_THRESHOLD_SHIFT                        = 16;

localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_STATUS_HEALTH_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_HEALTH_TEST_STATUS_HEALTH_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_REPETITION_TEST_COUNT_REPETITION_COUNT_MASK                                = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_REPETITION_TEST_COUNT_REPETITION_COUNT_SHIFT                               = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_PATTERN_COUNT_MASK                                  = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_PATTERN_COUNT_SHIFT                                 = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_TARGET_PATTERN_MASK                                 = 32'hF0000;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_TARGET_PATTERN_SHIFT                                = 16;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_SAMPLES_PROCESSED_MASK                              = 32'h3FF00000;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_SAMPLES_PROCESSED_SHIFT                             = 20;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_PATTERN_COUNT_MASK                                  = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_PATTERN_COUNT_SHIFT                                 = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_TARGET_PATTERN_MASK                                 = 32'hF0000;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_TARGET_PATTERN_SHIFT                                = 16;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_SAMPLES_PROCESSED_MASK                              = 32'h3FF00000;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_SAMPLES_PROCESSED_SHIFT                             = 20;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_PATTERN_COUNT_MASK                                  = 32'h3FF;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_PATTERN_COUNT_SHIFT                                 = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_TARGET_PATTERN_MASK                                 = 32'h3C00;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_TARGET_PATTERN_SHIFT                                = 10;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_SAMPLES_PROCESSED_MASK                              = 32'h3FF00000;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_3BIT_SAMPLES_PROCESSED_SHIFT                             = 20;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_PATTERN_COUNT_MASK                                  = 32'h3FF;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_PATTERN_COUNT_SHIFT                                 = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_TARGET_PATTERN_MASK                                 = 32'h3C00;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_TARGET_PATTERN_SHIFT                                = 10;

localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_SAMPLES_PROCESSED_MASK                              = 32'h3FF00000;
localparam int unsigned ENTROPY_SOURCE_APT_PATTERN_COUNT_4BIT_SAMPLES_PROCESSED_SHIFT                             = 20;

localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_1BIT_LIMIT_MASK                                             = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_1BIT_LIMIT_SHIFT                                            = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_2BIT_LIMIT_MASK                                             = 32'h3FF;
localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_2BIT_LIMIT_SHIFT                                            = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_3BIT_LIMIT_MASK                                             = 32'h3FF;
localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_3BIT_LIMIT_SHIFT                                            = 0;

localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_4BIT_LIMIT_MASK                                             = 32'h3FF;
localparam int unsigned ENTROPY_SOURCE_APT_PROPORTION_4BIT_LIMIT_SHIFT                                            = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_0_COUNT_01_MASK                                         = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_0_COUNT_01_SHIFT                                        = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_0_COUNT_10_MASK                                         = 32'hFFFF0000;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_0_COUNT_10_SHIFT                                        = 16;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_1_COUNT_00_MASK                                         = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_1_COUNT_00_SHIFT                                        = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_1_COUNT_11_MASK                                         = 32'hFFFF0000;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_COUNTS_1_COUNT_11_SHIFT                                        = 16;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_01_MASK                                     = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_01_SHIFT                                    = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_10_MASK                                     = 32'hFF00;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_10_SHIFT                                    = 8;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_00_MASK                                     = 32'hFF0000;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_00_SHIFT                                    = 16;

localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_11_MASK                                     = 32'hFF000000;
localparam int unsigned ENTROPY_SOURCE_MARKOV_TEST_PROBABILITIES_PROB_11_SHIFT                                    = 24;

localparam int unsigned ENTROPY_SOURCE_RING_OSC_ENABLE_ENABLE_MASK                                                = 32'hFFF;
localparam int unsigned ENTROPY_SOURCE_RING_OSC_ENABLE_ENABLE_SHIFT                                               = 0;

localparam int unsigned ENTROPY_SOURCE_RING_OSC_ENABLE_SAMPLE_CLK_ENABLE_MASK                                     = 32'hFFF000;
localparam int unsigned ENTROPY_SOURCE_RING_OSC_ENABLE_SAMPLE_CLK_ENABLE_SHIFT                                    = 12;

localparam int unsigned ENTROPY_SOURCE_RING_OSC_TUNE_DETUNE_MASK                                                  = 32'hFFF;
localparam int unsigned ENTROPY_SOURCE_RING_OSC_TUNE_DETUNE_SHIFT                                                 = 0;

localparam int unsigned ENTROPY_SOURCE_RING_OSC_TUNE_SAMPLE_CLK_DETUNE_MASK                                       = 32'hFFF000;
localparam int unsigned ENTROPY_SOURCE_RING_OSC_TUNE_SAMPLE_CLK_DETUNE_SHIFT                                      = 12;

localparam int unsigned ENTROPY_SOURCE_RING_OSC_CTRL_SAMPLE_CLK_SELECT_MASK                                       = 32'hFFF;
localparam int unsigned ENTROPY_SOURCE_RING_OSC_CTRL_SAMPLE_CLK_SELECT_SHIFT                                      = 0;

localparam int unsigned ENTROPY_SOURCE_DECORRELATOR_CTRL_BYPASS_MASK                                              = 32'hFFF;
localparam int unsigned ENTROPY_SOURCE_DECORRELATOR_CTRL_BYPASS_SHIFT                                             = 0;

localparam int unsigned ENTROPY_SOURCE_DECORRELATOR_CTRL_SAMPLE_CLK_DIV_MASK                                      = 32'hFFFFF000;
localparam int unsigned ENTROPY_SOURCE_DECORRELATOR_CTRL_SAMPLE_CLK_DIV_SHIFT                                     = 12;

localparam int unsigned ENTROPY_SOURCE_DECORRELATOR_MASK_ENTROPY_BYTE_MASK_MASK                                   = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_DECORRELATOR_MASK_ENTROPY_BYTE_MASK_SHIFT                                  = 0;

localparam int unsigned ENTROPY_SOURCE_STARTUP_CTRL_DELAY_CYCLES_MASK                                             = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_STARTUP_CTRL_DELAY_CYCLES_SHIFT                                            = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_0_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_0_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_1_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_1_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_2_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_2_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_3_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_3_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_4_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_4_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_5_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_5_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_6_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_6_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_7_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_7_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_8_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_8_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_9_HEALTH_STATUS_STATUS_MASK                                      = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_9_HEALTH_STATUS_STATUS_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_10_HEALTH_STATUS_STATUS_MASK                                     = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_10_HEALTH_STATUS_STATUS_SHIFT                                    = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_11_HEALTH_STATUS_STATUS_MASK                                     = 32'hFF;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_11_HEALTH_STATUS_STATUS_SHIFT                                    = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_0_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_0_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_1_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_1_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_2_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_2_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_3_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_3_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_4_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_4_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_5_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_5_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_6_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_6_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_7_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_7_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_8_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_8_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_9_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                       = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_9_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                      = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_10_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                      = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_10_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                     = 0;

localparam int unsigned ENTROPY_SOURCE_GENERATOR_11_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_MASK                      = 32'h1F;
localparam int unsigned ENTROPY_SOURCE_GENERATOR_11_SAMPLE_CLK_CONFIG_SAMPLE_CLK_DIVIDE_SHIFT                     = 0;

localparam int unsigned ENTROPY_SOURCE_HT_WATERMARK_NUM_WATERMARK_NUM_MASK                                        = 32'hF;
localparam int unsigned ENTROPY_SOURCE_HT_WATERMARK_NUM_WATERMARK_NUM_SHIFT                                       = 0;

localparam int unsigned ENTROPY_SOURCE_HT_WATERMARK_WATERMARK_VALUE_MASK                                          = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_HT_WATERMARK_WATERMARK_VALUE_SHIFT                                         = 0;

localparam int unsigned ENTROPY_SOURCE_REPCNT_TOTAL_FAILS_FAIL_COUNT_MASK                                         = 32'hFFFFFFFF;
localparam int unsigned ENTROPY_SOURCE_REPCNT_TOTAL_FAILS_FAIL_COUNT_SHIFT                                        = 0;

localparam int unsigned ENTROPY_SOURCE_APT_HI_TOTAL_FAILS_FAIL_COUNT_MASK                                         = 32'hFFFFFFFF;
localparam int unsigned ENTROPY_SOURCE_APT_HI_TOTAL_FAILS_FAIL_COUNT_SHIFT                                        = 0;

localparam int unsigned ENTROPY_SOURCE_APT_LO_TOTAL_FAILS_FAIL_COUNT_MASK                                         = 32'hFFFFFFFF;
localparam int unsigned ENTROPY_SOURCE_APT_LO_TOTAL_FAILS_FAIL_COUNT_SHIFT                                        = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_HI_TOTAL_FAILS_FAIL_COUNT_MASK                                      = 32'hFFFFFFFF;
localparam int unsigned ENTROPY_SOURCE_MARKOV_HI_TOTAL_FAILS_FAIL_COUNT_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_MARKOV_LO_TOTAL_FAILS_FAIL_COUNT_MASK                                      = 32'hFFFFFFFF;
localparam int unsigned ENTROPY_SOURCE_MARKOV_LO_TOTAL_FAILS_FAIL_COUNT_SHIFT                                     = 0;

localparam int unsigned ENTROPY_SOURCE_ALERT_SUMMARY_FAIL_COUNTS_ANY_FAIL_COUNT_MASK                              = 32'hFFFF;
localparam int unsigned ENTROPY_SOURCE_ALERT_SUMMARY_FAIL_COUNTS_ANY_FAIL_COUNT_SHIFT                             = 0;

localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_APT_LO_FAIL_COUNT_MASK                                   = 32'hF;
localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_APT_LO_FAIL_COUNT_SHIFT                                  = 0;

localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_APT_HI_FAIL_COUNT_MASK                                   = 32'hF0;
localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_APT_HI_FAIL_COUNT_SHIFT                                  = 4;

localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_MARKOV_LO_FAIL_COUNT_MASK                                = 32'hF00;
localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_MARKOV_LO_FAIL_COUNT_SHIFT                               = 8;

localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_MARKOV_HI_FAIL_COUNT_MASK                                = 32'hF000;
localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_MARKOV_HI_FAIL_COUNT_SHIFT                               = 12;

localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_REPCNT_FAIL_COUNT_MASK                                   = 32'hF0000;
localparam int unsigned ENTROPY_SOURCE_ALERT_FAIL_COUNTS_REPCNT_FAIL_COUNT_SHIFT                                  = 16;





typedef struct packed {
    logic [3:0]   major_version ;
    logic [3:0]   minor_version ;
    logic [7:0]   rsvd_0 ;
    logic [15:0]   name ;
} entropy_source_component_id_reg_t;



typedef struct packed {
    logic [0:0]   sha256_whitening_enable ;
    logic [1:0]   rsvd_3 ;
    logic [9:0]   downsample_rate ;
    logic [6:0]   rsvd_2 ;
    logic [0:0]   bypass_entropy_compressor ;
    logic [2:0]   rsvd_1 ;
    logic [0:0]   autotune_enable ;
    logic [2:0]   rsvd_0 ;
    logic [0:0]   reset ;
} entropy_source_ctrl_reg_t;



typedef struct packed {
    logic [0:0]   rsvd ;
} entropy_source_status_reg_t;



typedef struct packed {
    logic [2:0]   select_freq_div ;
    logic [7:0]   select_signal ;
} entropy_source_debug_ctrl_reg_t;



typedef struct packed {
    logic [0:0]   fifo_underflow ;
    logic [2:0]   rsvd_2 ;
    logic [0:0]   fifo_overflow ;
    logic [2:0]   rsvd_1 ;
    logic [0:0]   fifo_error ;
    logic [2:0]   rsvd_0 ;
    logic [0:0]   health_test_failed ;
} entropy_source_intr_status_reg_t;



typedef struct packed {
    logic [0:0]   fifo_underflow ;
    logic [2:0]   rsvd_2 ;
    logic [0:0]   fifo_overflow ;
    logic [2:0]   rsvd_1 ;
    logic [0:0]   fifo_error ;
    logic [2:0]   rsvd_0 ;
    logic [0:0]   health_test_failed ;
} entropy_source_intr_enable_reg_t;



typedef struct packed {
    logic [0:0]   fifo_underflow ;
    logic [2:0]   rsvd_2 ;
    logic [0:0]   fifo_overflow ;
    logic [2:0]   rsvd_1 ;
    logic [0:0]   fifo_error ;
    logic [2:0]   rsvd_0 ;
    logic [0:0]   health_test_failed ;
} entropy_source_intr_test_reg_t;



typedef struct packed {
    logic [2:0]   output_count ;
    logic [3:0]   input_count ;
    logic [2:0]   rsvd_0 ;
    logic [0:0]   busy ;
} entropy_source_sha256_status_reg_t;



typedef struct packed {
    logic [0:0]   entropy_churn_enable ;
    logic [2:0]   rsvd_0 ;
    logic [0:0]   enable ;
} entropy_source_fifo_ctrl_reg_t;



typedef struct packed {
    logic [4:0]   rptr ;
    logic [2:0]   rsvd_1 ;
    logic [4:0]   wptr ;
    logic [0:0]   rsvd_0 ;
    logic [6:0]   level ;
} entropy_source_fifo_status_reg_t;



typedef struct packed {
    logic [31:0]   rdata ;
} entropy_source_fifo_rdata_reg_t;



typedef struct packed {
    logic [7:0]   repetition_limit ;
    logic [7:0]   enable ;
} entropy_source_health_test_ctrl_reg_t;



typedef struct packed {
    logic [15:0]   size ;
} entropy_source_health_test_window_size_reg_t;



typedef struct packed {
    logic [15:0]   prob_10_threshold ;
    logic [15:0]   prob_01_threshold ;
} entropy_source_markov_test_prob_thresholds_reg_t;



typedef struct packed {
    logic [7:0]   health_status ;
} entropy_source_health_test_status_reg_t;



typedef struct packed {
    logic [15:0]   repetition_count ;
} entropy_source_repetition_test_count_reg_t;



typedef struct packed {
    logic [9:0]   samples_processed ;
    logic [3:0]   target_pattern ;
    logic [15:0]   pattern_count ;
} entropy_source_apt_pattern_count_1bit_reg_t;



typedef struct packed {
    logic [9:0]   samples_processed ;
    logic [3:0]   target_pattern ;
    logic [15:0]   pattern_count ;
} entropy_source_apt_pattern_count_2bit_reg_t;



typedef struct packed {
    logic [9:0]   samples_processed ;
    logic [5:0]   rsvd_0 ;
    logic [3:0]   target_pattern ;
    logic [9:0]   pattern_count ;
} entropy_source_apt_pattern_count_3bit_reg_t;



typedef struct packed {
    logic [9:0]   samples_processed ;
    logic [5:0]   rsvd_0 ;
    logic [3:0]   target_pattern ;
    logic [9:0]   pattern_count ;
} entropy_source_apt_pattern_count_4bit_reg_t;



typedef struct packed {
    logic [15:0]   limit ;
} entropy_source_apt_proportion_1bit_reg_t;



typedef struct packed {
    logic [9:0]   limit ;
} entropy_source_apt_proportion_2bit_reg_t;



typedef struct packed {
    logic [9:0]   limit ;
} entropy_source_apt_proportion_3bit_reg_t;



typedef struct packed {
    logic [9:0]   limit ;
} entropy_source_apt_proportion_4bit_reg_t;



typedef struct packed {
    logic [15:0]   count_10 ;
    logic [15:0]   count_01 ;
} entropy_source_markov_test_counts_0_reg_t;



typedef struct packed {
    logic [15:0]   count_11 ;
    logic [15:0]   count_00 ;
} entropy_source_markov_test_counts_1_reg_t;



typedef struct packed {
    logic [7:0]   prob_11 ;
    logic [7:0]   prob_00 ;
    logic [7:0]   prob_10 ;
    logic [7:0]   prob_01 ;
} entropy_source_markov_test_probabilities_reg_t;



typedef struct packed {
    logic [11:0]   sample_clk_enable ;
    logic [11:0]   enable ;
} entropy_source_ring_osc_enable_reg_t;



typedef struct packed {
    logic [11:0]   sample_clk_detune ;
    logic [11:0]   detune ;
} entropy_source_ring_osc_tune_reg_t;



typedef struct packed {
    logic [11:0]   sample_clk_select ;
} entropy_source_ring_osc_ctrl_reg_t;



typedef struct packed {
    logic [19:0]   sample_clk_div ;
    logic [11:0]   bypass ;
} entropy_source_decorrelator_ctrl_reg_t;



typedef struct packed {
    logic [7:0]   entropy_byte_mask ;
} entropy_source_decorrelator_mask_reg_t;



typedef struct packed {
    logic [15:0]   delay_cycles ;
} entropy_source_startup_ctrl_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_0_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_1_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_2_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_3_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_4_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_5_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_6_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_7_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_8_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_9_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_10_health_status_reg_t;



typedef struct packed {
    logic [7:0]   status ;
} entropy_source_generator_11_health_status_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_0_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_1_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_2_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_3_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_4_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_5_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_6_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_7_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_8_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_9_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_10_sample_clk_config_reg_t;



typedef struct packed {
    logic [4:0]   sample_clk_divide ;
} entropy_source_generator_11_sample_clk_config_reg_t;



typedef struct packed {
    logic [3:0]   watermark_num ;
} entropy_source_ht_watermark_num_reg_t;



typedef struct packed {
    logic [15:0]   watermark_value ;
} entropy_source_ht_watermark_reg_t;



typedef struct packed {
    logic [31:0]   fail_count ;
} entropy_source_repcnt_total_fails_reg_t;



typedef struct packed {
    logic [31:0]   fail_count ;
} entropy_source_apt_hi_total_fails_reg_t;



typedef struct packed {
    logic [31:0]   fail_count ;
} entropy_source_apt_lo_total_fails_reg_t;



typedef struct packed {
    logic [31:0]   fail_count ;
} entropy_source_markov_hi_total_fails_reg_t;



typedef struct packed {
    logic [31:0]   fail_count ;
} entropy_source_markov_lo_total_fails_reg_t;



typedef struct packed {
    logic [15:0]   any_fail_count ;
} entropy_source_alert_summary_fail_counts_reg_t;



typedef struct packed {
    logic [3:0]   repcnt_fail_count ;
    logic [3:0]   markov_hi_fail_count ;
    logic [3:0]   markov_lo_fail_count ;
    logic [3:0]   apt_hi_fail_count ;
    logic [3:0]   apt_lo_fail_count ;
} entropy_source_alert_fail_counts_reg_t;




`endif
