/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 

/***************************************************************************
 * Company: example.org
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:7ffdb470a256cfc4fa1ffe82d6ca75adadb2aa25 

#include <pka_modelTestHarness.h>
#include "pka_reg_handler.h"
#include "pka_reg_access.h"
#include <cstdint>
#include <cstring>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#ifdef ACCELLERA_SYSTEMC
#include "Logger.h"
#endif

extern "C" {
#include "pka_driver/pka_sample_apps.h"
}

#ifdef ACCELLERA_SYSTEMC
// Test logger macros (accept stream expressions, convert to string internally)
#undef TEST_LOG_INFO
#undef TEST_LOG_ERROR
#undef TEST_LOG_DEBUG
#undef TEST_LOG_WARNING
#define TEST_LOG_INFO(expr)    do { std::ostringstream _oss; _oss << expr; test_logger.log(utils::logging::Logger::LogLevel::INFO, __FUNCTION__, __LINE__, _oss.str()); } while (0)
#define TEST_LOG_ERROR(expr)   do { std::ostringstream _oss; _oss << expr; test_logger.log(utils::logging::Logger::LogLevel::ERROR, __FUNCTION__, __LINE__, _oss.str()); } while (0)
#define TEST_LOG_DEBUG(expr)   do { std::ostringstream _oss; _oss << expr; test_logger.log(utils::logging::Logger::LogLevel::DEBUG_LEVEL, __FUNCTION__, __LINE__, _oss.str()); } while (0)
#define TEST_LOG_WARNING(expr) do { std::ostringstream _oss; _oss << expr; test_logger.log(utils::logging::Logger::LogLevel::WARNING, __FUNCTION__, __LINE__, _oss.str()); } while (0)


#elif SYNOPSYS_SYSTEMC
using namespace scml2::testing;
#endif

namespace mylibrary {

class pka_modelTest : public pka_modelTestHarness, public PkaRegAccess {
#ifdef SYNOPSYS_SYSTEMC
  // Register the test class and all test methods
  SCML2_BEGIN_TESTS(pka_modelTest);
  SCML2_TEST(testAlwaysSucceeds);
  SCML2_TEST(test_pka_rsa_sign_verify_nist);
  SCML2_TEST(test_pka_rsa_encrypt_decrypt);
  SCML2_TEST(test_pka_ecc_sign_verify_asn1);
  SCML2_TEST(test_pka_ecc_sign_verify_bp_p384r1);
  SCML2_TEST(test_pka_ecc_encrypt_decrypt_bp_p256r1);
  SCML2_TEST(test_pka_ecc_key_agree_nist384);
  SCML2_TEST(test_pka_eddsa_sign_verify);
  SCML2_TEST(test_pka_montg_key_agree);
  SCML2_TEST(test_pka_sm2_sign_verify_256);
  SCML2_TEST(test_pka_sm2_encrypt_decrypt_256);
  SCML2_TEST(test_pka_sm2_key_agree_256);
  SCML2_END_TESTS();

  pka_modelTest() {} // Constructor

  bool read_register(const std::string& reg_name, int addr, uint64_t &cap);
  void write_register(const std::string& reg_name, int address, uint64_t data);
  uint32_t pka_read(uint32_t addr) override;
  void pka_write(uint32_t addr, uint32_t data) override;
  void pka_read_bigint(uint32_t addr, uint8_t *buffer, uint32_t length) override;
  void pka_write_bigint(uint32_t addr, const uint8_t *buffer, uint32_t length) override;
  virtual void do_initialize_test_group() override;
#elif ACCELLERA_SYSTEMC
public:
pka_modelTest(sc_core::sc_module_name name,bool register_thread): pka_modelTestHarness(name)
{
    pka_register_handler(static_cast<PkaRegAccess*>(this));
    if(register_thread)
        SC_THREAD(process_test_case);
}

SC_HAS_PROCESS(pka_modelTest);

  bool read_register(const std::string& reg_name, int addr, uint64_t &cap);
  void write_register(const std::string& reg_name, int address, uint64_t data);
  uint32_t pka_read(uint32_t addr) override;
  void pka_write(uint32_t addr, uint32_t data) override;
  void pka_read_bigint(uint32_t addr, uint8_t *buffer, uint32_t length) override;
  void pka_write_bigint(uint32_t addr, const uint8_t *buffer, uint32_t length) override;

// Thread to test all the testcases (no config - runs all PKA tests with default params)
void process_test_case(){
    static const std::map<std::string, std::string> default_params = {
        {"F_W_MemoryMix", "0"},
        {"F_W_RamMemorySize", "11"},
        {"F_W_RomMemorySize", "11"},
        {"EnableBankswitchA", "1"},
        {"Include_RSA_Functions", "0"}
    };
    this->modelUnderTest->process_params(default_params);

    static const std::vector<std::string> test_names = {
        "testAlwaysSucceeds",
        "test_pka_rsa_sign_verify_nist",
        "test_pka_rsa_encrypt_decrypt",
        "test_pka_ecc_sign_verify_asn1",
        "test_pka_ecc_sign_verify_bp_p384r1",
        "test_pka_ecc_encrypt_decrypt_bp_p256r1",
        "test_pka_ecc_key_agree_nist384",
        "test_pka_eddsa_sign_verify",
        "test_pka_montg_key_agree",
        "test_pka_sm2_sign_verify_256",
        "test_pka_sm2_encrypt_decrypt_256",
        "test_pka_sm2_key_agree_256"
    };

    for (const auto &test : test_names)
    {
        TEST_LOG_INFO("\n\n================================ TEST START: " << test << " ================================");
        setup();
        auto it = testFunctions.find(test);
        if (it != testFunctions.end())
        {
            it->second(); // Call the function
            TEST_LOG_INFO("================================= TEST END: " << test << " =================================");
        }
        else
        {
            TEST_LOG_ERROR("No function found for test: " << test << "\n");
            TEST_LOG_INFO("================================= TEST END: " << test << " =================================");
        }
    }

    std::cout << "\n=====================================================================\n";
    std::cout << "                    Test Cases Executed in This Run\n";
    std::cout << "=====================================================================\n";
    int test_case_counter = 1;
    for (const auto &test : test_names)
    {
        std::cout << "  " << std::dec << test_case_counter << ". " << test << std::endl;
        ++test_case_counter;
    }
    std::cout << "=====================================================================\n\n";
}
#endif 

  ~pka_modelTest() {} // Destructor
  // Override this if you want a customize construction of your model under test // ! Only available when not reusing component build in test
  //virtual pka_model* create_model_under_test(const char* name) { // ! Only available when not reusing component build in test
  //  return new pka_model(name); // ! Only available when not reusing component build in test
  //}

  // Override this if you want to customize construction of your mirror model
  //virtual pka_modelMirrorBase* create_mirror_model(const char* name) {
  //  return new pka_modelMirrorBase(name);
  //}
  #ifdef SYNOPSYS_SYSTEMC
  void do_initialize_test_group() override {
    pka_modelTestHarness::do_initialize_test_group();
    pka_register_handler(static_cast<PkaRegAccess*>(this));
  }
  // initialize is called once at the start of the test run, after the model and
  // the mirror model have been created & connected. Initialize the models further here,
  // set up extra connections, set clock periods, ...
  virtual void initialize() {
  }
  #endif
  // Called before running each testcase
  // Reset your model here.
  virtual void setup() {
  }
  #ifdef SYNOPSYS_SYSTEMC
  // Called after running each testcase
  virtual void teardown() {
  }
  
  // Called at the end of the complete testrun
  virtual void shutdown() {
  }
  #endif
  void testAlwaysSucceeds() {
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(true, "test always succeeds");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(true, "test always succeeds");
    #endif
  }

  void test_pka_rsa_sign_verify_nist() {
    int ret = rsa_sign_verify_nist_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA RSA sign/verify NIST failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA RSA sign/verify NIST failed");
    #endif
  }
  void test_pka_rsa_encrypt_decrypt() {
    int ret = rsa_encrypt_decrypt_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA RSA encrypt/decrypt failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA RSA encrypt/decrypt failed");
    #endif
  }
  void test_pka_ecc_sign_verify_asn1() {
    int ret = ecc_sign_verify_asn1_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA ECC sign/verify ASN1 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA ECC sign/verify ASN1 failed");
    #endif
  }
  void test_pka_ecc_sign_verify_bp_p384r1() {
    int ret = ecc_sign_verify_bp_p384r1_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA ECC sign/verify BP P384R1 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA ECC sign/verify BP P384R1 failed");
    #endif
  }
  void test_pka_ecc_encrypt_decrypt_bp_p256r1() {
    int ret = ecc_encrypt_decrypt_bp_p256r1_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA ECC encrypt/decrypt BP P256R1 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA ECC encrypt/decrypt BP P256R1 failed");
    #endif
  }
  void test_pka_ecc_key_agree_nist384() {
    int ret = ecc_key_agree_nist384_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA ECC key agree NIST384 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA ECC key agree NIST384 failed");
    #endif
  }
  void test_pka_eddsa_sign_verify() {
    int ret = eddsa_sign_verify_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA EdDSA sign/verify failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA EdDSA sign/verify failed");
    #endif
  }
  void test_pka_montg_key_agree() {
    int ret = montg_key_agree_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA Montgomery key agree (X25519) failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA Montgomery key agree (X25519) failed");
    #endif
  }
  void test_pka_sm2_sign_verify_256() {
    int ret = sm2_sign_verify_256_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA SM2 sign/verify 256 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA SM2 sign/verify 256 failed");
    #endif
  }
  void test_pka_sm2_encrypt_decrypt_256() {
    int ret = sm2_encrypt_decrypt_256_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA SM2 encrypt/decrypt 256 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA SM2 encrypt/decrypt 256 failed");
    #endif
  }
  void test_pka_sm2_key_agree_256() {
    int ret = sm2_key_agree_256_main();
    bool ok = (ret == 0);
    #ifdef SYNOPSYS_SYSTEMC
    SCML2_ASSERT_THAT(ok, "PKA SM2 key agree 256 failed");
    #elif ACCELLERA_SYSTEMC
    SCML2_ASSERT_TO(ok, "PKA SM2 key agree 256 failed");
    #endif
  }

  #ifdef ACCELLERA_SYSTEMC
// Logger instances
utils::logging::Logger cache_logger{"test_cache"};
utils::logging::Logger test_logger{"test_main"};

// Register Test Functions here
std::unordered_map<std::string, std::function<void()>> testFunctions = {
        {"testAlwaysSucceeds", [this]() { testAlwaysSucceeds(); }},
        {"test_pka_rsa_sign_verify_nist", [this]() { test_pka_rsa_sign_verify_nist(); }},
        {"test_pka_rsa_encrypt_decrypt", [this]() { test_pka_rsa_encrypt_decrypt(); }},
        {"test_pka_ecc_sign_verify_asn1", [this]() { test_pka_ecc_sign_verify_asn1(); }},
        {"test_pka_ecc_sign_verify_bp_p384r1", [this]() { test_pka_ecc_sign_verify_bp_p384r1(); }},
        {"test_pka_ecc_encrypt_decrypt_bp_p256r1", [this]() { test_pka_ecc_encrypt_decrypt_bp_p256r1(); }},
        {"test_pka_ecc_key_agree_nist384", [this]() { test_pka_ecc_key_agree_nist384(); }},
        {"test_pka_eddsa_sign_verify", [this]() { test_pka_eddsa_sign_verify(); }},
        {"test_pka_montg_key_agree", [this]() { test_pka_montg_key_agree(); }},
        {"test_pka_sm2_sign_verify_256", [this]() { test_pka_sm2_sign_verify_256(); }},
        {"test_pka_sm2_encrypt_decrypt_256", [this]() { test_pka_sm2_encrypt_decrypt_256(); }},
        {"test_pka_sm2_key_agree_256", [this]() { test_pka_sm2_key_agree_256(); }},
    };
#endif

  // TOOL_INSERT_TESTS_HERE - DO NOT REMOVE THIS LINE
};

bool pka_modelTest::read_register(const std::string& reg_name, int addr, uint64_t &cap)
{
    bool OK = mirrorModel->p_mem_socket_mockup.read(addr, cap);
    std::cout << "read_register: " << reg_name << " addr=0x" << std::hex << addr << " cap=0x" << cap << std::dec << " OK=" << OK << std::endl;
    return OK;
}

void pka_modelTest::write_register(const std::string& reg_name, int address, uint64_t data)
{
    std::cout << "write_register: " << reg_name << " addr=0x" << std::hex << address << " data=0x" << data << std::dec << std::endl;
    mirrorModel->p_mem_socket_mockup.write(address, data);
}

uint32_t pka_modelTest::pka_read(uint32_t addr)
{
    uint64_t cap = 0;
    read_register("PKA_REG", static_cast<int>(addr), cap);
    return static_cast<uint32_t>(cap);
}

void pka_modelTest::pka_write(uint32_t addr, uint32_t data)
{
    std::cout << "pka_write: addr=0x" << std::hex << addr << " data=0x" << data << std::dec << std::endl;
    write_register("PKA_REG", static_cast<int>(addr), static_cast<uint64_t>(data));
}

void pka_modelTest::pka_read_bigint(uint32_t addr, uint8_t *buffer, uint32_t length)
{
    unsigned n = length >> 2;
    uint32_t tmp;

    for (unsigned i = 0; i < n; i++) {
        uint64_t cap = 0;
        read_register("PKA_REG", static_cast<int>(addr + i * 4), cap);
        tmp = static_cast<uint32_t>(cap);
        std::memcpy(buffer + ((n - i - 1) << 2) + (length & 3), &tmp, 4);
    }
    if (length & 3) {
        uint64_t cap = 0;
        read_register("PKA_REG", static_cast<int>(addr + n * 4), cap);
        tmp = static_cast<uint32_t>(cap);
        std::memcpy(buffer, reinterpret_cast<char *>(&tmp) + sizeof(tmp) - (length & 3), length & 3);
    }
}

void pka_modelTest::pka_write_bigint(uint32_t addr, const uint8_t *buffer, uint32_t length)
{
    unsigned n = length >> 2;
    uint32_t tmp;

    for (unsigned i = 0; i < n; i++) {
        std::memcpy(&tmp, buffer + ((n - i - 1) << 2) + (length & 3), 4);
        write_register("PKA_REG", static_cast<int>(addr + i * 4), static_cast<uint64_t>(tmp));
    }
    if (length & 3) {
        tmp = 0;
        std::memcpy(reinterpret_cast<char *>(&tmp) + sizeof(tmp) - (length & 3), buffer, length & 3);
        write_register("PKA_REG", static_cast<int>(addr + n * 4), static_cast<uint64_t>(tmp));
    }
}

} // namespace mylibrary

// Main function
#ifdef ACCELLERA_SYSTEMC
int sc_main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;
    mylibrary::pka_modelTest pka_test_ut("pka_test_ut", true);
    sc_start();
    return 0;
}

#elif SYNOPSYS_SYSTEMC
namespace mylibrary {
//SCML2_REGISTER_TEST_GROUP_WITH_PARAMETERS(pka_modelTest, parameter_configurations(parameter_configuration("Default")("F_W_MemoryMix", 0)("F_W_RamMemorySize", 11)("F_W_RomMemorySize", 11)("EnableBankswitchA", 1)("Include_RSA_Functions", 0)));
SCML2_REGISTER_TEST_GROUP(pka_modelTest);

SCML2_TESTING_PORT_TAG(pka_modelTest, p_mem_socket, "TLM2_GP");
} // namespace mylibrary
#endif
