/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Company: example.org
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:1a3ed7c3a468b7a7abb0e876e872a08b03a6d59a 

#pragma once
#include <pka_model.h>
#include <pka_modelMirror.h>

#ifdef SYNOPSYS_SYSTEMC
#include <scml2_testing.h>

#include <pka_modelCovermodel.h>
#include "scml2_protocol_engines/reset/include/reset_engine_proxies.h"
#include "scml2_protocol_engines/interrupt/include/interrupt_engine_proxies.h"
#include "scml2_protocol_engines/tlm2_ft_initiator_port/include/testing/tlm2_ft_initiator_port_peProxyBase.h"
#include <scml2_testing/fb_test_utils.h>

SCML2_FASTBUILD_COVERAGE(::mylibrary::pka_model, "mylibrary::pka_model0", "pka_model" + std::string(::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") ? std::string(",")+::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") : "") + ",../../SystemC/libso-gcc-9.5-64/FastBuild,..;");
#endif

namespace mylibrary {

#ifdef SYNOPSYS_SYSTEMC
class pka_modelTestHarness : public scml2::testing::test_group<::mylibrary::pka_model, pka_modelMirror, scml2::testing::fast_build_covergroup<pka_modelCovermodel > > {
  protected:
    pka_modelTestHarness() 
        : scml2::testing::test_group<::mylibrary::pka_model, pka_modelMirror, scml2::testing::fast_build_covergroup<pka_modelCovermodel > >()
        , F_W_MemoryMix("F_W_MemoryMix", this->get_property_server())
        , F_W_RamMemorySize("F_W_RamMemorySize", this->get_property_server())
        , F_W_RomMemorySize("F_W_RomMemorySize", this->get_property_server())
        , EnableBankswitchA("EnableBankswitchA", this->get_property_server())
        , Include_RSA_Functions("Include_RSA_Functions", this->get_property_server())
        , p_reset()
        , p_intr("p_intr")
        , p_mem_socket("p_mem_socket") {
      
    }
    
    scml2::testing::property_proxy<unsigned int> F_W_MemoryMix;
    scml2::testing::property_proxy<unsigned int> F_W_RamMemorySize;
    scml2::testing::property_proxy<unsigned int> F_W_RomMemorySize;
    scml2::testing::property_proxy<bool> EnableBankswitchA;
    scml2::testing::property_proxy<bool> Include_RSA_Functions;
    sc_core::sc_signal< bool > p_reset_signal;
    scml2::testing::reset_master_engine_proxy p_reset;
    sc_core::sc_signal< bool > p_intr_signal;
    scml2::testing::interrupt_slave_engine_proxy p_intr;
    scml2::tlm2_ft_initiator_port_peProxy<32> p_mem_socket;
  #endif

#ifdef ACCELLERA_SYSTEMC
class pka_modelTestHarness : public sc_core::sc_module {
public:

//use unique ptrs to point to the models
  std::shared_ptr<pka_model> modelUnderTest = std::make_shared<pka_model>("modelUnderTest");
  std::shared_ptr<pka_modelMirror> mirrorModel = std::make_shared<pka_modelMirror>("mirrorModel");

// Internal Signals
sc_signal<bool> p_reset_signal{"p_reset_signal"};
sc_signal<bool> p_intr_signal{"p_intr_signal"};

//Constructor
pka_modelTestHarness(sc_core::sc_module_name name)
  : sc_core::sc_module(name)
{
  // do bindings
  do_initialize_test_group();

  //initialise the constants
  do_initialize_constants();
}

#endif

#ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    /* coverity[member_decl] */
    int CTRL;
    /* coverity[member_decl] */
    int ENTRY_PNT;
    /* coverity[member_decl] */
    int RTN_CODE;
    /* coverity[member_decl] */
    int BUILD_CONFIG;
    /* coverity[member_decl] */
    int STACK_PNTR;
    /* coverity[member_decl] */
    int INSTR_SINCE_GO;
    /* coverity[member_decl] */
    int CONFIG;
    /* coverity[member_decl] */
    int STAT;
    /* coverity[member_decl] */
    int FLAGS;
    /* coverity[member_decl] */
    int WATCHDOG;
    /* coverity[member_decl] */
    int CYCLES_SINCE_GO;
    /* coverity[member_decl] */
    int INDEX_I;
    /* coverity[member_decl] */
    int INDEX_J;
    /* coverity[member_decl] */
    int INDEX_K;
    /* coverity[member_decl] */
    int INDEX_L;
    /* coverity[member_decl] */
    int IRQ_EN;
    /* coverity[member_decl] */
    int JMP_PROB;
    /* coverity[member_decl] */
    int JMP_PROB_LFSR;
    /* coverity[member_decl] */
    int BANK_SW_A;
    /* coverity[member_decl] */
    int BANK_SW_B;
    /* coverity[member_decl] */
    int BANK_SW_C;
    /* coverity[member_decl] */
    int BANK_SW_D;
    virtual void do_initialize_constants() {
      CTRL = 0x0 + 0x0;
      ENTRY_PNT = 0x0 + 0x4;
      RTN_CODE = 0x0 + 0x8;
      BUILD_CONFIG = 0x0 + 0xc;
      STACK_PNTR = 0x0 + 0x10;
      INSTR_SINCE_GO = 0x0 + 0x14;
      CONFIG = 0x0 + 0x1c;
      STAT = 0x0 + 0x20;
      FLAGS = 0x0 + 0x24;
      WATCHDOG = 0x0 + 0x28;
      CYCLES_SINCE_GO = 0x0 + 0x2c;
      INDEX_I = 0x0 + 0x30;
      INDEX_J = 0x0 + 0x34;
      INDEX_K = 0x0 + 0x38;
      INDEX_L = 0x0 + 0x3c;
      IRQ_EN = 0x0 + 0x40;
      JMP_PROB = 0x0 + 0x44;
      JMP_PROB_LFSR = 0x0 + 0x48;
      BANK_SW_A = 0x0 + 0x50;
      BANK_SW_B = 0x0 + 0x54;
      BANK_SW_C = 0x0 + 0x58;
      BANK_SW_D = 0x0 + 0x5c;
    }

#endif

#ifdef SYNOPSYS_SYSTEMC
  protected: 
    virtual void do_initialize_test_group() {
      p_reset.set_target(&this->mirrorModel->p_reset_mockup);
      this->modelUnderTest->p_reset(p_reset_signal);
      this->mirrorModel->p_reset(p_reset_signal);
      p_intr.set_target(&this->mirrorModel->p_intr_mockup);
      this->modelUnderTest->p_intr(p_intr_signal);
      this->mirrorModel->p_intr(p_intr_signal);
      p_mem_socket.set_target(&this->mirrorModel->p_mem_socket_mockup);
      this->mirrorModel->p_mem_socket(this->modelUnderTest->p_mem_socket);
    }
    
    virtual void do_initialize_properties() {
      this->init_param(F_W_MemoryMix, 0);
      this->init_param(F_W_RamMemorySize, 11);
      this->init_param(F_W_RomMemorySize, 11);
      this->init_param(EnableBankswitchA, 1);
      this->init_param(Include_RSA_Functions, 0);
    }

};

#elif ACCELLERA_SYSTEMC
  private:
    // Do all the bindings here
    void do_initialize_test_group()
    {
      mirrorModel->p_mem_socket(modelUnderTest->p_mem_socket);
      modelUnderTest->p_reset(p_reset_signal);
      modelUnderTest->p_intr(p_intr_signal);
      mirrorModel->p_reset(p_reset_signal);
      mirrorModel->p_intr(p_intr_signal);
      
    }
    // initialise any config parameter to default value here
    void initialize_properties()
    {
      mirrorModel->F_W_MemoryMix = 0;
      mirrorModel->F_W_RamMemorySize = 11;
      mirrorModel->F_W_RomMemorySize = 11;
      mirrorModel->EnableBankswitchA = 1;
      mirrorModel->Include_RSA_Functions = 0;
    }
};
#endif


}
