/***************************************************************************
 * Copyright 1996-2024 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Company: example.org
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:8700beae3247c31b880793071add274ed8c94230 

#pragma once

#include <cdns_xspi_ctrl_reg.h>
#include <cdns_xspi_ctrl_regMirror.h>

#ifdef SYNOPSYS_SYSTEMC
#include <scml2_testing.h>
#include <cdns_xspi_ctrl_regCovermodel.h>
#include "scml2_protocol_engines/tlm2_ft_initiator_port/include/testing/tlm2_ft_initiator_port_peProxyBase.h"
#include "scml2_protocol_engines/reset/include/reset_engine_proxies.h"
#include "scml2_protocol_engines/interrupt/include/interrupt_engine_proxies.h"
#include <scml2_testing/fb_test_utils.h>
#endif

#include <vector>
#include <memory>
#include <systemc>

#ifdef SYNOPSYS_SYSTEMC
SCML2_FASTBUILD_COVERAGE(::mylibrary::cdns_xspi_ctrl_reg, "mylibrary::cdns_xspi_ctrl_reg0", "cdns_xspi_ctrl_reg" + std::string(::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") ? std::string(",")+::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") : "") + ",../../SystemC/libso-gcc-9.5-64/FastBuild,..;");
#endif

namespace mylibrary {

#ifdef SYNOPSYS_SYSTEMC

class cdns_xspi_ctrl_regTestHarness : public scml2::testing::test_group<::mylibrary::cdns_xspi_ctrl_reg, cdns_xspi_ctrl_regMirror, scml2::testing::fast_build_covergroup<cdns_xspi_ctrl_regCovermodel > > {
  protected:
    cdns_xspi_ctrl_regTestHarness() 
        : scml2::testing::test_group<::mylibrary::cdns_xspi_ctrl_reg, cdns_xspi_ctrl_regMirror, scml2::testing::fast_build_covergroup<cdns_xspi_ctrl_regCovermodel > >()
        , NUM_TARGETS("NUM_TARGETS", this->get_property_server())
        , t_reg_socket("t_reg_socket")
        , reset_in()
        , int_out("int_out") {
      
    }
    
    scml2::testing::property_proxy<int> NUM_TARGETS;
    scml2::tlm2_ft_initiator_port_peProxy<32> t_reg_socket;
    sc_core::sc_signal< bool > reset_in_signal;
    scml2::testing::reset_master_engine_proxy reset_in;
    scml2::testing::target_socket_proxy<64> t_axi_slave_socket;
    scml2::testing::initiator_socket_proxy<64> i_dma_socket;
    sc_core::sc_signal< bool > int_out_signal;
    scml2::testing::interrupt_slave_engine_proxy int_out;
    scml2::testing::target_socket_proxy<64> PoR_input_signals;
    std::vector< scml2::testing::initiator_socket_proxy<64> > xspi_bus_socket;


#ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    /* coverity[member_decl] */
    int cmd_reg0;
    /* coverity[member_decl] */
    int cmd_reg1;
    /* coverity[member_decl] */
    int cmd_reg2;
    /* coverity[member_decl] */
    int cmd_reg3;
    /* coverity[member_decl] */
    int cmd_reg4;
    /* coverity[member_decl] */
    int cmd_reg5;
    /* coverity[member_decl] */
    int cmd_status_ptr;
    /* coverity[member_decl] */
    int cmd_status;
    /* coverity[member_decl] */
    int ctrl_status;
    /* coverity[member_decl] */
    int trd_status;
    /* coverity[member_decl] */
    int intr_status;
    /* coverity[member_decl] */
    int intr_enable;
    /* coverity[member_decl] */
    int trd_comp_intr_status;
    /* coverity[member_decl] */
    int trd_error_intr_status;
    /* coverity[member_decl] */
    int trd_error_intr_en;
    /* coverity[member_decl] */
    int dma_target_error_l;
    /* coverity[member_decl] */
    int dma_target_error_h;
    /* coverity[member_decl] */
    int boot_status;
    /* coverity[member_decl] */
    int long_polling;
    /* coverity[member_decl] */
    int short_polling;
    /* coverity[member_decl] */
    int ctrl_config;
    /* coverity[member_decl] */
    int dma_settings;
    /* coverity[member_decl] */
    int sdma_size;
    /* coverity[member_decl] */
    int sdma_trd_info;
    /* coverity[member_decl] */
    int sdma_addr0;
    /* coverity[member_decl] */
    int sdma_addr1;
    /* coverity[member_decl] */
    int discovery_control;
    /* coverity[member_decl] */
    int xip_mode_cfg;
    /* coverity[member_decl] */
    int global_seq_cfg;
    /* coverity[member_decl] */
    int global_seq_cfg_1;
    /* coverity[member_decl] */
    int direct_access_cfg;
    /* coverity[member_decl] */
    int direct_access_rmp;
    /* coverity[member_decl] */
    int direct_access_rmp_1;
    /* coverity[member_decl] */
    int rst_seq_cfg_0;
    /* coverity[member_decl] */
    int rst_seq_cfg_1;
    /* coverity[member_decl] */
    int ers_seq_cfg_0;
    /* coverity[member_decl] */
    int ers_seq_cfg_1;
    /* coverity[member_decl] */
    int ers_seq_cfg_2;
    /* coverity[member_decl] */
    int prog_seq_cfg_0;
    /* coverity[member_decl] */
    int prog_seq_cfg_1;
    /* coverity[member_decl] */
    int prog_seq_cfg_2;
    /* coverity[member_decl] */
    int read_seq_cfg_0;
    /* coverity[member_decl] */
    int read_seq_cfg_1;
    /* coverity[member_decl] */
    int read_seq_cfg_2;
    /* coverity[member_decl] */
    int we_seq_cfg_0;
    /* coverity[member_decl] */
    int stat_seq_cfg_0;
    /* coverity[member_decl] */
    int stat_seq_cfg_1;
    /* coverity[member_decl] */
    int stat_seq_cfg_2;
    /* coverity[member_decl] */
    int stat_seq_cfg_3;
    /* coverity[member_decl] */
    int stat_seq_cfg_4;
    /* coverity[member_decl] */
    int stat_seq_cfg_5;
    /* coverity[member_decl] */
    int stat_seq_cfg_7;
    /* coverity[member_decl] */
    int stat_seq_cfg_8;
    /* coverity[member_decl] */
    int stat_seq_cfg_9;
    /* coverity[member_decl] */
    int stat_seq_cfg_10;
    /* coverity[member_decl] */
    int xspi_ctrl_version;
    /* coverity[member_decl] */
    int ctrl_features_reg;
    /* coverity[member_decl] */
    int wp_settings;
    /* coverity[member_decl] */
    int reset_pin_settings;
    /* coverity[member_decl] */
    int clock_mode_settings;
    /* coverity[member_decl] */
    int jedec_rst_timing_reg;
    /* coverity[member_decl] */
    int dev_delay_reg;
    /* coverity[member_decl] */
    int rst_recovery_reg;
    /* coverity[member_decl] */
    int dev_active_max_reg;
    /* coverity[member_decl] */
    int hf_offset_reg;
    /* coverity[member_decl] */
    int dll_phy_update_cnt;
    /* coverity[member_decl] */
    int dll_phy_ctrl;
    /* coverity[member_decl] */
    int phy_dq_timing_reg;
    /* coverity[member_decl] */
    int phy_dqs_timing_reg;
    /* coverity[member_decl] */
    int phy_gate_lpbk_ctrl_reg;
    /* coverity[member_decl] */
    int phy_dll_master_ctrl_reg;
    /* coverity[member_decl] */
    int phy_dll_slave_ctrl_reg;
    /* coverity[member_decl] */
    int phy_ie_timing_reg;
    /* coverity[member_decl] */
    int phy_obs_reg_0;
    /* coverity[member_decl] */
    int phy_dll_obs_reg_0;
    /* coverity[member_decl] */
    int phy_dll_obs_reg_1;
    /* coverity[member_decl] */
    int phy_static_togg_reg;
    /* coverity[member_decl] */
    int phy_wr_deskew_pd_ctrl_0_reg;
    /* coverity[member_decl] */
    int phy_version_reg;
    /* coverity[member_decl] */
    int phy_features_reg;
    /* coverity[member_decl] */
    int phy_ctrl_reg;
    /* coverity[member_decl] */
    int phy_tsel_reg;
    /* coverity[member_decl] */
    int phy_gpio_ctrl_0;
    /* coverity[member_decl] */
    int phy_gpio_ctrl_1;
    /* coverity[member_decl] */
    int phy_gpio_status_0;
    /* coverity[member_decl] */
    int phy_gpio_status_1;
    virtual void do_initialize_constants() {
      cmd_reg0 = 0x0 + 0x0;
      cmd_reg1 = 0x0 + 0x4;
      cmd_reg2 = 0x0 + 0x8;
      cmd_reg3 = 0x0 + 0xc;
      cmd_reg4 = 0x0 + 0x10;
      cmd_reg5 = 0x0 + 0x14;
      cmd_status_ptr = 0x0 + 0x40;
      cmd_status = 0x0 + 0x44;
      ctrl_status = 0x0 + 0x100;
      trd_status = 0x0 + 0x104;
      intr_status = 0x0 + 0x110;
      intr_enable = 0x0 + 0x114;
      trd_comp_intr_status = 0x0 + 0x120;
      trd_error_intr_status = 0x0 + 0x130;
      trd_error_intr_en = 0x0 + 0x134;
      dma_target_error_l = 0x0 + 0x150;
      dma_target_error_h = 0x0 + 0x154;
      boot_status = 0x0 + 0x158;
      long_polling = 0x200 + 0x8;
      short_polling = 0x200 + 0xc;
      ctrl_config = 0x200 + 0x30;
      dma_settings = 0x200 + 0x3c;
      sdma_size = 0x200 + 0x40;
      sdma_trd_info = 0x200 + 0x44;
      sdma_addr0 = 0x200 + 0x4c;
      sdma_addr1 = 0x200 + 0x50;
      discovery_control = 0x200 + 0x60;
      xip_mode_cfg = 0x380 + 0x8;
      global_seq_cfg = 0x380 + 0x10;
      global_seq_cfg_1 = 0x380 + 0x14;
      direct_access_cfg = 0x380 + 0x18;
      direct_access_rmp = 0x380 + 0x1c;
      direct_access_rmp_1 = 0x380 + 0x20;
      rst_seq_cfg_0 = 0x400 + 0x0;
      rst_seq_cfg_1 = 0x400 + 0x4;
      ers_seq_cfg_0 = 0x400 + 0x10;
      ers_seq_cfg_1 = 0x400 + 0x14;
      ers_seq_cfg_2 = 0x400 + 0x18;
      prog_seq_cfg_0 = 0x400 + 0x20;
      prog_seq_cfg_1 = 0x400 + 0x24;
      prog_seq_cfg_2 = 0x400 + 0x28;
      read_seq_cfg_0 = 0x400 + 0x30;
      read_seq_cfg_1 = 0x400 + 0x34;
      read_seq_cfg_2 = 0x400 + 0x38;
      we_seq_cfg_0 = 0x400 + 0x40;
      stat_seq_cfg_0 = 0x400 + 0x50;
      stat_seq_cfg_1 = 0x400 + 0x54;
      stat_seq_cfg_2 = 0x400 + 0x58;
      stat_seq_cfg_3 = 0x400 + 0x5c;
      stat_seq_cfg_4 = 0x400 + 0x60;
      stat_seq_cfg_5 = 0x400 + 0x64;
      stat_seq_cfg_7 = 0x400 + 0x6c;
      stat_seq_cfg_8 = 0x400 + 0x70;
      stat_seq_cfg_9 = 0x400 + 0x74;
      stat_seq_cfg_10 = 0x400 + 0x78;
      xspi_ctrl_version = 0xf00 + 0x0;
      ctrl_features_reg = 0xf00 + 0x4;
      wp_settings = 0x1000 + 0x0;
      reset_pin_settings = 0x1000 + 0x4;
      clock_mode_settings = 0x1000 + 0x8;
      jedec_rst_timing_reg = 0x1000 + 0xc;
      dev_delay_reg = 0x1000 + 0x10;
      rst_recovery_reg = 0x1000 + 0x14;
      dev_active_max_reg = 0x1000 + 0x18;
      hf_offset_reg = 0x1000 + 0x20;
      dll_phy_update_cnt = 0x1000 + 0x30;
      dll_phy_ctrl = 0x1000 + 0x34;
      phy_dq_timing_reg = 0x2000 + 0x0;
      phy_dqs_timing_reg = 0x2000 + 0x4;
      phy_gate_lpbk_ctrl_reg = 0x2000 + 0x8;
      phy_dll_master_ctrl_reg = 0x2000 + 0xc;
      phy_dll_slave_ctrl_reg = 0x2000 + 0x10;
      phy_ie_timing_reg = 0x2000 + 0x14;
      phy_obs_reg_0 = 0x2000 + 0x18;
      phy_dll_obs_reg_0 = 0x2000 + 0x1c;
      phy_dll_obs_reg_1 = 0x2000 + 0x20;
      phy_static_togg_reg = 0x2000 + 0x28;
      phy_wr_deskew_pd_ctrl_0_reg = 0x2000 + 0x34;
      phy_version_reg = 0x2000 + 0x70;
      phy_features_reg = 0x2000 + 0x74;
      phy_ctrl_reg = 0x2080 + 0x0;
      phy_tsel_reg = 0x2080 + 0x4;
      phy_gpio_ctrl_0 = 0x2080 + 0x8;
      phy_gpio_ctrl_1 = 0x2080 + 0xc;
      phy_gpio_status_0 = 0x2080 + 0x10;
      phy_gpio_status_1 = 0x2080 + 0x14;
    }

#endif

  protected: 
    virtual void do_initialize_test_group() {
      t_reg_socket.set_target(&this->mirrorModel->t_reg_socket_mockup);
      this->mirrorModel->t_reg_socket(this->modelUnderTest->t_reg_socket);
      reset_in.set_target(&this->mirrorModel->reset_in_mockup);
      this->modelUnderTest->reset_in(reset_in_signal);
      this->mirrorModel->reset_in(reset_in_signal);
      t_axi_slave_socket.set_target(&this->mirrorModel->t_axi_slave_socket);
      this->modelUnderTest->t_axi_slave_socket(this->mirrorModel->t_axi_slave_socket);
      i_dma_socket.set_target(&this->mirrorModel->i_dma_socket);
      this->modelUnderTest->i_dma_socket(this->mirrorModel->i_dma_socket);
      int_out.set_target(&this->mirrorModel->int_out_mockup);
      this->modelUnderTest->int_out(int_out_signal);
      this->mirrorModel->int_out(int_out_signal);
      PoR_input_signals.set_target(&this->mirrorModel->PoR_input_signals);
      this->modelUnderTest->PoR_input_signals(this->mirrorModel->PoR_input_signals);
      xspi_bus_socket.resize(NUM_TARGETS);

      for (size_t i = 0; i < (size_t)(NUM_TARGETS); ++i) {
        //xspi_bus_socket[i].set_target(&this->mirrorModel->xspi_bus_socket[i]);
        this->modelUnderTest->xspi_bus_socket[i](this->mirrorModel->xspi_bus_socket[i]);
      }
    }
    
    virtual void do_initialize_properties() {
      this->init_param(NUM_TARGETS, 1);
    }

};

#elif ACCELLERA_SYSTEMC

class cdns_xspi_ctrl_regTestHarness : public sc_core::sc_module {
public:

  // Use shared ptrs to point to the models
  std::shared_ptr<mylibrary::cdns_xspi_ctrl_reg> modelUnderTest = std::make_shared<mylibrary::cdns_xspi_ctrl_reg>("modelUnderTest");
  std::shared_ptr<mylibrary::cdns_xspi_ctrl_regMirror> mirrorModel = std::make_shared<mylibrary::cdns_xspi_ctrl_regMirror>("mirrorModel");

  // Internal signals
  sc_core::sc_signal<bool> reset_in_signal{"reset_in_signal"};
  sc_core::sc_signal<bool> int_out_signal{"int_out_signal"};

  // Constructor
  cdns_xspi_ctrl_regTestHarness(sc_core::sc_module_name name)
    : sc_core::sc_module(name)
  {
    // Do the bindings
    do_initialize_test_group();
    
    // Initialize the constants
    #ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    do_initialize_constants();
    #endif
  }

#ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    /* coverity[member_decl] */
    int cmd_reg0;
    /* coverity[member_decl] */
    int cmd_reg1;
    /* coverity[member_decl] */
    int cmd_reg2;
    /* coverity[member_decl] */
    int cmd_reg3;
    /* coverity[member_decl] */
    int cmd_reg4;
    /* coverity[member_decl] */
    int cmd_reg5;
    /* coverity[member_decl] */
    int cmd_status_ptr;
    /* coverity[member_decl] */
    int cmd_status;
    /* coverity[member_decl] */
    int ctrl_status;
    /* coverity[member_decl] */
    int trd_status;
    /* coverity[member_decl] */
    int intr_status;
    /* coverity[member_decl] */
    int intr_enable;
    /* coverity[member_decl] */
    int trd_comp_intr_status;
    /* coverity[member_decl] */
    int trd_error_intr_status;
    /* coverity[member_decl] */
    int trd_error_intr_en;
    /* coverity[member_decl] */
    int dma_target_error_l;
    /* coverity[member_decl] */
    int dma_target_error_h;
    /* coverity[member_decl] */
    int boot_status;
    /* coverity[member_decl] */
    int long_polling;
    /* coverity[member_decl] */
    int short_polling;
    /* coverity[member_decl] */
    int ctrl_config;
    /* coverity[member_decl] */
    int dma_settings;
    /* coverity[member_decl] */
    int sdma_size;
    /* coverity[member_decl] */
    int sdma_trd_info;
    /* coverity[member_decl] */
    int sdma_addr0;
    /* coverity[member_decl] */
    int sdma_addr1;
    /* coverity[member_decl] */
    int discovery_control;
    /* coverity[member_decl] */
    int xip_mode_cfg;
    /* coverity[member_decl] */
    int global_seq_cfg;
    /* coverity[member_decl] */
    int global_seq_cfg_1;
    /* coverity[member_decl] */
    int direct_access_cfg;
    /* coverity[member_decl] */
    int direct_access_rmp;
    /* coverity[member_decl] */
    int direct_access_rmp_1;
    /* coverity[member_decl] */
    int rst_seq_cfg_0;
    /* coverity[member_decl] */
    int rst_seq_cfg_1;
    /* coverity[member_decl] */
    int ers_seq_cfg_0;
    /* coverity[member_decl] */
    int ers_seq_cfg_1;
    /* coverity[member_decl] */
    int ers_seq_cfg_2;
    /* coverity[member_decl] */
    int prog_seq_cfg_0;
    /* coverity[member_decl] */
    int prog_seq_cfg_1;
    /* coverity[member_decl] */
    int prog_seq_cfg_2;
    /* coverity[member_decl] */
    int read_seq_cfg_0;
    /* coverity[member_decl] */
    int read_seq_cfg_1;
    /* coverity[member_decl] */
    int read_seq_cfg_2;
    /* coverity[member_decl] */
    int we_seq_cfg_0;
    /* coverity[member_decl] */
    int stat_seq_cfg_0;
    /* coverity[member_decl] */
    int stat_seq_cfg_1;
    /* coverity[member_decl] */
    int stat_seq_cfg_2;
    /* coverity[member_decl] */
    int stat_seq_cfg_3;
    /* coverity[member_decl] */
    int stat_seq_cfg_4;
    /* coverity[member_decl] */
    int stat_seq_cfg_5;
    /* coverity[member_decl] */
    int stat_seq_cfg_7;
    /* coverity[member_decl] */
    int stat_seq_cfg_8;
    /* coverity[member_decl] */
    int stat_seq_cfg_9;
    /* coverity[member_decl] */
    int stat_seq_cfg_10;
    /* coverity[member_decl] */
    int xspi_ctrl_version;
    /* coverity[member_decl] */
    int ctrl_features_reg;
    /* coverity[member_decl] */
    int wp_settings;
    /* coverity[member_decl] */
    int reset_pin_settings;
    /* coverity[member_decl] */
    int clock_mode_settings;
    /* coverity[member_decl] */
    int jedec_rst_timing_reg;
    /* coverity[member_decl] */
    int dev_delay_reg;
    /* coverity[member_decl] */
    int rst_recovery_reg;
    /* coverity[member_decl] */
    int dev_active_max_reg;
    /* coverity[member_decl] */
    int hf_offset_reg;
    /* coverity[member_decl] */
    int dll_phy_update_cnt;
    /* coverity[member_decl] */
    int dll_phy_ctrl;
    /* coverity[member_decl] */
    int phy_dq_timing_reg;
    /* coverity[member_decl] */
    int phy_dqs_timing_reg;
    /* coverity[member_decl] */
    int phy_gate_lpbk_ctrl_reg;
    /* coverity[member_decl] */
    int phy_dll_master_ctrl_reg;
    /* coverity[member_decl] */
    int phy_dll_slave_ctrl_reg;
    /* coverity[member_decl] */
    int phy_ie_timing_reg;
    /* coverity[member_decl] */
    int phy_obs_reg_0;
    /* coverity[member_decl] */
    int phy_dll_obs_reg_0;
    /* coverity[member_decl] */
    int phy_dll_obs_reg_1;
    /* coverity[member_decl] */
    int phy_static_togg_reg;
    /* coverity[member_decl] */
    int phy_wr_deskew_pd_ctrl_0_reg;
    /* coverity[member_decl] */
    int phy_version_reg;
    /* coverity[member_decl] */
    int phy_features_reg;
    /* coverity[member_decl] */
    int phy_ctrl_reg;
    /* coverity[member_decl] */
    int phy_tsel_reg;
    /* coverity[member_decl] */
    int phy_gpio_ctrl_0;
    /* coverity[member_decl] */
    int phy_gpio_ctrl_1;
    /* coverity[member_decl] */
    int phy_gpio_status_0;
    /* coverity[member_decl] */
    int phy_gpio_status_1;
#endif

  private:
    void do_initialize_test_group()
    {
      // Connect register socket
      mirrorModel->t_reg_socket(modelUnderTest->t_reg_socket);
      
      // Connect reset signal
      modelUnderTest->reset_in(reset_in_signal);
      mirrorModel->reset_in(reset_in_signal);
      
      // Connect interrupt signal
      modelUnderTest->int_out(int_out_signal);
      mirrorModel->int_out(int_out_signal);
      
      // Connect AXI slave socket
      modelUnderTest->t_axi_slave_socket(mirrorModel->t_axi_slave_socket);
      
      // Connect DMA socket (note: lowercase 'i' in i_dma_socket)
      modelUnderTest->i_dma_socket(mirrorModel->i_dma_socket);
      
      // Connect PoR input signals
      modelUnderTest->PoR_input_signals(mirrorModel->PoR_input_signals);
      
      // Connect XSPI bus sockets (note: xspi_bus_socket, not xspi_master_socket)
      // Assuming single target for now, but should handle vector properly
      if (modelUnderTest->xspi_bus_socket.size() > 0 && mirrorModel->xspi_bus_socket.size() > 0) {
        for (size_t i = 0; i < modelUnderTest->xspi_bus_socket.size() && i < mirrorModel->xspi_bus_socket.size(); ++i) {
          modelUnderTest->xspi_bus_socket[i](mirrorModel->xspi_bus_socket[i]);
        }
      }
    }
    
    void initialize_properties()
    {
      mirrorModel->NUM_TARGETS = 1;
    }
    
    #ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    void do_initialize_constants() {
      cmd_reg0 = 0x0 + 0x0;
      cmd_reg1 = 0x0 + 0x4;
      cmd_reg2 = 0x0 + 0x8;
      cmd_reg3 = 0x0 + 0xc;
      cmd_reg4 = 0x0 + 0x10;
      cmd_reg5 = 0x0 + 0x14;
      cmd_status_ptr = 0x0 + 0x40;
      cmd_status = 0x0 + 0x44;
      ctrl_status = 0x0 + 0x100;
      trd_status = 0x0 + 0x104;
      intr_status = 0x0 + 0x110;
      intr_enable = 0x0 + 0x114;
      trd_comp_intr_status = 0x0 + 0x120;
      trd_error_intr_status = 0x0 + 0x130;
      trd_error_intr_en = 0x0 + 0x134;
      dma_target_error_l = 0x0 + 0x150;
      dma_target_error_h = 0x0 + 0x154;
      boot_status = 0x0 + 0x158;
      long_polling = 0x200 + 0x8;
      short_polling = 0x200 + 0xc;
      ctrl_config = 0x200 + 0x30;
      dma_settings = 0x200 + 0x3c;
      sdma_size = 0x200 + 0x40;
      sdma_trd_info = 0x200 + 0x44;
      sdma_addr0 = 0x200 + 0x4c;
      sdma_addr1 = 0x200 + 0x50;
      discovery_control = 0x200 + 0x60;
      xip_mode_cfg = 0x380 + 0x8;
      global_seq_cfg = 0x380 + 0x10;
      global_seq_cfg_1 = 0x380 + 0x14;
      direct_access_cfg = 0x380 + 0x18;
      direct_access_rmp = 0x380 + 0x1c;
      direct_access_rmp_1 = 0x380 + 0x20;
      rst_seq_cfg_0 = 0x400 + 0x0;
      rst_seq_cfg_1 = 0x400 + 0x4;
      ers_seq_cfg_0 = 0x400 + 0x10;
      ers_seq_cfg_1 = 0x400 + 0x14;
      ers_seq_cfg_2 = 0x400 + 0x18;
      prog_seq_cfg_0 = 0x400 + 0x20;
      prog_seq_cfg_1 = 0x400 + 0x24;
      prog_seq_cfg_2 = 0x400 + 0x28;
      read_seq_cfg_0 = 0x400 + 0x30;
      read_seq_cfg_1 = 0x400 + 0x34;
      read_seq_cfg_2 = 0x400 + 0x38;
      we_seq_cfg_0 = 0x400 + 0x40;
      stat_seq_cfg_0 = 0x400 + 0x50;
      stat_seq_cfg_1 = 0x400 + 0x54;
      stat_seq_cfg_2 = 0x400 + 0x58;
      stat_seq_cfg_3 = 0x400 + 0x5c;
      stat_seq_cfg_4 = 0x400 + 0x60;
      stat_seq_cfg_5 = 0x400 + 0x64;
      stat_seq_cfg_7 = 0x400 + 0x6c;
      stat_seq_cfg_8 = 0x400 + 0x70;
      stat_seq_cfg_9 = 0x400 + 0x74;
      stat_seq_cfg_10 = 0x400 + 0x78;
      xspi_ctrl_version = 0xf00 + 0x0;
      ctrl_features_reg = 0xf00 + 0x4;
      wp_settings = 0x1000 + 0x0;
      reset_pin_settings = 0x1000 + 0x4;
      clock_mode_settings = 0x1000 + 0x8;
      jedec_rst_timing_reg = 0x1000 + 0xc;
      dev_delay_reg = 0x1000 + 0x10;
      rst_recovery_reg = 0x1000 + 0x14;
      dev_active_max_reg = 0x1000 + 0x18;
      hf_offset_reg = 0x1000 + 0x20;
      dll_phy_update_cnt = 0x1000 + 0x30;
      dll_phy_ctrl = 0x1000 + 0x34;
      phy_dq_timing_reg = 0x2000 + 0x0;
      phy_dqs_timing_reg = 0x2000 + 0x4;
      phy_gate_lpbk_ctrl_reg = 0x2000 + 0x8;
      phy_dll_master_ctrl_reg = 0x2000 + 0xc;
      phy_dll_slave_ctrl_reg = 0x2000 + 0x10;
      phy_ie_timing_reg = 0x2000 + 0x14;
      phy_obs_reg_0 = 0x2000 + 0x18;
      phy_dll_obs_reg_0 = 0x2000 + 0x1c;
      phy_dll_obs_reg_1 = 0x2000 + 0x20;
      phy_static_togg_reg = 0x2000 + 0x28;
      phy_wr_deskew_pd_ctrl_0_reg = 0x2000 + 0x34;
      phy_version_reg = 0x2000 + 0x70;
      phy_features_reg = 0x2000 + 0x74;
      phy_ctrl_reg = 0x2080 + 0x0;
      phy_tsel_reg = 0x2080 + 0x4;
      phy_gpio_ctrl_0 = 0x2080 + 0x8;
      phy_gpio_ctrl_1 = 0x2080 + 0xc;
      phy_gpio_status_0 = 0x2080 + 0x10;
      phy_gpio_status_1 = 0x2080 + 0x14;
    }
    #endif
};
#endif

}
