// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package output_remap_reg_pkg;

    localparam OUTPUT_REMAP_REG_DATA_WIDTH = 64;
    localparam OUTPUT_REMAP_REG_MIN_ADDR_WIDTH = 4;
    localparam OUTPUT_REMAP_REG_SIZE = 'h8;

    typedef struct {
        logic [55:0] value;
    } output_remap__output_remap_region__REGION_ATTRS__offset__out_t;

    typedef struct {
        output_remap__output_remap_region__REGION_ATTRS__offset__out_t offset;
    } output_remap__output_remap_region__REGION_ATTRS__out_t;

    typedef struct {
        output_remap__output_remap_region__REGION_ATTRS__out_t region_attrs;
    } output_remap__output_remap_region__out_t;

    typedef struct {
        output_remap__output_remap_region__out_t REGION;
    } output_remap__out_t;
endpackage
