#include "sep_efuse_basetest.h"

// Full register map for the combined sep_efuse model.
// Shadow (0x000-0x3FC), INTERFACE_CTRL (0x400-0x418), EFUSE_MMR (0x500-0x56C).
sep_efuse_basetest::Register_Property_t reg_map[] = {
    // Shadow registers
    {sep_efuse_basetest::LOCKS_LO_OFFSET,              sep_efuse_basetest::LOCKS_LO_READ,              sep_efuse_basetest::LOCKS_LO_WRITE,              sep_efuse_basetest::LOCKS_LO_RESET,              "LOCKS_LO"},
    {sep_efuse_basetest::LOCKS_HI_OFFSET,              sep_efuse_basetest::LOCKS_HI_READ,              sep_efuse_basetest::LOCKS_HI_WRITE,              sep_efuse_basetest::LOCKS_HI_RESET,              "LOCKS_HI"},
    {sep_efuse_basetest::LC_STATE_OFFSET,              sep_efuse_basetest::LC_STATE_READ,              sep_efuse_basetest::LC_STATE_WRITE,              sep_efuse_basetest::LC_STATE_RESET,              "LC_STATE"},
    {sep_efuse_basetest::SBOOT_DIS_OFFSET,             sep_efuse_basetest::SBOOT_DIS_READ,             sep_efuse_basetest::SBOOT_DIS_WRITE,             sep_efuse_basetest::SBOOT_DIS_RESET,             "SBOOT_DIS"},
    {sep_efuse_basetest::TRANSIENT_RMA_EN_OFFSET,      sep_efuse_basetest::TRANSIENT_RMA_EN_READ,      sep_efuse_basetest::TRANSIENT_RMA_EN_WRITE,      sep_efuse_basetest::TRANSIENT_RMA_EN_RESET,      "TRANSIENT_RMA_EN"},
    {sep_efuse_basetest::SIP_DIS_LO_OFFSET,            sep_efuse_basetest::SIP_DIS_LO_READ,            sep_efuse_basetest::SIP_DIS_LO_WRITE,            sep_efuse_basetest::SIP_DIS_LO_RESET,            "SIP_DIS_LO"},
    {sep_efuse_basetest::SIP_DIS_HI_OFFSET,            sep_efuse_basetest::SIP_DIS_HI_READ,            sep_efuse_basetest::SIP_DIS_HI_WRITE,            sep_efuse_basetest::SIP_DIS_HI_RESET,            "SIP_DIS_HI"},
    {sep_efuse_basetest::SYS_DIS_LO_OFFSET,            sep_efuse_basetest::SYS_DIS_LO_READ,            sep_efuse_basetest::SYS_DIS_LO_WRITE,            sep_efuse_basetest::SYS_DIS_LO_RESET,            "SYS_DIS_LO"},
    {sep_efuse_basetest::SYS_DIS_HI_OFFSET,            sep_efuse_basetest::SYS_DIS_HI_READ,            sep_efuse_basetest::SYS_DIS_HI_WRITE,            sep_efuse_basetest::SYS_DIS_HI_RESET,            "SYS_DIS_HI"},
    {sep_efuse_basetest::RMA_SIP_TOKEN_OFFSET,         sep_efuse_basetest::RMA_SIP_TOKEN_READ,         sep_efuse_basetest::RMA_SIP_TOKEN_WRITE,         sep_efuse_basetest::RMA_SIP_TOKEN_RESET,         "RMA_SIP_TOKEN"},
    {sep_efuse_basetest::RMA_CHIPLET_TOKEN_OFFSET,     sep_efuse_basetest::RMA_CHIPLET_TOKEN_READ,     sep_efuse_basetest::RMA_CHIPLET_TOKEN_WRITE,     sep_efuse_basetest::RMA_CHIPLET_TOKEN_RESET,     "RMA_CHIPLET_TOKEN"},
    {sep_efuse_basetest::CLASS_KEY_OFFSET,             sep_efuse_basetest::CLASS_KEY_READ,             sep_efuse_basetest::CLASS_KEY_WRITE,             sep_efuse_basetest::CLASS_KEY_RESET,             "CLASS_KEY"},
    {sep_efuse_basetest::CHIPLET_PUBK_REVOKE_OFFSET,   sep_efuse_basetest::CHIPLET_PUBK_REVOKE_READ,   sep_efuse_basetest::CHIPLET_PUBK_REVOKE_WRITE,   sep_efuse_basetest::CHIPLET_PUBK_REVOKE_RESET,   "CHIPLET_PUBK_REVOKE"},
    {sep_efuse_basetest::BL1_VERSION_OFFSET,           sep_efuse_basetest::BL1_VERSION_READ,           sep_efuse_basetest::BL1_VERSION_WRITE,           sep_efuse_basetest::BL1_VERSION_RESET,           "BL1_VERSION"},
    {sep_efuse_basetest::BL2_VERSION_OFFSET,           sep_efuse_basetest::BL2_VERSION_READ,           sep_efuse_basetest::BL2_VERSION_WRITE,           sep_efuse_basetest::BL2_VERSION_RESET,           "BL2_VERSION"},
    {sep_efuse_basetest::CHIPLET_UID_OFFSET,           sep_efuse_basetest::CHIPLET_UID_READ,           sep_efuse_basetest::CHIPLET_UID_WRITE,           sep_efuse_basetest::CHIPLET_UID_RESET,           "CHIPLET_UID"},
    {sep_efuse_basetest::SIP_PUBK_OFFSET,              sep_efuse_basetest::SIP_PUBK_READ,              sep_efuse_basetest::SIP_PUBK_WRITE,              sep_efuse_basetest::SIP_PUBK_RESET,              "SIP_PUBK"},
    {sep_efuse_basetest::SIP_UID_OFFSET,               sep_efuse_basetest::SIP_UID_READ,               sep_efuse_basetest::SIP_UID_WRITE,               sep_efuse_basetest::SIP_UID_RESET,               "SIP_UID"},
    {sep_efuse_basetest::SYS_PUBK_OFFSET,              sep_efuse_basetest::SYS_PUBK_READ,              sep_efuse_basetest::SYS_PUBK_WRITE,              sep_efuse_basetest::SYS_PUBK_RESET,              "SYS_PUBK"},
    {sep_efuse_basetest::SYS_UID_OFFSET,               sep_efuse_basetest::SYS_UID_READ,               sep_efuse_basetest::SYS_UID_WRITE,               sep_efuse_basetest::SYS_UID_RESET,               "SYS_UID"},
    {sep_efuse_basetest::STATUS_RPT_OFFSET,            sep_efuse_basetest::STATUS_RPT_READ,            sep_efuse_basetest::STATUS_RPT_WRITE,            sep_efuse_basetest::STATUS_RPT_RESET,            "STATUS_RPT"},
    {sep_efuse_basetest::SEP_ROM_CTRL_OFFSET,          sep_efuse_basetest::SEP_ROM_CTRL_READ,          sep_efuse_basetest::SEP_ROM_CTRL_WRITE,          sep_efuse_basetest::SEP_ROM_CTRL_RESET,          "SEP_ROM_CTRL"},
    {sep_efuse_basetest::SEP_SPI_CTRL_FIELD_EN_OFFSET, sep_efuse_basetest::SEP_SPI_CTRL_FIELD_EN_READ, sep_efuse_basetest::SEP_SPI_CTRL_FIELD_EN_WRITE, sep_efuse_basetest::SEP_SPI_CTRL_FIELD_EN_RESET, "SEP_SPI_CTRL_FIELD_EN"},
    {sep_efuse_basetest::SPI_DISCOVERY_CTRL_OFFSET,    sep_efuse_basetest::SPI_DISCOVERY_CTRL_READ,    sep_efuse_basetest::SPI_DISCOVERY_CTRL_WRITE,    sep_efuse_basetest::SPI_DISCOVERY_CTRL_RESET,    "SPI_DISCOVERY_CTRL"},
    {sep_efuse_basetest::SPI_PHY_DQ_TIMING_OFFSET,     sep_efuse_basetest::SPI_PHY_DQ_TIMING_READ,     sep_efuse_basetest::SPI_PHY_DQ_TIMING_WRITE,     sep_efuse_basetest::SPI_PHY_DQ_TIMING_RESET,     "SPI_PHY_DQ_TIMING"},
    {sep_efuse_basetest::SPI_PHY_DQS_TIMING_OFFSET,    sep_efuse_basetest::SPI_PHY_DQS_TIMING_READ,    sep_efuse_basetest::SPI_PHY_DQS_TIMING_WRITE,    sep_efuse_basetest::SPI_PHY_DQS_TIMING_RESET,    "SPI_PHY_DQS_TIMING"},
    {sep_efuse_basetest::SPI_PHY_GATE_LPBK_OFFSET,     sep_efuse_basetest::SPI_PHY_GATE_LPBK_READ,     sep_efuse_basetest::SPI_PHY_GATE_LPBK_WRITE,     sep_efuse_basetest::SPI_PHY_GATE_LPBK_RESET,     "SPI_PHY_GATE_LPBK"},
    {sep_efuse_basetest::SPI_PHY_DLL_SLAVE_OFFSET,     sep_efuse_basetest::SPI_PHY_DLL_SLAVE_READ,     sep_efuse_basetest::SPI_PHY_DLL_SLAVE_WRITE,     sep_efuse_basetest::SPI_PHY_DLL_SLAVE_RESET,     "SPI_PHY_DLL_SLAVE"},
    {sep_efuse_basetest::SPI_PHY_DLL_MASTER_OFFSET,    sep_efuse_basetest::SPI_PHY_DLL_MASTER_READ,    sep_efuse_basetest::SPI_PHY_DLL_MASTER_WRITE,    sep_efuse_basetest::SPI_PHY_DLL_MASTER_RESET,    "SPI_PHY_DLL_MASTER"},
    {sep_efuse_basetest::SPI_PHY_MISC_OFFSET,          sep_efuse_basetest::SPI_PHY_MISC_READ,          sep_efuse_basetest::SPI_PHY_MISC_WRITE,          sep_efuse_basetest::SPI_PHY_MISC_RESET,          "SPI_PHY_MISC"},
    {sep_efuse_basetest::SPI_RB_VALID_TIME_OFFSET,     sep_efuse_basetest::SPI_RB_VALID_TIME_READ,     sep_efuse_basetest::SPI_RB_VALID_TIME_WRITE,     sep_efuse_basetest::SPI_RB_VALID_TIME_RESET,     "SPI_RB_VALID_TIME"},
    {sep_efuse_basetest::PUBLIC_KEY_0_OFFSET,          sep_efuse_basetest::PUBLIC_KEY_0_READ,          sep_efuse_basetest::PUBLIC_KEY_0_WRITE,          sep_efuse_basetest::PUBLIC_KEY_0_RESET,          "PUBLIC_KEY_0"},
    {sep_efuse_basetest::PUBLIC_KEY_1_OFFSET,          sep_efuse_basetest::PUBLIC_KEY_1_READ,          sep_efuse_basetest::PUBLIC_KEY_1_WRITE,          sep_efuse_basetest::PUBLIC_KEY_1_RESET,          "PUBLIC_KEY_1"},
    {sep_efuse_basetest::RESERVED_0_OFFSET,            sep_efuse_basetest::RESERVED_0_READ,            sep_efuse_basetest::RESERVED_0_WRITE,            sep_efuse_basetest::RESERVED_0_RESET,            "RESERVED_0"},
    {sep_efuse_basetest::RESERVED_1_OFFSET,            sep_efuse_basetest::RESERVED_1_READ,            sep_efuse_basetest::RESERVED_1_WRITE,            sep_efuse_basetest::RESERVED_1_RESET,            "RESERVED_1"},
    {sep_efuse_basetest::RESERVED_2_OFFSET,            sep_efuse_basetest::RESERVED_2_READ,            sep_efuse_basetest::RESERVED_2_WRITE,            sep_efuse_basetest::RESERVED_2_RESET,            "RESERVED_2"},
    {sep_efuse_basetest::RESERVED_3_OFFSET,            sep_efuse_basetest::RESERVED_3_READ,            sep_efuse_basetest::RESERVED_3_WRITE,            sep_efuse_basetest::RESERVED_3_RESET,            "RESERVED_3"},
    {sep_efuse_basetest::RESERVED_4_OFFSET,            sep_efuse_basetest::RESERVED_4_READ,            sep_efuse_basetest::RESERVED_4_WRITE,            sep_efuse_basetest::RESERVED_4_RESET,            "RESERVED_4"},
    {sep_efuse_basetest::RESERVED_5_OFFSET,            sep_efuse_basetest::RESERVED_5_READ,            sep_efuse_basetest::RESERVED_5_WRITE,            sep_efuse_basetest::RESERVED_5_RESET,            "RESERVED_5"},
    {sep_efuse_basetest::RESERVED_6_OFFSET,            sep_efuse_basetest::RESERVED_6_READ,            sep_efuse_basetest::RESERVED_6_WRITE,            sep_efuse_basetest::RESERVED_6_RESET,            "RESERVED_6"},
    {sep_efuse_basetest::RESERVED_7_OFFSET,            sep_efuse_basetest::RESERVED_7_READ,            sep_efuse_basetest::RESERVED_7_WRITE,            sep_efuse_basetest::RESERVED_7_RESET,            "RESERVED_7"},
    {sep_efuse_basetest::RESERVED_LAST_256_OFFSET,     sep_efuse_basetest::RESERVED_LAST_256_READ,     sep_efuse_basetest::RESERVED_LAST_256_WRITE,     sep_efuse_basetest::RESERVED_LAST_256_RESET,     "RESERVED_LAST_256"},
    {sep_efuse_basetest::RESERVED_LAST_64_LO_OFFSET,   sep_efuse_basetest::RESERVED_LAST_64_LO_READ,   sep_efuse_basetest::RESERVED_LAST_64_LO_WRITE,   sep_efuse_basetest::RESERVED_LAST_64_LO_RESET,   "RESERVED_LAST_64_LO"},
    {sep_efuse_basetest::RESERVED_LAST_64_HI_OFFSET,   sep_efuse_basetest::RESERVED_LAST_64_HI_READ,   sep_efuse_basetest::RESERVED_LAST_64_HI_WRITE,   sep_efuse_basetest::RESERVED_LAST_64_HI_RESET,   "RESERVED_LAST_64_HI"},
    {sep_efuse_basetest::RESERVED_LAST_32_OFFSET,      sep_efuse_basetest::RESERVED_LAST_32_READ,      sep_efuse_basetest::RESERVED_LAST_32_WRITE,      sep_efuse_basetest::RESERVED_LAST_32_RESET,      "RESERVED_LAST_32"},
    // EFUSE_INTERFACE_CTRL
    {sep_efuse_basetest::EFUSE_INTF_STATUS_OFFSET,       sep_efuse_basetest::EFUSE_INTF_STATUS_READ,       sep_efuse_basetest::EFUSE_INTF_STATUS_WRITE,       sep_efuse_basetest::EFUSE_INTF_STATUS_RESET,       "EFUSE_INTF_STATUS"},
    {sep_efuse_basetest::EFUSE_WRITE_CTRL_OFFSET,        sep_efuse_basetest::EFUSE_WRITE_CTRL_READ,        sep_efuse_basetest::EFUSE_WRITE_CTRL_WRITE,        sep_efuse_basetest::EFUSE_WRITE_CTRL_RESET,        "EFUSE_WRITE_CTRL"},
    {sep_efuse_basetest::EFUSE_READ_CTRL_OFFSET,         sep_efuse_basetest::EFUSE_READ_CTRL_READ,         sep_efuse_basetest::EFUSE_READ_CTRL_WRITE,         sep_efuse_basetest::EFUSE_READ_CTRL_RESET,         "EFUSE_READ_CTRL"},
    {sep_efuse_basetest::EFUSE_PROG_INTF_RD_DATA_OFFSET, sep_efuse_basetest::EFUSE_PROG_INTF_RD_DATA_READ, sep_efuse_basetest::EFUSE_PROG_INTF_RD_DATA_WRITE, sep_efuse_basetest::EFUSE_PROG_INTF_RD_DATA_RESET, "EFUSE_PROG_INTF_RD_DATA"},
    {sep_efuse_basetest::EFUSE_READ_INTF_RD_DATA_OFFSET, sep_efuse_basetest::EFUSE_READ_INTF_RD_DATA_READ, sep_efuse_basetest::EFUSE_READ_INTF_RD_DATA_WRITE, sep_efuse_basetest::EFUSE_READ_INTF_RD_DATA_RESET, "EFUSE_READ_INTF_RD_DATA"},
    {sep_efuse_basetest::EFUSE_READ_REQ_TIMEOUT_OFFSET,  sep_efuse_basetest::EFUSE_READ_REQ_TIMEOUT_READ,  sep_efuse_basetest::EFUSE_READ_REQ_TIMEOUT_WRITE,  sep_efuse_basetest::EFUSE_READ_REQ_TIMEOUT_RESET,  "EFUSE_READ_REQ_TIMEOUT"},
    {sep_efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_OFFSET,  sep_efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_READ,  sep_efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_WRITE,  sep_efuse_basetest::EFUSE_PROG_REQ_TIMEOUT_RESET,  "EFUSE_PROG_REQ_TIMEOUT"},
    // EFUSE_MMR
    {sep_efuse_basetest::RMA_SIP_TOKEN_I_OFFSET,         sep_efuse_basetest::RMA_SIP_TOKEN_I_READ,         sep_efuse_basetest::RMA_SIP_TOKEN_I_WRITE,         sep_efuse_basetest::RMA_SIP_TOKEN_I_RESET,         "RMA_SIP_TOKEN_I"},
    {sep_efuse_basetest::RMA_CHIPLET_TOKEN_I_OFFSET,     sep_efuse_basetest::RMA_CHIPLET_TOKEN_I_READ,     sep_efuse_basetest::RMA_CHIPLET_TOKEN_I_WRITE,     sep_efuse_basetest::RMA_CHIPLET_TOKEN_I_RESET,     "RMA_CHIPLET_TOKEN_I"},
    {sep_efuse_basetest::SEC_DISABLE_TOKEN_I_OFFSET,     sep_efuse_basetest::SEC_DISABLE_TOKEN_I_READ,     sep_efuse_basetest::SEC_DISABLE_TOKEN_I_WRITE,     sep_efuse_basetest::SEC_DISABLE_TOKEN_I_RESET,     "SEC_DISABLE_TOKEN_I"},
    {sep_efuse_basetest::TOKEN_EOP_OFFSET,               sep_efuse_basetest::TOKEN_EOP_READ,               sep_efuse_basetest::TOKEN_EOP_WRITE,               sep_efuse_basetest::TOKEN_EOP_RESET,               "TOKEN_EOP"},
    {sep_efuse_basetest::RMA_SIP_TOKEN_MATCH_OFFSET,     sep_efuse_basetest::RMA_SIP_TOKEN_MATCH_READ,     sep_efuse_basetest::RMA_SIP_TOKEN_MATCH_WRITE,     sep_efuse_basetest::RMA_SIP_TOKEN_MATCH_RESET,     "RMA_SIP_TOKEN_MATCH"},
    {sep_efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_OFFSET, sep_efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_READ, sep_efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_WRITE, sep_efuse_basetest::RMA_CHIPLET_TOKEN_MATCH_RESET, "RMA_CHIPLET_TOKEN_MATCH"},
    {sep_efuse_basetest::SEC_DISABLE_TOKEN_MATCH_OFFSET, sep_efuse_basetest::SEC_DISABLE_TOKEN_MATCH_READ, sep_efuse_basetest::SEC_DISABLE_TOKEN_MATCH_WRITE, sep_efuse_basetest::SEC_DISABLE_TOKEN_MATCH_RESET, "SEC_DISABLE_TOKEN_MATCH"},
};
