// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package sep_scratch_reg_pkg;

    localparam SEP_SCRATCH_REG_DATA_WIDTH = 64;
    localparam SEP_SCRATCH_REG_MIN_ADDR_WIDTH = 6;
    localparam SEP_SCRATCH_REG_SIZE = 'h40;

    typedef struct {
        logic [31:0] value;
    } sep_scratch__SCRATCH__data__out_t;

    typedef struct {
        sep_scratch__SCRATCH__data__out_t data;
    } sep_scratch__SCRATCH__out_t;

    typedef struct {
        sep_scratch__SCRATCH__out_t SCRATCH[8];
    } sep_scratch__out_t;
endpackage
