// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package entropy_source_reg_pkg;

    localparam ENTROPY_SOURCE_REG_DATA_WIDTH = 32;
    localparam ENTROPY_SOURCE_REG_MIN_ADDR_WIDTH = 9;
    localparam ENTROPY_SOURCE_REG_SIZE = 'h154;

    typedef struct {
        logic next;
    } entropy_source__STATUS__RSVD__in_t;

    typedef struct {
        entropy_source__STATUS__RSVD__in_t RSVD;
    } entropy_source__STATUS__in_t;

    typedef struct {
        logic next;
    } entropy_source__INTR_STATUS__HEALTH_TEST_FAILED__in_t;

    typedef struct {
        logic next;
    } entropy_source__INTR_STATUS__FIFO_ERROR__in_t;

    typedef struct {
        logic next;
    } entropy_source__INTR_STATUS__FIFO_OVERFLOW__in_t;

    typedef struct {
        logic next;
    } entropy_source__INTR_STATUS__FIFO_UNDERFLOW__in_t;

    typedef struct {
        entropy_source__INTR_STATUS__HEALTH_TEST_FAILED__in_t HEALTH_TEST_FAILED;
        entropy_source__INTR_STATUS__FIFO_ERROR__in_t FIFO_ERROR;
        entropy_source__INTR_STATUS__FIFO_OVERFLOW__in_t FIFO_OVERFLOW;
        entropy_source__INTR_STATUS__FIFO_UNDERFLOW__in_t FIFO_UNDERFLOW;
    } entropy_source__INTR_STATUS__in_t;

    typedef struct {
        logic next;
    } entropy_source__SHA256_STATUS__BUSY__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__SHA256_STATUS__INPUT_COUNT__in_t;

    typedef struct {
        logic [2:0] next;
    } entropy_source__SHA256_STATUS__OUTPUT_COUNT__in_t;

    typedef struct {
        entropy_source__SHA256_STATUS__BUSY__in_t BUSY;
        entropy_source__SHA256_STATUS__INPUT_COUNT__in_t INPUT_COUNT;
        entropy_source__SHA256_STATUS__OUTPUT_COUNT__in_t OUTPUT_COUNT;
    } entropy_source__SHA256_STATUS__in_t;

    typedef struct {
        logic [6:0] next;
    } entropy_source__FIFO_STATUS__LEVEL__in_t;

    typedef struct {
        logic [4:0] next;
    } entropy_source__FIFO_STATUS__WPTR__in_t;

    typedef struct {
        logic [4:0] next;
    } entropy_source__FIFO_STATUS__RPTR__in_t;

    typedef struct {
        entropy_source__FIFO_STATUS__LEVEL__in_t LEVEL;
        entropy_source__FIFO_STATUS__WPTR__in_t WPTR;
        entropy_source__FIFO_STATUS__RPTR__in_t RPTR;
    } entropy_source__FIFO_STATUS__in_t;

    typedef struct packed {
        logic [31:0] RDATA;
    } entropy_source__FIFO_RDATA__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        entropy_source__FIFO_RDATA__external__fields__in_t rd_data;
    } entropy_source__FIFO_RDATA__external__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__HEALTH_TEST_STATUS__HEALTH_STATUS__in_t;

    typedef struct {
        entropy_source__HEALTH_TEST_STATUS__HEALTH_STATUS__in_t HEALTH_STATUS;
    } entropy_source__HEALTH_TEST_STATUS__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__REPETITION_TEST_COUNT__REPETITION_COUNT__in_t;

    typedef struct {
        entropy_source__REPETITION_TEST_COUNT__REPETITION_COUNT__in_t REPETITION_COUNT;
    } entropy_source__REPETITION_TEST_COUNT__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__APT_PATTERN_COUNT_1BIT__PATTERN_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__APT_PATTERN_COUNT_1BIT__TARGET_PATTERN__in_t;

    typedef struct {
        logic [9:0] next;
    } entropy_source__APT_PATTERN_COUNT_1BIT__SAMPLES_PROCESSED__in_t;

    typedef struct {
        entropy_source__APT_PATTERN_COUNT_1BIT__PATTERN_COUNT__in_t PATTERN_COUNT;
        entropy_source__APT_PATTERN_COUNT_1BIT__TARGET_PATTERN__in_t TARGET_PATTERN;
        entropy_source__APT_PATTERN_COUNT_1BIT__SAMPLES_PROCESSED__in_t SAMPLES_PROCESSED;
    } entropy_source__APT_PATTERN_COUNT_1BIT__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__APT_PATTERN_COUNT_2BIT__PATTERN_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__APT_PATTERN_COUNT_2BIT__TARGET_PATTERN__in_t;

    typedef struct {
        logic [9:0] next;
    } entropy_source__APT_PATTERN_COUNT_2BIT__SAMPLES_PROCESSED__in_t;

    typedef struct {
        entropy_source__APT_PATTERN_COUNT_2BIT__PATTERN_COUNT__in_t PATTERN_COUNT;
        entropy_source__APT_PATTERN_COUNT_2BIT__TARGET_PATTERN__in_t TARGET_PATTERN;
        entropy_source__APT_PATTERN_COUNT_2BIT__SAMPLES_PROCESSED__in_t SAMPLES_PROCESSED;
    } entropy_source__APT_PATTERN_COUNT_2BIT__in_t;

    typedef struct {
        logic [9:0] next;
    } entropy_source__APT_PATTERN_COUNT_3BIT__PATTERN_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__APT_PATTERN_COUNT_3BIT__TARGET_PATTERN__in_t;

    typedef struct {
        logic [9:0] next;
    } entropy_source__APT_PATTERN_COUNT_3BIT__SAMPLES_PROCESSED__in_t;

    typedef struct {
        entropy_source__APT_PATTERN_COUNT_3BIT__PATTERN_COUNT__in_t PATTERN_COUNT;
        entropy_source__APT_PATTERN_COUNT_3BIT__TARGET_PATTERN__in_t TARGET_PATTERN;
        entropy_source__APT_PATTERN_COUNT_3BIT__SAMPLES_PROCESSED__in_t SAMPLES_PROCESSED;
    } entropy_source__APT_PATTERN_COUNT_3BIT__in_t;

    typedef struct {
        logic [9:0] next;
    } entropy_source__APT_PATTERN_COUNT_4BIT__PATTERN_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__APT_PATTERN_COUNT_4BIT__TARGET_PATTERN__in_t;

    typedef struct {
        logic [9:0] next;
    } entropy_source__APT_PATTERN_COUNT_4BIT__SAMPLES_PROCESSED__in_t;

    typedef struct {
        entropy_source__APT_PATTERN_COUNT_4BIT__PATTERN_COUNT__in_t PATTERN_COUNT;
        entropy_source__APT_PATTERN_COUNT_4BIT__TARGET_PATTERN__in_t TARGET_PATTERN;
        entropy_source__APT_PATTERN_COUNT_4BIT__SAMPLES_PROCESSED__in_t SAMPLES_PROCESSED;
    } entropy_source__APT_PATTERN_COUNT_4BIT__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__MARKOV_TEST_COUNTS_0__COUNT_01__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__MARKOV_TEST_COUNTS_0__COUNT_10__in_t;

    typedef struct {
        entropy_source__MARKOV_TEST_COUNTS_0__COUNT_01__in_t COUNT_01;
        entropy_source__MARKOV_TEST_COUNTS_0__COUNT_10__in_t COUNT_10;
    } entropy_source__MARKOV_TEST_COUNTS_0__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__MARKOV_TEST_COUNTS_1__COUNT_00__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__MARKOV_TEST_COUNTS_1__COUNT_11__in_t;

    typedef struct {
        entropy_source__MARKOV_TEST_COUNTS_1__COUNT_00__in_t COUNT_00;
        entropy_source__MARKOV_TEST_COUNTS_1__COUNT_11__in_t COUNT_11;
    } entropy_source__MARKOV_TEST_COUNTS_1__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__MARKOV_TEST_PROBABILITIES__PROB_01__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__MARKOV_TEST_PROBABILITIES__PROB_10__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__MARKOV_TEST_PROBABILITIES__PROB_00__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__MARKOV_TEST_PROBABILITIES__PROB_11__in_t;

    typedef struct {
        entropy_source__MARKOV_TEST_PROBABILITIES__PROB_01__in_t PROB_01;
        entropy_source__MARKOV_TEST_PROBABILITIES__PROB_10__in_t PROB_10;
        entropy_source__MARKOV_TEST_PROBABILITIES__PROB_00__in_t PROB_00;
        entropy_source__MARKOV_TEST_PROBABILITIES__PROB_11__in_t PROB_11;
    } entropy_source__MARKOV_TEST_PROBABILITIES__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_0_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_0_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_0_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_1_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_1_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_1_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_2_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_2_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_2_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_3_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_3_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_3_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_4_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_4_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_4_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_5_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_5_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_5_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_6_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_6_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_6_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_7_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_7_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_7_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_8_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_8_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_8_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_9_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_9_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_9_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_10_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_10_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_10_HEALTH_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } entropy_source__GENERATOR_11_HEALTH_STATUS__STATUS__in_t;

    typedef struct {
        entropy_source__GENERATOR_11_HEALTH_STATUS__STATUS__in_t STATUS;
    } entropy_source__GENERATOR_11_HEALTH_STATUS__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__HT_WATERMARK_NUM__WATERMARK_NUM__in_t;

    typedef struct {
        entropy_source__HT_WATERMARK_NUM__WATERMARK_NUM__in_t WATERMARK_NUM;
    } entropy_source__HT_WATERMARK_NUM__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__HT_WATERMARK__WATERMARK_VALUE__in_t;

    typedef struct {
        entropy_source__HT_WATERMARK__WATERMARK_VALUE__in_t WATERMARK_VALUE;
    } entropy_source__HT_WATERMARK__in_t;

    typedef struct {
        logic [31:0] next;
    } entropy_source__REPCNT_TOTAL_FAILS__FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__REPCNT_TOTAL_FAILS__FAIL_COUNT__in_t FAIL_COUNT;
    } entropy_source__REPCNT_TOTAL_FAILS__in_t;

    typedef struct {
        logic [31:0] next;
    } entropy_source__APT_HI_TOTAL_FAILS__FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__APT_HI_TOTAL_FAILS__FAIL_COUNT__in_t FAIL_COUNT;
    } entropy_source__APT_HI_TOTAL_FAILS__in_t;

    typedef struct {
        logic [31:0] next;
    } entropy_source__APT_LO_TOTAL_FAILS__FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__APT_LO_TOTAL_FAILS__FAIL_COUNT__in_t FAIL_COUNT;
    } entropy_source__APT_LO_TOTAL_FAILS__in_t;

    typedef struct {
        logic [31:0] next;
    } entropy_source__MARKOV_HI_TOTAL_FAILS__FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__MARKOV_HI_TOTAL_FAILS__FAIL_COUNT__in_t FAIL_COUNT;
    } entropy_source__MARKOV_HI_TOTAL_FAILS__in_t;

    typedef struct {
        logic [31:0] next;
    } entropy_source__MARKOV_LO_TOTAL_FAILS__FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__MARKOV_LO_TOTAL_FAILS__FAIL_COUNT__in_t FAIL_COUNT;
    } entropy_source__MARKOV_LO_TOTAL_FAILS__in_t;

    typedef struct {
        logic [15:0] next;
    } entropy_source__ALERT_SUMMARY_FAIL_COUNTS__ANY_FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__ALERT_SUMMARY_FAIL_COUNTS__ANY_FAIL_COUNT__in_t ANY_FAIL_COUNT;
    } entropy_source__ALERT_SUMMARY_FAIL_COUNTS__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__ALERT_FAIL_COUNTS__APT_LO_FAIL_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__ALERT_FAIL_COUNTS__APT_HI_FAIL_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__ALERT_FAIL_COUNTS__MARKOV_LO_FAIL_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__ALERT_FAIL_COUNTS__MARKOV_HI_FAIL_COUNT__in_t;

    typedef struct {
        logic [3:0] next;
    } entropy_source__ALERT_FAIL_COUNTS__REPCNT_FAIL_COUNT__in_t;

    typedef struct {
        entropy_source__ALERT_FAIL_COUNTS__APT_LO_FAIL_COUNT__in_t APT_LO_FAIL_COUNT;
        entropy_source__ALERT_FAIL_COUNTS__APT_HI_FAIL_COUNT__in_t APT_HI_FAIL_COUNT;
        entropy_source__ALERT_FAIL_COUNTS__MARKOV_LO_FAIL_COUNT__in_t MARKOV_LO_FAIL_COUNT;
        entropy_source__ALERT_FAIL_COUNTS__MARKOV_HI_FAIL_COUNT__in_t MARKOV_HI_FAIL_COUNT;
        entropy_source__ALERT_FAIL_COUNTS__REPCNT_FAIL_COUNT__in_t REPCNT_FAIL_COUNT;
    } entropy_source__ALERT_FAIL_COUNTS__in_t;

    typedef struct {
        entropy_source__STATUS__in_t STATUS;
        entropy_source__INTR_STATUS__in_t INTR_STATUS;
        entropy_source__SHA256_STATUS__in_t SHA256_STATUS;
        entropy_source__FIFO_STATUS__in_t FIFO_STATUS;
        entropy_source__FIFO_RDATA__external__in_t FIFO_RDATA;
        entropy_source__HEALTH_TEST_STATUS__in_t HEALTH_TEST_STATUS;
        entropy_source__REPETITION_TEST_COUNT__in_t REPETITION_TEST_COUNT;
        entropy_source__APT_PATTERN_COUNT_1BIT__in_t APT_PATTERN_COUNT_1BIT;
        entropy_source__APT_PATTERN_COUNT_2BIT__in_t APT_PATTERN_COUNT_2BIT;
        entropy_source__APT_PATTERN_COUNT_3BIT__in_t APT_PATTERN_COUNT_3BIT;
        entropy_source__APT_PATTERN_COUNT_4BIT__in_t APT_PATTERN_COUNT_4BIT;
        entropy_source__MARKOV_TEST_COUNTS_0__in_t MARKOV_TEST_COUNTS_0;
        entropy_source__MARKOV_TEST_COUNTS_1__in_t MARKOV_TEST_COUNTS_1;
        entropy_source__MARKOV_TEST_PROBABILITIES__in_t MARKOV_TEST_PROBABILITIES;
        entropy_source__GENERATOR_0_HEALTH_STATUS__in_t GENERATOR_0_HEALTH_STATUS;
        entropy_source__GENERATOR_1_HEALTH_STATUS__in_t GENERATOR_1_HEALTH_STATUS;
        entropy_source__GENERATOR_2_HEALTH_STATUS__in_t GENERATOR_2_HEALTH_STATUS;
        entropy_source__GENERATOR_3_HEALTH_STATUS__in_t GENERATOR_3_HEALTH_STATUS;
        entropy_source__GENERATOR_4_HEALTH_STATUS__in_t GENERATOR_4_HEALTH_STATUS;
        entropy_source__GENERATOR_5_HEALTH_STATUS__in_t GENERATOR_5_HEALTH_STATUS;
        entropy_source__GENERATOR_6_HEALTH_STATUS__in_t GENERATOR_6_HEALTH_STATUS;
        entropy_source__GENERATOR_7_HEALTH_STATUS__in_t GENERATOR_7_HEALTH_STATUS;
        entropy_source__GENERATOR_8_HEALTH_STATUS__in_t GENERATOR_8_HEALTH_STATUS;
        entropy_source__GENERATOR_9_HEALTH_STATUS__in_t GENERATOR_9_HEALTH_STATUS;
        entropy_source__GENERATOR_10_HEALTH_STATUS__in_t GENERATOR_10_HEALTH_STATUS;
        entropy_source__GENERATOR_11_HEALTH_STATUS__in_t GENERATOR_11_HEALTH_STATUS;
        entropy_source__HT_WATERMARK_NUM__in_t HT_WATERMARK_NUM;
        entropy_source__HT_WATERMARK__in_t HT_WATERMARK;
        entropy_source__REPCNT_TOTAL_FAILS__in_t REPCNT_TOTAL_FAILS;
        entropy_source__APT_HI_TOTAL_FAILS__in_t APT_HI_TOTAL_FAILS;
        entropy_source__APT_LO_TOTAL_FAILS__in_t APT_LO_TOTAL_FAILS;
        entropy_source__MARKOV_HI_TOTAL_FAILS__in_t MARKOV_HI_TOTAL_FAILS;
        entropy_source__MARKOV_LO_TOTAL_FAILS__in_t MARKOV_LO_TOTAL_FAILS;
        entropy_source__ALERT_SUMMARY_FAIL_COUNTS__in_t ALERT_SUMMARY_FAIL_COUNTS;
        entropy_source__ALERT_FAIL_COUNTS__in_t ALERT_FAIL_COUNTS;
    } entropy_source__in_t;

    typedef struct {
        logic value;
    } entropy_source__CTRL__RESET__out_t;

    typedef struct {
        logic value;
    } entropy_source__CTRL__AUTOTUNE_ENABLE__out_t;

    typedef struct {
        logic value;
    } entropy_source__CTRL__BYPASS_ENTROPY_COMPRESSOR__out_t;

    typedef struct {
        logic [9:0] value;
    } entropy_source__CTRL__DOWNSAMPLE_RATE__out_t;

    typedef struct {
        logic value;
    } entropy_source__CTRL__SHA256_WHITENING_ENABLE__out_t;

    typedef struct {
        entropy_source__CTRL__RESET__out_t RESET;
        entropy_source__CTRL__AUTOTUNE_ENABLE__out_t AUTOTUNE_ENABLE;
        entropy_source__CTRL__BYPASS_ENTROPY_COMPRESSOR__out_t BYPASS_ENTROPY_COMPRESSOR;
        entropy_source__CTRL__DOWNSAMPLE_RATE__out_t DOWNSAMPLE_RATE;
        entropy_source__CTRL__SHA256_WHITENING_ENABLE__out_t SHA256_WHITENING_ENABLE;
    } entropy_source__CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } entropy_source__DEBUG_CTRL__SELECT_SIGNAL__out_t;

    typedef struct {
        logic [2:0] value;
    } entropy_source__DEBUG_CTRL__SELECT_FREQ_DIV__out_t;

    typedef struct {
        entropy_source__DEBUG_CTRL__SELECT_SIGNAL__out_t SELECT_SIGNAL;
        entropy_source__DEBUG_CTRL__SELECT_FREQ_DIV__out_t SELECT_FREQ_DIV;
    } entropy_source__DEBUG_CTRL__out_t;

    typedef struct {
        logic intr;
    } entropy_source__INTR_STATUS__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_ENABLE__HEALTH_TEST_FAILED__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_ENABLE__FIFO_ERROR__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_ENABLE__FIFO_OVERFLOW__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_ENABLE__FIFO_UNDERFLOW__out_t;

    typedef struct {
        entropy_source__INTR_ENABLE__HEALTH_TEST_FAILED__out_t HEALTH_TEST_FAILED;
        entropy_source__INTR_ENABLE__FIFO_ERROR__out_t FIFO_ERROR;
        entropy_source__INTR_ENABLE__FIFO_OVERFLOW__out_t FIFO_OVERFLOW;
        entropy_source__INTR_ENABLE__FIFO_UNDERFLOW__out_t FIFO_UNDERFLOW;
    } entropy_source__INTR_ENABLE__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_TEST__HEALTH_TEST_FAILED__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_TEST__FIFO_ERROR__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_TEST__FIFO_OVERFLOW__out_t;

    typedef struct {
        logic value;
    } entropy_source__INTR_TEST__FIFO_UNDERFLOW__out_t;

    typedef struct {
        entropy_source__INTR_TEST__HEALTH_TEST_FAILED__out_t HEALTH_TEST_FAILED;
        entropy_source__INTR_TEST__FIFO_ERROR__out_t FIFO_ERROR;
        entropy_source__INTR_TEST__FIFO_OVERFLOW__out_t FIFO_OVERFLOW;
        entropy_source__INTR_TEST__FIFO_UNDERFLOW__out_t FIFO_UNDERFLOW;
    } entropy_source__INTR_TEST__out_t;

    typedef struct {
        logic value;
    } entropy_source__FIFO_CTRL__ENABLE__out_t;

    typedef struct {
        logic value;
    } entropy_source__FIFO_CTRL__ENTROPY_CHURN_ENABLE__out_t;

    typedef struct {
        entropy_source__FIFO_CTRL__ENABLE__out_t ENABLE;
        entropy_source__FIFO_CTRL__ENTROPY_CHURN_ENABLE__out_t ENTROPY_CHURN_ENABLE;
    } entropy_source__FIFO_CTRL__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } entropy_source__FIFO_RDATA__external__out_t;

    typedef struct {
        logic [7:0] value;
    } entropy_source__HEALTH_TEST_CTRL__ENABLE__out_t;

    typedef struct {
        logic [7:0] value;
    } entropy_source__HEALTH_TEST_CTRL__REPETITION_LIMIT__out_t;

    typedef struct {
        entropy_source__HEALTH_TEST_CTRL__ENABLE__out_t ENABLE;
        entropy_source__HEALTH_TEST_CTRL__REPETITION_LIMIT__out_t REPETITION_LIMIT;
    } entropy_source__HEALTH_TEST_CTRL__out_t;

    typedef struct {
        logic [15:0] value;
    } entropy_source__HEALTH_TEST_WINDOW_SIZE__SIZE__out_t;

    typedef struct {
        entropy_source__HEALTH_TEST_WINDOW_SIZE__SIZE__out_t SIZE;
    } entropy_source__HEALTH_TEST_WINDOW_SIZE__out_t;

    typedef struct {
        logic [15:0] value;
    } entropy_source__MARKOV_TEST_PROB_THRESHOLDS__PROB_01_THRESHOLD__out_t;

    typedef struct {
        logic [15:0] value;
    } entropy_source__MARKOV_TEST_PROB_THRESHOLDS__PROB_10_THRESHOLD__out_t;

    typedef struct {
        entropy_source__MARKOV_TEST_PROB_THRESHOLDS__PROB_01_THRESHOLD__out_t PROB_01_THRESHOLD;
        entropy_source__MARKOV_TEST_PROB_THRESHOLDS__PROB_10_THRESHOLD__out_t PROB_10_THRESHOLD;
    } entropy_source__MARKOV_TEST_PROB_THRESHOLDS__out_t;

    typedef struct {
        logic [15:0] value;
    } entropy_source__APT_PROPORTION_1BIT__LIMIT__out_t;

    typedef struct {
        entropy_source__APT_PROPORTION_1BIT__LIMIT__out_t LIMIT;
    } entropy_source__APT_PROPORTION_1BIT__out_t;

    typedef struct {
        logic [9:0] value;
    } entropy_source__APT_PROPORTION_2BIT__LIMIT__out_t;

    typedef struct {
        entropy_source__APT_PROPORTION_2BIT__LIMIT__out_t LIMIT;
    } entropy_source__APT_PROPORTION_2BIT__out_t;

    typedef struct {
        logic [9:0] value;
    } entropy_source__APT_PROPORTION_3BIT__LIMIT__out_t;

    typedef struct {
        entropy_source__APT_PROPORTION_3BIT__LIMIT__out_t LIMIT;
    } entropy_source__APT_PROPORTION_3BIT__out_t;

    typedef struct {
        logic [9:0] value;
    } entropy_source__APT_PROPORTION_4BIT__LIMIT__out_t;

    typedef struct {
        entropy_source__APT_PROPORTION_4BIT__LIMIT__out_t LIMIT;
    } entropy_source__APT_PROPORTION_4BIT__out_t;

    typedef struct {
        logic [11:0] value;
    } entropy_source__RING_OSC_ENABLE__ENABLE__out_t;

    typedef struct {
        logic [11:0] value;
    } entropy_source__RING_OSC_ENABLE__SAMPLE_CLK_ENABLE__out_t;

    typedef struct {
        entropy_source__RING_OSC_ENABLE__ENABLE__out_t ENABLE;
        entropy_source__RING_OSC_ENABLE__SAMPLE_CLK_ENABLE__out_t SAMPLE_CLK_ENABLE;
    } entropy_source__RING_OSC_ENABLE__out_t;

    typedef struct {
        logic [11:0] value;
    } entropy_source__RING_OSC_TUNE__DETUNE__out_t;

    typedef struct {
        logic [11:0] value;
    } entropy_source__RING_OSC_TUNE__SAMPLE_CLK_DETUNE__out_t;

    typedef struct {
        entropy_source__RING_OSC_TUNE__DETUNE__out_t DETUNE;
        entropy_source__RING_OSC_TUNE__SAMPLE_CLK_DETUNE__out_t SAMPLE_CLK_DETUNE;
    } entropy_source__RING_OSC_TUNE__out_t;

    typedef struct {
        logic [11:0] value;
    } entropy_source__RING_OSC_CTRL__SAMPLE_CLK_SELECT__out_t;

    typedef struct {
        entropy_source__RING_OSC_CTRL__SAMPLE_CLK_SELECT__out_t SAMPLE_CLK_SELECT;
    } entropy_source__RING_OSC_CTRL__out_t;

    typedef struct {
        logic [11:0] value;
    } entropy_source__DECORRELATOR_CTRL__BYPASS__out_t;

    typedef struct {
        logic [19:0] value;
    } entropy_source__DECORRELATOR_CTRL__SAMPLE_CLK_DIV__out_t;

    typedef struct {
        entropy_source__DECORRELATOR_CTRL__BYPASS__out_t BYPASS;
        entropy_source__DECORRELATOR_CTRL__SAMPLE_CLK_DIV__out_t SAMPLE_CLK_DIV;
    } entropy_source__DECORRELATOR_CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } entropy_source__DECORRELATOR_MASK__ENTROPY_BYTE_MASK__out_t;

    typedef struct {
        entropy_source__DECORRELATOR_MASK__ENTROPY_BYTE_MASK__out_t ENTROPY_BYTE_MASK;
    } entropy_source__DECORRELATOR_MASK__out_t;

    typedef struct {
        logic [15:0] value;
    } entropy_source__STARTUP_CTRL__DELAY_CYCLES__out_t;

    typedef struct {
        entropy_source__STARTUP_CTRL__DELAY_CYCLES__out_t DELAY_CYCLES;
    } entropy_source__STARTUP_CTRL__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_0_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_0_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_0_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_1_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_1_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_1_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_2_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_2_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_2_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_3_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_3_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_3_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_4_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_4_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_4_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_5_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_5_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_5_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_6_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_6_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_6_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_7_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_7_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_7_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_8_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_8_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_8_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_9_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_9_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_9_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_10_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_10_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_10_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [4:0] value;
    } entropy_source__GENERATOR_11_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t;

    typedef struct {
        entropy_source__GENERATOR_11_SAMPLE_CLK_CONFIG__SAMPLE_CLK_DIVIDE__out_t SAMPLE_CLK_DIVIDE;
    } entropy_source__GENERATOR_11_SAMPLE_CLK_CONFIG__out_t;

    typedef struct {
        logic [3:0] value;
    } entropy_source__HT_WATERMARK_NUM__WATERMARK_NUM__out_t;

    typedef struct {
        entropy_source__HT_WATERMARK_NUM__WATERMARK_NUM__out_t WATERMARK_NUM;
    } entropy_source__HT_WATERMARK_NUM__out_t;

    typedef struct {
        entropy_source__CTRL__out_t CTRL;
        entropy_source__DEBUG_CTRL__out_t DEBUG_CTRL;
        entropy_source__INTR_STATUS__out_t INTR_STATUS;
        entropy_source__INTR_ENABLE__out_t INTR_ENABLE;
        entropy_source__INTR_TEST__out_t INTR_TEST;
        entropy_source__FIFO_CTRL__out_t FIFO_CTRL;
        entropy_source__FIFO_RDATA__external__out_t FIFO_RDATA;
        entropy_source__HEALTH_TEST_CTRL__out_t HEALTH_TEST_CTRL;
        entropy_source__HEALTH_TEST_WINDOW_SIZE__out_t HEALTH_TEST_WINDOW_SIZE;
        entropy_source__MARKOV_TEST_PROB_THRESHOLDS__out_t MARKOV_TEST_PROB_THRESHOLDS;
        entropy_source__APT_PROPORTION_1BIT__out_t APT_PROPORTION_1BIT;
        entropy_source__APT_PROPORTION_2BIT__out_t APT_PROPORTION_2BIT;
        entropy_source__APT_PROPORTION_3BIT__out_t APT_PROPORTION_3BIT;
        entropy_source__APT_PROPORTION_4BIT__out_t APT_PROPORTION_4BIT;
        entropy_source__RING_OSC_ENABLE__out_t RING_OSC_ENABLE;
        entropy_source__RING_OSC_TUNE__out_t RING_OSC_TUNE;
        entropy_source__RING_OSC_CTRL__out_t RING_OSC_CTRL;
        entropy_source__DECORRELATOR_CTRL__out_t DECORRELATOR_CTRL;
        entropy_source__DECORRELATOR_MASK__out_t DECORRELATOR_MASK;
        entropy_source__STARTUP_CTRL__out_t STARTUP_CTRL;
        entropy_source__GENERATOR_0_SAMPLE_CLK_CONFIG__out_t GENERATOR_0_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_1_SAMPLE_CLK_CONFIG__out_t GENERATOR_1_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_2_SAMPLE_CLK_CONFIG__out_t GENERATOR_2_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_3_SAMPLE_CLK_CONFIG__out_t GENERATOR_3_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_4_SAMPLE_CLK_CONFIG__out_t GENERATOR_4_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_5_SAMPLE_CLK_CONFIG__out_t GENERATOR_5_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_6_SAMPLE_CLK_CONFIG__out_t GENERATOR_6_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_7_SAMPLE_CLK_CONFIG__out_t GENERATOR_7_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_8_SAMPLE_CLK_CONFIG__out_t GENERATOR_8_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_9_SAMPLE_CLK_CONFIG__out_t GENERATOR_9_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_10_SAMPLE_CLK_CONFIG__out_t GENERATOR_10_SAMPLE_CLK_CONFIG;
        entropy_source__GENERATOR_11_SAMPLE_CLK_CONFIG__out_t GENERATOR_11_SAMPLE_CLK_CONFIG;
        entropy_source__HT_WATERMARK_NUM__out_t HT_WATERMARK_NUM;
    } entropy_source__out_t;

    typedef enum logic [2:0] {
        entropy_source__WATERMARK_TEST__REPCNT_HI = 'h0,
        entropy_source__WATERMARK_TEST__APT_HI = 'h1,
        entropy_source__WATERMARK_TEST__APT_LO = 'h2,
        entropy_source__WATERMARK_TEST__MARKOV_HI = 'h3,
        entropy_source__WATERMARK_TEST__MARKOV_LO = 'h4
    } entropy_source__WATERMARK_TEST_e;
endpackage
