// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#define SEP_MSG_LIFECYCLE_INVALID                        0x01
#define SEP_MSG_SPI_TLV_INVALID                          0x03
#define SEP_MSG_SPI_NOT_DETECTED_SLOW                    0x04
#define SEP_MSG_INVALID_MANIFEST_ID                      0x06
#define SEP_MSG_INVALID_MANIFEST_VERSION                 0x07
#define SEP_MSG_INVALID_SECURITY_VERSION                 0x08
#define SEP_MSG_INVALID_MANIFEST_LENGTH                  0x09
#define SEP_MSG_INVALID_SIGNATURE_TYPE                   0x0a
#define SEP_MSG_INVALID_KEY_INDEX                        0x0b
#define SEP_MSG_REVOKED_KEY                              0x0c
#define SEP_MSG_INVALID_KEY_HASH                         0x0d
#define SEP_MSG_INVALID_SIGNATURE                        0x0e
#define SEP_MSG_TOC_ID_INVALID                           0x0f
#define SEP_MSG_TOC_VERSION_INVALID                      0x10
#define SEP_MSG_TOC_HASH_INVALID                         0x11
#define SEP_MSG_BL1_SIZE_INVALID                         0x12
#define SEP_MSG_INVALID_MANIFEST_HASH                    0x13
#define SEP_MSG_SEP_BL1_MISSING                          0x14
#define SEP_MSG_PAYLOAD_OVERLAPS_MANIFEST                0x16
#define SEP_MSG_BL1_RETURNED                             0x18
#define SEP_MSG_INVALID_KEY_CONTENTS                     0x19
#define SEP_MSG_DECRYPTION_FAILED                        0x1a
#define SEP_MSG_PAYLOAD_IMAGE_COUNT_INVALID              0x1b
#define SEP_MSG_MANIFEST_INVALID_ENCRYPTION              0x1e
#define SEP_MSG_FUSE_LC_STATE                            0x20
#define SEP_MSG_INVALID_CHIPLET_ID                       0x21
#define SEP_MSG_INVALID_PACKAGE_ID                       0x22
#define SEP_MSG_PRIMARY_CHIPLET                          0x23
#define SEP_MSG_TOC_PAYLOAD_SIZE_MISMATCH                0x24
#define SEP_MSG_IMAGE_EXCEEDS_PAYLOAD_LENGTH             0x25
#define SEP_MSG_INVALID_IMAGE_SIZE                       0x26
#define SEP_MSG_INVALID_PAYLOAD_LENGTH                   0x27
#define SEP_MSG_GENERAL_EXCEPTION                        0x28
#define SEP_MSG_WAIT_FOR_PLL_LOCK                        0x29
#define SEP_MSG_SECONDARY_CHIPLET                        0x2a
#define SEP_MSG_BOOT_RECOVERY                            0x2b
#define SEP_MSG_LIFECYCLE_VALID                          0x2c
#define SEP_MSG_EXT_SRAM_CLEAR_START                     0x2d
#define SEP_MSG_SPI_USE_FUSES                            0x2e
#define SEP_MSG_SPI_DETECTED_DEFAULT                     0x2f
#define SEP_MSG_SPI_TRY_BACKUP                           0x31
#define SEP_MSG_SPI_TLV_PRIMARY                          0x32
#define SEP_MSG_SPI_TLV_BACKUP                           0x33
#define SEP_MSG_SPI_TLV_VALID                            0x34
#define SEP_MSG_SPI_USING_DEFAULT_CONFIG                 0x35
#define SEP_MSG_SPI_TRY_TLV_CONFIG                       0x36
#define SEP_MSG_SPI_USING_TLV_CONFIG                     0x37
#define SEP_MSG_SPI_USE_SLOW_CONFIG                      0x38
#define SEP_MSG_EXT_SRAM_INIT_WAIT                       0x39
#define SEP_MSG_DECRYPTION_START                         0x40
#define SEP_MSG_PAYLOAD_NOT_ENCRYPTED                    0x41
#define SEP_MSG_DECRYPTION_END                           0x42
#define SEP_MSG_STARTING_BL1                             0x43
#define SEP_MSG_BOOTROM_START                            0x44
#define SEP_MSG_ROM_INITIALIZED                          0x45
#define SEP_MSG_SPI_COPY_START                           0x46
#define SEP_MSG_PRIMARY_BL1_LOADED                       0x48
#define SEP_MSG_BACKUP_BL1_LOADED                        0x49
#define SEP_MSG_COPY_AND_EXEC_IMAGE                      0x4a
#define SEP_MSG_START_MANIFEST_VALIDATION                0x4b
#define SEP_MSG_CHECK_MANIFEST_HASH                      0x4c
#define SEP_MSG_CHECK_PAYLOAD_HASH                       0x4d
#define SEP_MSG_VERIFY_SIGNATURE                         0x4e
#define SEP_MSG_CHECK_USAGE_CONSTRAINTS                  0x4f
#define SEP_MSG_CREATE_SKS_KEYS                          0x50
#define SEP_MSG_RECORD_MEASUREMENT                       0x51
#define SEP_MSG_START_PAYLOAD_VALIDATION                 0x52
#define SEP_MSG_MANIFEST_VALIDATED                       0x53
#define SEP_MSG_EXEC_IMAGE                               0x54
#define SEP_MSG_PAYLOAD_VALIDATED                        0x55
#define SEP_MSG_BOOTROM_PRESTART_DONE                    0x56
#define SEP_MSG_BOOTROM_START_MAIN                       0x57
#define SEP_MSG_FUSE_SBOOT_DIS                           0x58
#define SEP_MSG_SPI_NOT_DETECTED_DEFAULT                 0x5f
#define SEP_MSG_SPI_NOT_DETECTED_TLV                     0x60
#define SEP_MSG_SPI_PRIMARY_TLV_FAILED                   0x61
#define SEP_MSG_SPI_USING_SLOW_CONFIG                    0x62
#define SEP_MSG_PAYLOAD_HASH_INVALID                     0x66
#define SEP_MSG_WARM_RESET_JUMP                          0x68
#define SEP_MSG_WARM_RESET_HANG                          0x69
#define SEP_MSG_MANIFEST_TOO_LONG                        0x6b
#define SEP_MSG_TOC_INVALID_ORDER                        0x6c
#define SEP_MSG_IMAGE_EXCEEDS_BOUND                      0x6d
#define SEP_MSG_PLL_CLK_INIT                             0x6f
#define SEP_MSG_REF_CLK_SELECTED                         0x70
#define SEP_MSG_PLL_CLK_SELECTED                         0x71
#define SEP_MSG_STATUS_REPORTING_DISABLED                0x76
#define SEP_MSG_STATUS_REPORTING_ENABLED                 0x77
#define SEP_MSG_STATUS_REPORTING_READY                   0x78
#define SEP_MSG_STATUS_REPORTING_INVALID                 0x79
#define SEP_MSG_PAYLOAD_INVALID_LOCATION_FLASH           0x7a
#define SEP_MSG_CLEAR_ICCM_FAILED                        0x7b
#define SEP_MSG_WAIT_FOR_SMC_MANIFEST_READY              0x7d
#define SEP_MSG_USING_ROM_KEY                            0x7f
#define SEP_MSG_CHIPLET_UNSUPPORTED                      0x8a
#define SEP_MSG_STACK_VALIDATION_FAILED                  0x8c
#define SEP_MSG_MANIFEST_SECURE_BOOT                     0x8d
#define SEP_MSG_SECURE_BOOT_ENABLED                      0x8e
#define SEP_MSG_SECURE_BOOT_DISABLED                     0x8f
#define SEP_MSG_ROTATE_UPDATE                            0x90
#define SEP_MSG_SIGNATURE_VALIDATED                      0x91
#define SEP_MSG_ICCM_CLEAR_START                         0x93
#define SEP_MSG_ICCM_CLEAR_DONE                          0x94
#define SEP_MSG_PLL_FUSES_BLANK                          0x95
#define SEP_MSG_USING_SMC_SRAM                           0x98
#define SEP_MSG_USING_SEP_SRAM                           0x99
#define SEP_MSG_DMA_ERROR                                0x9d
#define SEP_MSG_BL1_ENTRY_INVALID                       0x12b
#define SEP_MSG_DFT_GATE_CHECK                          0x200
#define SEP_MSG_DFT_GATE_BYPASS                         0x201
#define SEP_MSG_PERIPH_BUS_RESET_CHECK                  0x202
#define SEP_MSG_PERIPH_BUS_RESET_STUB                   0x203
#define SEP_MSG_CRYPTO_INIT_CHECK                       0x204
#define SEP_MSG_DMA_INIT_CHECK                          0x205
#define SEP_MSG_SPI_INIT_CHECK                          0x206
#define SEP_MSG_VALIDATE_CHECK                          0x207
#define SEP_MSG_HANDOFF_CHECK                           0x208
#define SEP_MSG_BL0_STATE_INIT                          0x209
#define SEP_MSG_BOOT_MODE                               0x20a
#define SEP_MSG_SMC_COORD_CHECK                         0x20b
#define SEP_MSG_DEVICE_MODE_INPUTS_CHECK                0x20c
#define SEP_MSG_ROM_MAIN_BEFORE_PASS                    0x20d
#define SEP_MSG_BL1_FOUND                               0x20e
#define SEP_MSG_BL1_COPY                                0x20f
#define SEP_MSG_EXT_SRAM_CLEAR_DONE                     0x210
#define SEP_MSG_RUNTIME_INIT_OK                         0x211
#define SEP_MSG_MANIFEST_LOAD_START                     0x212
#define SEP_MSG_MANIFEST_LOAD_FAILED                    0x213
#define SEP_MSG_BAD_IMAGE_TYPE                          0x214
#define SEP_MSG_IMAGE_OOB                               0x215
#define SEP_MSG_IMAGE_OVERLAP                           0x216
#define SEP_MSG_BL1_BAD_ADDR                            0x217
#define SEP_MSG_BL1_TOO_LARGE                           0x218
#define SEP_MSG_INFO_OVERFLOW                          0xfffe
#define SEP_MSG_WARNING_OVERFLOW                       0xffff
