// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#pragma once
#include <stdint.h>
#include <stddef.h>

/* Generated by common_otbn infrastructure using OpenTitan build tools */

/* Expected CRC checksum (matches OTBN LOAD_CHECKSUM register) */
#define OTBN_P256_ECDSA_EXPECTED_CRC 0xbae122dcU

/* OTBN symbol addresses (OpenTitan-style) */
#define _otbn_remote_app_p256_ecdsa_p256_verify ((const uint32_t*)0xfd4)
#define _otbn_remote_app_p256_ecdsa_MODE_SIDELOAD_ECDH ((const uint32_t*)0x72c)
#define _otbn_remote_app_p256_ecdsa_MODE_SIDELOAD_KEYGEN ((const uint32_t*)0x275)
#define _otbn_remote_app_p256_ecdsa_p256_invalid_input ((const uint32_t*)0xc4c)
#define _otbn_remote_app_p256_ecdsa_p256_generate_k ((const uint32_t*)0xa08)
#define _otbn_remote_app_p256_ecdsa_p256_r448 ((const uint32_t*)0x40)
#define _otbn_remote_app_p256_ecdsa_proj_add ((const uint32_t*)0x3c4)
#define _otbn_remote_app_p256_ecdsa__dmem_data_start ((const uint32_t*)0x0)
#define _otbn_remote_app_p256_ecdsa_x ((const uint32_t*)0x580)
#define _otbn_remote_app_p256_ecdsa_x_r ((const uint32_t*)0x640)
#define _otbn_remote_app_p256_ecdsa__imem_end ((const uint32_t*)0x12d8)
#define _otbn_remote_app_p256_ecdsa_MODE_VERIFY ((const uint32_t*)0x1f8)
#define _otbn_remote_app_p256_ecdsa__imem_start ((const uint32_t*)0x0)
#define _otbn_remote_app_p256_ecdsa_p256_u_n ((const uint32_t*)0x80)
#define _otbn_remote_app_p256_ecdsa_MODE_KEYGEN ((const uint32_t*)0x5c5)
#define _otbn_remote_app_p256_ecdsa_p256_shared_key ((const uint32_t*)0xc60)
#define _otbn_remote_app_p256_ecdsa_mul_modp ((const uint32_t*)0x2c4)
#define _otbn_remote_app_p256_ecdsa_msg ((const uint32_t*)0x520)
#define _otbn_remote_app_p256_ecdsa_p256_base_mult ((const uint32_t*)0x8c0)
#define _otbn_remote_app_p256_ecdsa_d0_io ((const uint32_t*)0x5c0)
#define _otbn_remote_app_p256_ecdsa_p256_key_from_seed ((const uint32_t*)0xad4)
#define _otbn_remote_app_p256_ecdsa_r ((const uint32_t*)0x540)
#define _otbn_remote_app_p256_ecdsa__imem_size ((const uint32_t*)0x12d8)
#define _otbn_remote_app_p256_ecdsa_p256_n ((const uint32_t*)0x60)
#define _otbn_remote_app_p256_ecdsa_trigger_fault_if_fg0_z ((const uint32_t*)0x15c)
#define _otbn_remote_app_p256_ecdsa_mode ((const uint32_t*)0x500)
#define _otbn_remote_app_p256_ecdsa__start ((const uint32_t*)0x0)
#define _otbn_remote_app_p256_ecdsa_p256_p ((const uint32_t*)0x20)
#define _otbn_remote_app_p256_ecdsa_p256_generate_random_key ((const uint32_t*)0x9cc)
#define _otbn_remote_app_p256_ecdsa_arithmetic_to_boolean_mod ((const uint32_t*)0xce8)
#define _otbn_remote_app_p256_ecdsa_scalar_mult_int ((const uint32_t*)0x7c4)
#define _otbn_remote_app_p256_ecdsa_p256_isoncurve ((const uint32_t*)0xb58)
#define _otbn_remote_app_p256_ecdsa_p256_gy ((const uint32_t*)0xc0)
#define _otbn_remote_app_p256_ecdsa__dmem_bss_start ((const uint32_t*)0xe0)
#define _otbn_remote_app_p256_ecdsa_p256_sign ((const uint32_t*)0xe14)
#define _otbn_remote_app_p256_ecdsa_y ((const uint32_t*)0x5a0)
#define _otbn_remote_app_p256_ecdsa_mod_mul_256x256 ((const uint32_t*)0x244)
#define _otbn_remote_app_p256_ecdsa__dmem_data_end ((const uint32_t*)0xe0)
#define _otbn_remote_app_p256_ecdsa_proj_double ((const uint32_t*)0x70c)
#define _otbn_remote_app_p256_ecdsa_mod_mul_320x128 ((const uint32_t*)0x290)
#define _otbn_remote_app_p256_ecdsa_MODE_SIDELOAD_SIGN ((const uint32_t*)0x45e)
#define _otbn_remote_app_p256_ecdsa_mod_inv ((const uint32_t*)0x694)
#define _otbn_remote_app_p256_ecdsa_p256_gx ((const uint32_t*)0xa0)
#define _otbn_remote_app_p256_ecdsa_ok ((const uint32_t*)0x504)
#define _otbn_remote_app_p256_ecdsa_s ((const uint32_t*)0x560)
#define _otbn_remote_app_p256_ecdsa_p256_check_public_key ((const uint32_t*)0xbc0)
#define _otbn_remote_app_p256_ecdsa_p256_b ((const uint32_t*)0x0)
#define _otbn_remote_app_p256_ecdsa_arithmetic_to_boolean ((const uint32_t*)0xd4c)
#define _otbn_remote_app_p256_ecdsa_MODE_SIGN ((const uint32_t*)0x31b)
#define _otbn_remote_app_p256_ecdsa_setup_modp ((const uint32_t*)0x398)
#define _otbn_remote_app_p256_ecdsa_MODE_ECDH ((const uint32_t*)0x6eb)
#define _otbn_remote_app_p256_ecdsa_start ((const uint32_t*)0x0)
#define _otbn_remote_app_p256_ecdsa__dmem_bss_end ((const uint32_t*)0x660)
#define _otbn_remote_app_p256_ecdsa_d1_io ((const uint32_t*)0x600)
#define _otbn_remote_app_p256_ecdsa_proj_to_affine ((const uint32_t*)0x504)
#define _otbn_remote_app_p256_ecdsa__dmem_bss_offset ((const uint32_t*)0xe0)

/* OpenTitan-compatible macros for p256_ecdsa */
#define OTBN_DECLARE_SYMBOL_ADDR(app, sym) /* Already declared above */
#define OTBN_ADDR_T_INIT(app, sym) ((uint32_t)_otbn_remote_app_##app##_##sym)

/* OTBN memory arrays */
extern const uint32_t otbn_p256_ecdsa_imem[];
extern const size_t otbn_p256_ecdsa_imem_words;
extern const uint32_t otbn_p256_ecdsa_dmem[];
extern const size_t otbn_p256_ecdsa_dmem_words;

