// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
// ROM-embedded public key digests for secure boot.
//
// Contains SHA-256 digests of allowed RSA-3072 public keys (moduli).
// The ROM verifies a manifest's public key by hashing it and comparing
// against these compiled-in digests (for ROM key slots) or against
// fuse-stored digests (for fuse key slots).
//
// Only the key digest is stored here;
// OTBN handles Montgomery precomputation internally, so we only store
// the key digest.
//
// Production keys: generated by tools/generate_key_digests.py from PEM files.
// Test keys: placeholder entries for development/DV.

#pragma once

#include <stdint.h>
#include <stdbool.h>

#include "manifest.h"  // PUBK_SEL_NUM_ROM_KEYS, RSA_3072_KEY_SZ_BYTES

#ifndef SHA256_DIGEST_SIZE_BYTES
#define SHA256_DIGEST_SIZE_BYTES 32
#endif

// Per-key information stored in ROM.
typedef struct {
    const uint8_t *digest;  // SHA-256 of the RSA-3072 modulus (32 bytes), or NULL
} public_key_info_t;

// Number of ROM key slots.
#define NUM_PUBLIC_KEY_DIGESTS  PUBK_SEL_NUM_ROM_KEYS

// ROM key digest table.
// Index 0..5 correspond to dev0, dev1, prod0..prod3.
// Entries with digest == NULL are considered empty/unused.
extern public_key_info_t public_key_digests[NUM_PUBLIC_KEY_DIGESTS];
