# SPDX-License-Identifier: Apache-2.0
# Extra fragment for samples/subsys/shell/shell_module on smc_vp.
# Keep the serial backend on polling UART (see Kconfig.defconfig).
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y
