/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was AUTO-GENERATED by this script:
 *       create_reg_c_header.py   (r2025-06-03)
 * ... from this input file:
 *       otbn_wrapper_key.rdl
 * ... using this as the target address space:
 *       otbn_wrapper_key
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

#ifndef OTBN_WRAPPER_KEY_REG_H
#define OTBN_WRAPPER_KEY_REG_H



//==============================================================================
// Addresses for Address Map: otbn_wrapper_key
//==============================================================================


#define OTBN_WRAPPER_KEY_REG_MAP_BASE_ADDR  (0x00000000)
#define OTBN_WRAPPER_KEY_REG_MAP_SIZE       (0x00000064)

#define KEY_SHARE0_0__REG_OFFSET                                                          (0x00000000)
#define KEY_SHARE0_0__REG_ADDR                                                            (0x00000000)
#define KEY_SHARE0_1__REG_OFFSET                                                          (0x00000004)
#define KEY_SHARE0_1__REG_ADDR                                                            (0x00000004)
#define KEY_SHARE0_2__REG_OFFSET                                                          (0x00000008)
#define KEY_SHARE0_2__REG_ADDR                                                            (0x00000008)
#define KEY_SHARE0_3__REG_OFFSET                                                          (0x0000000C)
#define KEY_SHARE0_3__REG_ADDR                                                            (0x0000000C)
#define KEY_SHARE0_4__REG_OFFSET                                                          (0x00000010)
#define KEY_SHARE0_4__REG_ADDR                                                            (0x00000010)
#define KEY_SHARE0_5__REG_OFFSET                                                          (0x00000014)
#define KEY_SHARE0_5__REG_ADDR                                                            (0x00000014)
#define KEY_SHARE0_6__REG_OFFSET                                                          (0x00000018)
#define KEY_SHARE0_6__REG_ADDR                                                            (0x00000018)
#define KEY_SHARE0_7__REG_OFFSET                                                          (0x0000001C)
#define KEY_SHARE0_7__REG_ADDR                                                            (0x0000001C)
#define KEY_SHARE0_8__REG_OFFSET                                                          (0x00000020)
#define KEY_SHARE0_8__REG_ADDR                                                            (0x00000020)
#define KEY_SHARE0_9__REG_OFFSET                                                          (0x00000024)
#define KEY_SHARE0_9__REG_ADDR                                                            (0x00000024)
#define KEY_SHARE0_10__REG_OFFSET                                                         (0x00000028)
#define KEY_SHARE0_10__REG_ADDR                                                           (0x00000028)
#define KEY_SHARE0_11__REG_OFFSET                                                         (0x0000002C)
#define KEY_SHARE0_11__REG_ADDR                                                           (0x0000002C)
#define KEY_SHARE1_0__REG_OFFSET                                                          (0x00000030)
#define KEY_SHARE1_0__REG_ADDR                                                            (0x00000030)
#define KEY_SHARE1_1__REG_OFFSET                                                          (0x00000034)
#define KEY_SHARE1_1__REG_ADDR                                                            (0x00000034)
#define KEY_SHARE1_2__REG_OFFSET                                                          (0x00000038)
#define KEY_SHARE1_2__REG_ADDR                                                            (0x00000038)
#define KEY_SHARE1_3__REG_OFFSET                                                          (0x0000003C)
#define KEY_SHARE1_3__REG_ADDR                                                            (0x0000003C)
#define KEY_SHARE1_4__REG_OFFSET                                                          (0x00000040)
#define KEY_SHARE1_4__REG_ADDR                                                            (0x00000040)
#define KEY_SHARE1_5__REG_OFFSET                                                          (0x00000044)
#define KEY_SHARE1_5__REG_ADDR                                                            (0x00000044)
#define KEY_SHARE1_6__REG_OFFSET                                                          (0x00000048)
#define KEY_SHARE1_6__REG_ADDR                                                            (0x00000048)
#define KEY_SHARE1_7__REG_OFFSET                                                          (0x0000004C)
#define KEY_SHARE1_7__REG_ADDR                                                            (0x0000004C)
#define KEY_SHARE1_8__REG_OFFSET                                                          (0x00000050)
#define KEY_SHARE1_8__REG_ADDR                                                            (0x00000050)
#define KEY_SHARE1_9__REG_OFFSET                                                          (0x00000054)
#define KEY_SHARE1_9__REG_ADDR                                                            (0x00000054)
#define KEY_SHARE1_10__REG_OFFSET                                                         (0x00000058)
#define KEY_SHARE1_10__REG_ADDR                                                           (0x00000058)
#define KEY_SHARE1_11__REG_OFFSET                                                         (0x0000005C)
#define KEY_SHARE1_11__REG_ADDR                                                           (0x0000005C)
#define KEY_CTRL_REG_OFFSET                                                               (0x00000060)
#define KEY_CTRL_REG_ADDR                                                                 (0x00000060)


#ifndef __ASSEMBLER__

#include <stdint.h>

//==============================================================================
// Structs for Address Map: otbn_wrapper_key
//==============================================================================


typedef struct {
    uint32_t data : 32;
} OTBN_WRAPPER_KEY_KEY_WORD_REG_reg_t;

typedef union {
    uint32_t val;
    OTBN_WRAPPER_KEY_KEY_WORD_REG_reg_t f;
} OTBN_WRAPPER_KEY_KEY_WORD_REG_reg_u;

#define OTBN_WRAPPER_KEY_KEY_WORD_REG_REG_DEFAULT (0x00000000)


typedef struct {
    uint32_t key_valid : 1;
    uint32_t rsvd : 31;
} OTBN_WRAPPER_KEY_KEY_CTRL_REG_reg_t;

typedef union {
    uint32_t val;
    OTBN_WRAPPER_KEY_KEY_CTRL_REG_reg_t f;
} OTBN_WRAPPER_KEY_KEY_CTRL_REG_reg_u;

#define OTBN_WRAPPER_KEY_KEY_CTRL_REG_REG_DEFAULT (0x00000000)


typedef struct {
    OTBN_WRAPPER_KEY_KEY_WORD_REG_reg_u key_share0[12];
    OTBN_WRAPPER_KEY_KEY_WORD_REG_reg_u key_share1[12];
    OTBN_WRAPPER_KEY_KEY_CTRL_REG_reg_u key_ctrl;
} otbn_wrapper_key_regmap_t;

#endif // __ASSEMBLER__

//==============================================================================
// Bit Fields for Address Map: otbn_wrapper_key
//==============================================================================

#define OTBN_WRAPPER_KEY_KEY_WORD_REG_DATA_MASK  0xFFFFFFFF
#define OTBN_WRAPPER_KEY_KEY_WORD_REG_DATA_SHIFT 0

#define OTBN_WRAPPER_KEY_KEY_CTRL_REG_KEY_VALID_MASK  0x1
#define OTBN_WRAPPER_KEY_KEY_CTRL_REG_KEY_VALID_SHIFT 0

#define OTBN_WRAPPER_KEY_KEY_CTRL_REG_RSVD_MASK  0xFFFFFFFE
#define OTBN_WRAPPER_KEY_KEY_CTRL_REG_RSVD_SHIFT 1

#endif
