/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:5e48b92e6453481c8c6e061661ed7249042f9754 


#pragma once

#include <scml2.h>
#include <systemc>
#include <scmlinc/scml_property.h>
#include <tlm.h>
#include <scml2_protocol_engines/reset/include/reset_engine.h>




class xspi_targetMirrorBase : public sc_core::sc_module {
  public:
#if (defined SYSTEMC_VERSION && SYSTEMC_VERSION <= 20221128 /*2.3.4*/)
    SC_HAS_PROCESS(xspi_targetMirrorBase);
#endif

	typedef xspi_targetMirrorBase ModelBaseType;

    xspi_targetMirrorBase(sc_core::sc_module_name name) 
        : sc_core::sc_module(name)
        , MEM_SIZE("MEM_SIZE", 0x2000000)
        , reset_in("reset_in")
        , xspi_bus("xspi_bus")
        , reset_in_mockup("reset_in_mockup", reset_in) {
      reset_in_mockup.mode = scml2::DURATION;
      reset_in_mockup.active_level = false;
      /* reset_in_mockup.duration = ; */
      reset_in_mockup.enable_debug_trigger = false;
      reset_in_mockup.finalize_construction();
    }
    
    ~xspi_targetMirrorBase() {
      
    }
    
    /**
     * This method resets all interfaces, registers, and bitfields to their reset value.
     * It is typically called from end_of_elaboration(), and connected to the reset port.
     */
    
    virtual void reset_model() {
    }
    
    virtual void end_of_elaboration() {
      sc_core::sc_module::end_of_elaboration();
      reset_model();
    }
    
    ModelBaseType& model() {
      return *this;
    }
     
    
    
    scml_property<int> MEM_SIZE;
    
    sc_core::sc_out<bool> reset_in;
    scml2::initiator_socket<64> xspi_bus;
    
    
    
    scml2::reset_master_engine reset_in_mockup;
};

