/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was auto-generated by this script:
 *       create_reg_sv_header.py   (r2025-06-03)
 * ... from this input file:
 *       output_remap.rdl
 * ... using this as the target address space:
 *       output_remap
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef OUTPUT_REMAP_REG_SVH
`define OUTPUT_REMAP_REG_SVH



//==============================================================================
// Addresses for Address Map: output_remap
//==============================================================================


localparam int unsigned OUTPUT_REMAP_REG_MAP_BASE_ADDR                                                            = 32'h00000000;
localparam int unsigned OUTPUT_REMAP_REG_MAP_SIZE                                                                 = 32'h00000008;




//==============================================================================
// Register File: REGION
//==============================================================================

localparam int unsigned REGION_REG_FILE_BASE_ADDR                                                                 = 32'h00000000;
localparam int unsigned REGION_REG_FILE_SIZE                                                                      = 32'h00000008;

localparam int unsigned REGION_REGION_ATTRS_REG_OFFSET                                                            = 32'h00000000;
localparam int unsigned REGION_REGION_ATTRS_REG_ADDR                                                              = 32'h00000000;


//==============================================================================
// Default values for registers
//==============================================================================

localparam longint unsigned OUTPUT_REMAP_REGION_REGION_ATTRS_REG_DEFAULT                                          = 64'h0000000000000000;



//==============================================================================
// Bit Fields for Address Map: output_remap
//==============================================================================

localparam longint unsigned OUTPUT_REMAP_REGION_REGION_ATTRS_OFFSET_MASK                                          = 64'hFFFFFFFFFFFFFF;
localparam     int unsigned OUTPUT_REMAP_REGION_REGION_ATTRS_OFFSET_SHIFT                                         = 0;





typedef struct packed {
    logic [55:0]   offset ;
} output_remap_region_region_attrs_reg_t;




`endif
