# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

# Start from the normal SEP platform configuration, then select the artifacts
# produced together by `make secure_boot_ephemeral`.
@include accellera_config.ini

[string]
och_sep_ss1.otbn.algorithm_type : rsa_3072
och_sep_ss1.targets : ../../../../sw/sep-vp-tests/fw-tests-from-tt-oca-hw/fw/sep/bootcode/build/secure/boot_rom.elf
och_sep_ss1.spiPreload : ../../../../sw/sep-vp-tests/fw-tests-from-tt-oca-hw/fw/sep/bootcode/build/secure/secure_boot.spi_preload
