#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Generate key_digests.c from RSA-3072 PEM key files.

Usage:
    python3 generate_key_digests.py --keys dev0.pem,dev1.pem,prod0.pem,...
    python3 generate_key_digests.py --keys-dir path/to/signing_keys/

Reads RSA-3072 private key PEM files, extracts the public key modulus,
computes SHA-256(modulus_big_endian_384bytes), and outputs key_digests.c.
"""

import argparse
import hashlib
import sys
from pathlib import Path

def extract_modulus_digest(pem_path):
    """Extract RSA-3072 modulus from PEM and return SHA-256 digest."""
    from cryptography.hazmat.primitives import serialization
    with open(pem_path, 'rb') as f:
        private_key = serialization.load_pem_private_key(f.read(), password=None)
    pub = private_key.public_key()
    n = pub.public_numbers().n
    modulus_bytes = n.to_bytes(384, byteorder='big')
    return hashlib.sha256(modulus_bytes).digest()

def format_digest(name, digest):
    """Format a digest as a C static const array."""
    lines = [f'static const uint8_t {name}[SHA256_DIGEST_SIZE_BYTES] = {{']
    for i in range(0, 32, 8):
        chunk = ', '.join(f'0x{digest[i+j]:02x}' for j in range(8))
        lines.append(f'    {chunk},')
    lines.append('};')
    return '\n'.join(lines)

SLOT_NAMES = ['dev0', 'dev1', 'prod0', 'prod1', 'prod2', 'prod3']

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--keys', help='Comma-separated PEM files (slot0,slot1,...)')
    group.add_argument('--keys-dir', help='Directory with rsa_private_key.*.pem files')
    parser.add_argument('-o', '--output', default='key_digests.c')
    args = parser.parse_args()

    pem_files = {}
    if args.keys_dir:
        d = Path(args.keys_dir)
        for name in SLOT_NAMES:
            p = d / f'rsa_private_key.{name}.pem'
            if p.exists():
                pem_files[name] = p
    else:
        for i, path in enumerate(args.keys.split(',')):
            path = path.strip()
            if path and path != '-':
                pem_files[SLOT_NAMES[i]] = Path(path)

    # Generate C file
    digest_defs = []
    entries = []
    for name in SLOT_NAMES:
        if name in pem_files:
            digest = extract_modulus_digest(pem_files[name])
            var = f'digest_{name}'
            digest_defs.append(format_digest(var, digest))
            entries.append(f'    {{ .digest = {var} }},  // slot {SLOT_NAMES.index(name)}: {name}')
            print(f'  slot {SLOT_NAMES.index(name)} ({name}): {pem_files[name]}', file=sys.stderr)
        else:
            entries.append(f'    {{ .digest = (void *)0 }},     // slot {SLOT_NAMES.index(name)}: {name}')

    with open(args.output, 'w') as f:
        f.write('// Auto-generated by generate_key_digests.py — DO NOT EDIT.\n')
        f.write('//\n')
        f.write('// SHA-256 digests of RSA-3072 public key moduli.\n\n')
        f.write('#include "key_digests.h"\n\n')
        for d in digest_defs:
            f.write(d + '\n\n')
        f.write('public_key_info_t public_key_digests[NUM_PUBLIC_KEY_DIGESTS] = {\n')
        f.write('\n'.join(entries) + '\n')
        f.write('};\n')

    print(f'Generated {args.output}', file=sys.stderr)

if __name__ == '__main__':
    main()
