// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
/**
 * @file secure_dma_register.h
 * @brief DMA Controller register type definitions
 *
 * This file contains all register type definitions for the DMA Controller
 * including:
 * - Interrupt control registers (INTR_STATE, INTR_ENABLE, INTR_TEST)
 * - Alert test register (ALERT_TEST)
 * - Address configuration registers (SRC/DST_ADDR_LO/HI, ADDR_SPACE_ID)
 * - Memory range security registers (ENABLED_MEMORY_RANGE_BASE/LIMIT,
 * RANGE_VALID)
 * - Register locking (RANGE_REGWEN, CFG_REGWEN)
 * - Transfer configuration (TOTAL/CHUNK_DATA_SIZE, TRANSFER_WIDTH)
 * - Control and status registers (CONTROL, STATUS, ERROR_CODE)
 * - Addressing mode configuration (SRC_CONFIG, DST_CONFIG)
 * - SHA-2 digest output registers (SHA2_DIGEST array)
 * - Hardware handshake configuration (HANDSHAKE_INTR_ENABLE,
 * CLEAR_INTR_SRC/BUS)
 * - Interrupt source configuration (INTR_SRC_ADDR, INTR_SRC_WR_VAL arrays)
 *
 * Each register class inherits from csml_reg<N> and defines its bitfields with
 * proper access restrictions (RO, WO, RW, W1C, W0C) and reset values.
 *
 * Generated by CSML Code Generator from CSV register specification.
 */

#pragma once
#include "csml_register.h"
#include <iostream>
#include <systemc.h>

/**
 * @namespace dma
 * @brief DMA Controller register type definitions namespace
 *
 * Contains all register class templates for the DMA Controller module.
 */
namespace dma {

/**
 * @class INTR_STATE_type
 * @brief Interrupt State Register (offset 0x00, RO, reset 0x00000000)
 *
 * Read-only register reflecting current interrupt status.
 * Fields:
 * - dma_done [0]: DMA transfer complete
 * - dma_chunk_done [1]: Chunk transfer complete
 * - dma_error [2]: Error occurred
 * - reserved0 [31:3]: Reserved (read as 0)
 */
template <unsigned int N> class INTR_STATE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  INTR_STATE_type(std::string reg_name, memory_type &memory,
                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x7, 0x0, 0x00000000),
        dma_done(reg_name + ".dma_done", *this, 0, 1),
        dma_chunk_done(reg_name + ".dma_chunk_done", *this, 1, 1),
        dma_error(reg_name + ".dma_error", *this, 2, 1),
        reserved0(reg_name + ".reserved0", *this, 3, 29) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> dma_done;       ///< DMA operation complete (bit 0, RO)
  csml_bitfield<N> dma_chunk_done; ///< Chunk transfer complete (bit 1, RO)
  csml_bitfield<N> dma_error;      ///< Error occurred (bit 2, RO)
  csml_bitfield<N> reserved0;      ///< Reserved bits [31:3]
};

template <unsigned int N> class INTR_ENABLE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  INTR_ENABLE_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x7, 0x7, 0x00000000),
        dma_done(reg_name + ".dma_done", *this, 0, 1),
        dma_chunk_done(reg_name + ".dma_chunk_done", *this, 1, 1),
        dma_error(reg_name + ".dma_error", *this, 2, 1),
        reserved0(reg_name + ".reserved0", *this, 3, 29) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> dma_done;
  csml_bitfield<N> dma_chunk_done;
  csml_bitfield<N> dma_error;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class INTR_TEST_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  INTR_TEST_type(std::string reg_name, memory_type &memory, unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x0, 0x7, 0x00000000),
        dma_done(reg_name + ".dma_done", *this, 0, 1),
        dma_chunk_done(reg_name + ".dma_chunk_done", *this, 1, 1),
        dma_error(reg_name + ".dma_error", *this, 2, 1),
        reserved0(reg_name + ".reserved0", *this, 3, 29) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> dma_done;
  csml_bitfield<N> dma_chunk_done;
  csml_bitfield<N> dma_error;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class ALERT_TEST_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  ALERT_TEST_type(std::string reg_name, memory_type &memory,
                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x0, 0x1, 0x00000000),
        fatal_fault(reg_name + ".fatal_fault", *this, 0, 1),
        reserved0(reg_name + ".reserved0", *this, 1, 31) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> fatal_fault;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class SRC_ADDR_LO_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  SRC_ADDR_LO_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        src_addr_lo(reg_name + ".src_addr_lo", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> src_addr_lo;
};

template <unsigned int N> class SRC_ADDR_HI_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  SRC_ADDR_HI_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        src_addr_hi(reg_name + ".src_addr_hi", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> src_addr_hi;
};

template <unsigned int N> class DST_ADDR_LO_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  DST_ADDR_LO_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        dst_addr_lo(reg_name + ".dst_addr_lo", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> dst_addr_lo;
};

template <unsigned int N> class DST_ADDR_HI_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  DST_ADDR_HI_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        dst_addr_hi(reg_name + ".dst_addr_hi", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> dst_addr_hi;
};

template <unsigned int N> class ADDR_SPACE_ID_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  ADDR_SPACE_ID_type(std::string reg_name, memory_type &memory,
                     unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xFF, 0xFF, 0x00000077),
        src_asid(reg_name + ".src_asid", *this, 0, 4),
        dst_asid(reg_name + ".dst_asid", *this, 4, 4),
        reserved0(reg_name + ".reserved0", *this, 8, 24) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> src_asid;
  csml_bitfield<N> dst_asid;
  csml_bitfield<N> reserved0;
};

template <unsigned int N>
class ENABLED_MEMORY_RANGE_BASE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  ENABLED_MEMORY_RANGE_BASE_type(std::string reg_name, memory_type &memory,
                                 unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        base(reg_name + ".base", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> base;
};

template <unsigned int N>
class ENABLED_MEMORY_RANGE_LIMIT_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  ENABLED_MEMORY_RANGE_LIMIT_type(std::string reg_name, memory_type &memory,
                                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        limit(reg_name + ".limit", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> limit;
};

template <unsigned int N> class RANGE_VALID_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  RANGE_VALID_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x1, 0x1, 0x00000000),
        range_valid(reg_name + ".range_valid", *this, 0, 1),
        reserved0(reg_name + ".reserved0", *this, 1, 31) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> range_valid;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class RANGE_REGWEN_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  RANGE_REGWEN_type(std::string reg_name, memory_type &memory,
                    unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xF, 0xF, 0x00000006),
        regwen(reg_name + ".regwen", *this, 0, 4),
        reserved0(reg_name + ".reserved0", *this, 4, 28) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> regwen;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class CFG_REGWEN_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  CFG_REGWEN_type(std::string reg_name, memory_type &memory,
                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xF, 0x0, 0x00000006),
        regwen(reg_name + ".regwen", *this, 0, 4),
        reserved0(reg_name + ".reserved0", *this, 4, 28) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> regwen;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class TOTAL_DATA_SIZE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  TOTAL_DATA_SIZE_type(std::string reg_name, memory_type &memory,
                       unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        total_size(reg_name + ".total_size", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> total_size;
};

template <unsigned int N> class CHUNK_DATA_SIZE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  CHUNK_DATA_SIZE_type(std::string reg_name, memory_type &memory,
                       unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        chunk_size(reg_name + ".chunk_size", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> chunk_size;
};

template <unsigned int N> class TRANSFER_WIDTH_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  TRANSFER_WIDTH_type(std::string reg_name, memory_type &memory,
                      unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x3, 0x3, 0x00000002),
        transaction_width(reg_name + ".transaction_width", *this, 0, 2),
        reserved0(reg_name + ".reserved0", *this, 2, 30) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> transaction_width;
  csml_bitfield<N> reserved0;
};

/**
 * @class CONTROL_type
 * @brief Control Register (offset 0x44, Mixed access, reset 0x00000000)
 *
 * DMA control register with mixed access types.
 * Fields:
 * - opcode [3:0]: Operation code (0x0=COPY, 0x1=SHA256, 0x2=SHA384, 0x3=SHA512)
 * - hardware_handshake_enable [4]: Enable hardware handshake mode
 * - digest_swap [5]: Byte-swap SHA-2 digest output
 * - initial_transfer [8]: First transfer for hash initialization
 * - abort [27]: Abort transfer (WO, always reads 0)
 * - go [31]: Start transfer (write 1 to initiate)
 */
template <unsigned int N> class CONTROL_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  CONTROL_type(std::string reg_name, memory_type &memory, unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xF7FFFFFF, 0x8000013F,
                    0x00000000),
        opcode(reg_name + ".opcode", *this, 0, 4),
        hardware_handshake_enable(reg_name + ".hardware_handshake_enable",
                                  *this, 4, 1),
        digest_swap(reg_name + ".digest_swap", *this, 5, 1),
        reserved0(reg_name + ".reserved0", *this, 6, 2),
        initial_transfer(reg_name + ".initial_transfer", *this, 8, 1),
        reserved1(reg_name + ".reserved1", *this, 9, 18),
        abort(reg_name + ".abort", *this, 27, 1),
        reserved2(reg_name + ".reserved2", *this, 28, 3),
        go(reg_name + ".go", *this, 31, 1) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> opcode; ///< Operation code [3:0]: 0x0=COPY, 0x1=SHA256,
                           ///< 0x2=SHA384, 0x3=SHA512
  csml_bitfield<N>
      hardware_handshake_enable; ///< Enable hardware handshake mode (bit 4, RW)
  csml_bitfield<N> digest_swap;  ///< Byte-swap SHA-2 digest (bit 5, RW)
  csml_bitfield<N> reserved0;    ///< Reserved bits [7:6]
  csml_bitfield<N>
      initial_transfer;       ///< First transfer for hash init (bit 8, RW)
  csml_bitfield<N> reserved1; ///< Reserved bits [26:9]
  csml_bitfield<N> abort;     ///< Abort transfer (bit 27, WO, always reads 0)
  csml_bitfield<N> reserved2; ///< Reserved bits [30:28]
  csml_bitfield<N> go;        ///< Start transfer (bit 31, RW)
};

template <unsigned int N> class SRC_CONFIG_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  SRC_CONFIG_type(std::string reg_name, memory_type &memory,
                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x3, 0x3, 0x00000000),
        increment(reg_name + ".increment", *this, 0, 1),
        wrap(reg_name + ".wrap", *this, 1, 1),
        reserved0(reg_name + ".reserved0", *this, 2, 30) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> increment;
  csml_bitfield<N> wrap;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class DST_CONFIG_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  DST_CONFIG_type(std::string reg_name, memory_type &memory,
                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x3, 0x3, 0x00000000),
        increment(reg_name + ".increment", *this, 0, 1),
        wrap(reg_name + ".wrap", *this, 1, 1),
        reserved0(reg_name + ".reserved0", *this, 2, 30) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> increment;
  csml_bitfield<N> wrap;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class STATUS_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  STATUS_type(std::string reg_name, memory_type &memory, unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x3F, 0x2E, 0x00000000),
        busy(reg_name + ".busy", *this, 0, 1),
        done(reg_name + ".done", *this, 1, 1),
        aborted(reg_name + ".aborted", *this, 2, 1),
        error(reg_name + ".error", *this, 3, 1),
        sha2_digest_valid(reg_name + ".sha2_digest_valid", *this, 4, 1),
        chunk_done(reg_name + ".chunk_done", *this, 5, 1),
        reserved0(reg_name + ".reserved0", *this, 6, 26) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> busy;
  csml_bitfield<N> done;
  csml_bitfield<N> aborted;
  csml_bitfield<N> error;
  csml_bitfield<N> sha2_digest_valid;
  csml_bitfield<N> chunk_done;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class ERROR_CODE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  ERROR_CODE_type(std::string reg_name, memory_type &memory,
                  unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xFF, 0x0, 0x00000000),
        src_addr_error(reg_name + ".src_addr_error", *this, 0, 1),
        dst_addr_error(reg_name + ".dst_addr_error", *this, 1, 1),
        opcode_error(reg_name + ".opcode_error", *this, 2, 1),
        size_error(reg_name + ".size_error", *this, 3, 1),
        bus_error(reg_name + ".bus_error", *this, 4, 1),
        base_limit_error(reg_name + ".base_limit_error", *this, 5, 1),
        range_valid_error(reg_name + ".range_valid_error", *this, 6, 1),
        asid_error(reg_name + ".asid_error", *this, 7, 1),
        reserved0(reg_name + ".reserved0", *this, 8, 24) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> src_addr_error;
  csml_bitfield<N> dst_addr_error;
  csml_bitfield<N> opcode_error;
  csml_bitfield<N> size_error;
  csml_bitfield<N> bus_error;
  csml_bitfield<N> base_limit_error;
  csml_bitfield<N> range_valid_error;
  csml_bitfield<N> asid_error;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class SHA2_DIGEST_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  SHA2_DIGEST_type(std::string reg_name, memory_type &memory,
                   unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0x0, 0x00000000),
        digest(reg_name + ".digest", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> digest;
};

template <unsigned int N>
class HANDSHAKE_INTR_ENABLE_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  HANDSHAKE_INTR_ENABLE_type(std::string reg_name, memory_type &memory,
                             unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x7FF, 0x7FF, 0x000007FF),
        enable(reg_name + ".enable", *this, 0, 11),
        reserved0(reg_name + ".reserved0", *this, 11, 21) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> enable;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class CLEAR_INTR_SRC_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  CLEAR_INTR_SRC_type(std::string reg_name, memory_type &memory,
                      unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x7FF, 0x7FF, 0x00000000),
        clear_enable(reg_name + ".clear_enable", *this, 0, 11),
        reserved0(reg_name + ".reserved0", *this, 11, 21) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> clear_enable;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class CLEAR_INTR_BUS_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  CLEAR_INTR_BUS_type(std::string reg_name, memory_type &memory,
                      unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0x7FF, 0x7FF, 0x00000000),
        bus_select(reg_name + ".bus_select", *this, 0, 11),
        reserved0(reg_name + ".reserved0", *this, 11, 21) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> bus_select;
  csml_bitfield<N> reserved0;
};

template <unsigned int N> class INTR_SRC_ADDR_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  INTR_SRC_ADDR_type(std::string reg_name, memory_type &memory,
                     unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        addr(reg_name + ".addr", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> addr;
};

template <unsigned int N> class INTR_SRC_WR_VAL_type : public csml_reg<N> {
public:
  using typename csml_reg<N>::memory_type;
  typedef typename csml_word<N>::wordtype DT;
  INTR_SRC_WR_VAL_type(std::string reg_name, memory_type &memory,
                       unsigned int offset)
      : csml_reg<N>(reg_name, memory, offset, 0xffffffff, 0xffffffff,
                    0x00000000),
        wr_val(reg_name + ".wr_val", *this, 0, 32) {
    this->set_read_write_restrictions(memory);
  }

  using csml_reg<N>::operator=;
  using csml_reg<N>::operator+=;
  using csml_reg<N>::operator-=;
  using csml_reg<N>::operator/=;
  using csml_reg<N>::operator*=;
  using csml_reg<N>::operator%=;
  using csml_reg<N>::operator^=;
  using csml_reg<N>::operator&=;
  using csml_reg<N>::operator|=;
  using csml_reg<N>::operator>>=;
  using csml_reg<N>::operator<<=;
  csml_bitfield<N> wr_val;
};

} // namespace dma