// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
/*
 * OTBN RSA-3072 Signature Verification Test
 *
 * This test demonstrates RSA-3072 signature verification using the OTBN coprocessor.
 * It verifies a PKCS#1 v1.5 padded signature with SHA-256 hash for the message "Hello OTBN."
 *
 * Test Vector Details:
 * - Message: "Hello OTBN."
 * - Hash Algorithm: SHA-256 (256-bit digest)
 * - Signature Algorithm: RSA-3072 with PKCS#1 v1.5 padding
 * - Public Exponent: e = 65537 (F4)
 *
 * Setup:
 *  Use generate_test_vectors.py to create test vectors for this test when evaluating
 *  different keys, messages, or padding schemes
 *
 * Test:
 * 1. Loads RSA modulus, signature, and operation mode into OTBN DMEM
 * 2. Executes RSA modular exponentiation (signature^e mod n) in OTBN
 * 3. Reads back the result and verifies the PKCS#1 v1.5 padding structure
 * 4. Extracts the SHA-256 digest from the padded result and compares with expected value
 *
 * Adapted from OpenTitan RSA reference implementation.
 * Ported from dv/sep/tests/ to fw/sep/tests/ (added test_pass/test_fail,
 * sep_outbound_filter_init).
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "rsa_3072_app_otbn.h"  // Generated by common_otbn infrastructure
#include "och_sep_top_reg.h"    // OCH SEP register map with absolute addresses
#include "och_sep_common.h"     // Register access macros (WRITE_REG/READ_REG)
#include "sep_outbound_filter.h"
#include "test_completion.h"

// ============================================================================
// RSA-3072 Constants
// ============================================================================

// RSA-3072 key and digest sizes
#define RSA_3072_NUM_BITS       3072
#define RSA_3072_NUM_BYTES      (RSA_3072_NUM_BITS / 8)  // 384 bytes
#define RSA_3072_NUM_WORDS      (RSA_3072_NUM_BYTES / 4)  // 96 words

// SHA-256 digest size
#define SHA256_DIGEST_BITS      256
#define SHA256_DIGEST_BYTES     (SHA256_DIGEST_BITS / 8)  // 32 bytes
#define SHA256_DIGEST_WORDS     (SHA256_DIGEST_BYTES / 4)  // 8 words

// RSA mode constant from OTBN run_rsa.s
// MODE_RSA_3072_MODEXP_F4: RSA-3072 modular exponentiation with F4 exponent (e=65537)
#define MODE_RSA_3072_MODEXP_F4  0x1be

// OTBN status register values
#define OTBN_STATUS_IDLE        0x00
#define OTBN_STATUS_BUSY_EXECUTE 0x01

// OTBN command register values
#define OTBN_CMD_EXECUTE        0xD8
#define OTBN_CMD_SEC_WIPE_DMEM  0xC3
#define OTBN_CMD_SEC_WIPE_IMEM  0x1E

// ============================================================================
// Register and Memory Access Macros
// ============================================================================

// Memory access - word-indexed access to IMEM and DMEM
#define OTBN_IMEM(word)   READ_MEM_WORD(OTBN_IMEM_MEM_BASE_ADDR, word)
#define OTBN_DMEM(word)   READ_MEM_WORD(OTBN_DMEM_MEM_BASE_ADDR, word)
#define OTBN_IMEM_WRITE(word, value)   WRITE_MEM_WORD(OTBN_IMEM_MEM_BASE_ADDR, word, value)
#define OTBN_DMEM_WRITE(word, value)   WRITE_MEM_WORD(OTBN_DMEM_MEM_BASE_ADDR, word, value)

// ============================================================================
// OTBN DMEM Symbol Offsets (extracted from ELF symbol table)
// ============================================================================

#define DMEM_MODE_OFFSET    OTBN_ADDR_T_INIT(rsa_3072_app, mode)    // Operation mode
#define DMEM_N_OFFSET       OTBN_ADDR_T_INIT(rsa_3072_app, rsa_n)   // RSA modulus (n)
#define DMEM_D0_OFFSET      OTBN_ADDR_T_INIT(rsa_3072_app, rsa_d0)  // Public exponent (e) for verify
#define DMEM_INOUT_OFFSET   OTBN_ADDR_T_INIT(rsa_3072_app, inout)   // Input: signature, Output: decrypted message

// ============================================================================
// Test Vectors - Generated for "Hello OTBN." with SHA-256
// ============================================================================

// RSA-3072 modulus (n) - 96 words in big-endian format (reversed word order)
static const uint32_t test_modulus[96] = {
    0x7bea9b17, 0x6128a693, 0xf8d14b28, 0x6b2210f0, 0x705ea032, 0x29a494fe,
    0x62ab3565, 0x591e5a0c, 0x5a37b289, 0x77c70b62, 0xcd9ba5a0, 0x5660bc01,
    0x0f3ee231, 0x2a38afc1, 0x2668d0ed, 0x8c1a9bac, 0x0868ad2c, 0xd147d3ff,
    0x03274087, 0x90ae7a62, 0x644dd430, 0x2eed3b94, 0x37bbed69, 0x0fce9c3a,
    0x8cb2d504, 0xc4b960ed, 0x0f6fa76e, 0xe4e3979c, 0xef0db3bd, 0xf9418dd1,
    0x8396279c, 0x15e79d7e, 0x3c70cd06, 0x7759fe66, 0x3380bb39, 0x800e9038,
    0x81bd3bf5, 0x03ca1490, 0xf72898c7, 0x714942b3, 0xbe03d574, 0x7e59296e,
    0x5c779ecd, 0x03479d3a, 0x13557ce1, 0x5f6be335, 0x0642eaff, 0x96963214,
    0xee69b4b4, 0x2aaabcfe, 0x35c94270, 0xb1265a30, 0x7236e358, 0x7d4f0359,
    0x0c9b68f4, 0x5bbdb1d5, 0x10d4e5f5, 0x37d81e09, 0x0cb3f718, 0x8b918d48,
    0xccc4859d, 0x9cca85a6, 0x9aec8ebb, 0x2b73a631, 0x9f5a74df, 0xae388cd4,
    0xaf68d149, 0x42bf4986, 0x8fbb8773, 0x84930d57, 0xe5c1f516, 0x3820944d,
    0x935aedb1, 0x59ce1791, 0xb8d21a40, 0xd5f9e5ca, 0x2c9e212b, 0xd1fee885,
    0x2d4ae258, 0x31bd8fb9, 0x218d43c6, 0x0d5365c0, 0x96c26490, 0x60f538d8,
    0x1759a998, 0x62c3d384, 0x5ccc328a, 0x5e1dae73, 0x29cfadbd, 0xf6210530,
    0x7d084a8b, 0x76e6dd44, 0xb8900fd6, 0xde91da0a, 0xfe0985b0, 0xbb32fb6e,
};

// Public exponent (e) - always 65537 for F4
static const uint32_t test_public_exponent = 0x00010001;

// SHA-256 digest of 'Hello OTBN.' - 8 words in big-endian format (reversed word order)
static const uint32_t test_message_digest[8] = {
    0x6eaf2403, 0x83625a71, 0x5359fbbb, 0x30b486d3,
    0xe3366d8a, 0x7f7f8c68, 0xadc45493, 0x2e8bd199,
};

// RSA-3072 signature - 96 words in big-endian format (reversed word order)
static const uint32_t test_signature[96] = {
    0x0e61cc02, 0xbbc39c74, 0xc06c87da, 0x6d993b20, 0xda66beca, 0xc314f857,
    0x24229ee7, 0x28930c7c, 0x85fd4586, 0xcdcf9c00, 0x0cdab077, 0xd19ae4cf,
    0x582ca86b, 0x38c0377d, 0x27106596, 0xfa4bd22e, 0x91457d2b, 0x1b876abc,
    0x2c7f5238, 0x603c30fd, 0x23f96285, 0x9e7dd339, 0x75314bf0, 0xde7f53f5,
    0x4ec010ec, 0x3de9b064, 0x6723b9f9, 0xf9794966, 0x95813546, 0x1497611d,
    0x3cb4d02b, 0x8d48ceb9, 0xa40cc004, 0xa10b9009, 0xc64230aa, 0x224fd1e2,
    0xf9dd9f52, 0x51257276, 0xe8fc1371, 0x3cb1455d, 0x1d05d1f5, 0xd1d996b7,
    0xc2a8e0bc, 0x409082b4, 0x0a2843da, 0x885e9d3c, 0xa150068b, 0xd5276fca,
    0x67bcb6b0, 0xc8462e45, 0x145bd250, 0x14432693, 0x4b3697dc, 0xbac7d1bc,
    0x130fb2d4, 0x465732ca, 0x08a32ed6, 0xd78c7533, 0x0e69c883, 0xbca00cf4,
    0xb4e20df7, 0xdc3a22cf, 0xe8c5af94, 0xf4e80113, 0xac77668c, 0x62ccd709,
    0xb4a35a29, 0x7d138470, 0xcb62b38f, 0x6b4c5b43, 0x600eaaa6, 0x27fee17a,
    0x19334f81, 0x1eaf7848, 0x2c0711e4, 0xf79dd58e, 0x2464f4a5, 0x5f9d2cae,
    0xfcbc6acb, 0x458c770d, 0xb465a081, 0x44daf85c, 0x2aac79f4, 0x773cff17,
    0x883abad9, 0x43a50820, 0xfcb12e4d, 0x89eafd2a, 0x75393c1a, 0x840209d2,
    0x2d8f99f5, 0xa96b9b4b, 0x935ecd3f, 0x3b613258, 0x998b514a, 0x97b0fe60,
};


// ============================================================================
// Helper Functions
// ============================================================================

static void fail_and_halt(int code, const char *msg) {
    printf("FAIL: %s\n", msg);
    test_fail(code);
    while (1) { __asm__("wfi"); }
}

/**
* Wait for OTBN to become idle
*/
static int otbn_wait_for_idle(void)
{
    int timeout = 1000000;  // Large timeout for simulation environments
    int print_counter = 0;  // Debug: print every 100k iterations

    while (timeout-- > 0) {
        uint32_t status = READ_REG(OTBN_STATUS_REG_ADDR);

        // Debug: Print status periodically
        if (++print_counter >= 100000) {
            printf("  [DEBUG] Waiting for OTBN idle... status=0x%02x (expect 0x%02x), timeout=%d\n",
                   status, OTBN_STATUS_IDLE, timeout);
            print_counter = 0;
        }

        if (status == OTBN_STATUS_IDLE) {
            return 0;  // Success
        }
        // Add a small delay to prevent bus contention
        for (volatile int i = 0; i < 100; i++);
    }

    printf("ERROR: OTBN timeout waiting for idle state\n");
    return -1;  // Timeout
}

/**
 * Manually initialize OTBN DMEM with zeros
 * This ensures a clean, predictable memory state
 */
static int otbn_dmem_zero_init(void) {
    printf("Manually initializing OTBN DMEM with zeros\n");

    // Wait for OTBN to be idle before starting
    if (otbn_wait_for_idle() != 0) {
        printf("ERROR: OTBN not idle before DMEM initialization\n");
        return -1;
    }

    // Zero out all visible DMEM locations
    // DMEM has 768 visible 32-bit words (3KB) over the bus interface
    const uint32_t dmem_size_words = 768;
    const uint32_t zero_value = 0x00000000;

    printf("  Writing zeros to DMEM addresses 0x000 to 0x%03x...\n", (dmem_size_words - 1) * 4);

    for (uint32_t addr = 0; addr < dmem_size_words; addr++) {
        OTBN_DMEM_WRITE(addr, zero_value);
    }

    // Reset the checksum register to 0 after DMEM initialization
    printf("  Resetting LOAD_CHECKSUM register to 0...\n");
    WRITE_REG(OTBN_LOAD_CHECKSUM_REG_ADDR, 0x00000000);

    printf("OTBN DMEM zero initialization completed (%u words written)\n", dmem_size_words);
    return 0;
}

/**
 * Load OTBN instruction memory with RSA-3072 program
 */
static int otbn_load_program(void) {
    // Load IMEM (instruction memory)
    size_t imem_words = otbn_rsa_3072_app_imem_words;
    printf("Loading OTBN IMEM: %zu words\n", imem_words);

    for (size_t i = 0; i < imem_words; i++) {
        OTBN_IMEM_WRITE(i, otbn_rsa_3072_app_imem[i]);
    }

    // Load DMEM (data memory)
    size_t dmem_words = otbn_rsa_3072_app_dmem_words;
    printf("Loading OTBN DMEM: %zu words (includes RSA constants)\n", dmem_words);

    for (size_t i = 0; i < dmem_words; i++) {
        OTBN_DMEM_WRITE(i, otbn_rsa_3072_app_dmem[i]);
    }

    // Verify the checksum if available
    if (OTBN_RSA_3072_APP_EXPECTED_CRC != 0) {
        uint32_t actual_crc = READ_REG(OTBN_LOAD_CHECKSUM_REG_ADDR);
        printf("Expected CRC: 0x%08x\n", OTBN_RSA_3072_APP_EXPECTED_CRC);
        printf("Actual CRC:   0x%08x\n", actual_crc);

        if (actual_crc == OTBN_RSA_3072_APP_EXPECTED_CRC) {
            printf("CRC validation PASSED\n");
        } else {
            printf("CRC validation FAILED\n");
            return -1;
        }
    }

    printf("OTBN program loaded successfully (IMEM + DMEM)\n");
    return 0;
}

/**
 * Write data to OTBN DMEM at specified offset
 */
static int otbn_write_dmem(uint32_t offset, const uint32_t* data, size_t word_count) {
    for (size_t i = 0; i < word_count; i++) {
        // Calculate word address in DMEM
        uint32_t word_addr = (offset >> 2) + i;
        uint32_t word = *(data + i);
        OTBN_DMEM_WRITE(word_addr, word);
    }
    return 0;
}

/**
 * Read data from OTBN DMEM at specified offset
 */
static int otbn_read_dmem(uint32_t offset, uint32_t* data, size_t word_count) {
    for (size_t i = 0; i < word_count; i++) {
        // Calculate word address in DMEM
        uint32_t word_addr = (offset >> 2) + i;
        *(data + i) = OTBN_DMEM(word_addr);
    }
    return 0;
}

/**
 * Helper function to compare two uint32_t arrays and print results
 */
static int compare_arrays(const uint32_t* expected, const uint32_t* actual, size_t count, const char* name) {
    int match = 1;
    for (size_t i = 0; i < count; i++) {
        if (expected[i] != actual[i]) {
            match = 0;
            break;
        }
    }

    printf("%s: %s\n", name, match ? "MATCH" : "MISMATCH");

    if (!match) {
        printf("  Expected: ");
        for (size_t i = 0; i < count; i++) {
            printf("%08x ", expected[i]);
        }
        printf("\n  Actual:   ");
        for (size_t i = 0; i < count; i++) {
            printf("%08x ", actual[i]);
        }
        printf("\n");
    }
    return match;
}

// ============================================================================
// RSA-3072 Specific Functions
// ============================================================================

/**
 * Setup RSA verification inputs in OTBN DMEM
 */
static int setup_rsa_verification_inputs(void) {
    printf("Setting up RSA-3072 verification inputs...\n");

    // 1. Write RSA modulus (n) - 96 words
    printf("WRITING MODULUS\n");
    if (otbn_write_dmem(DMEM_N_OFFSET, test_modulus, RSA_3072_NUM_WORDS) != 0) {
        printf("FAILED TO WRITE MODULUS\n");
        return -1;
    }

    // 2. Write signature (96 words) to inout buffer
    printf("WRITING SIG\n");
    if (otbn_write_dmem(DMEM_INOUT_OFFSET, test_signature, RSA_3072_NUM_WORDS) != 0) {
        printf("FAILED TO WRITE SIG\n");
        return -1;
    }

    // 3. Write operation mode (RSA-3072 modexp with F4 exponent)
    static const uint32_t mode[1] = {
        MODE_RSA_3072_MODEXP_F4
    };
    printf("WRITING MODE\n");
    if (otbn_write_dmem(DMEM_MODE_OFFSET, mode, 1) != 0) {
        printf("FAILED TO WRITE MODE\n");
        return -1;
    }

    printf("Setup complete\n");
    return 0;
}

/**
 * Verify RSA input data by reading back from DMEM
 */
static int verify_rsa_input_data(void) {
    printf("\n=== DMEM Input Data Verification ===\n");

    int errors = 0;

    // 1. Verify RSA modulus
    uint32_t readback_modulus[RSA_3072_NUM_WORDS];
    if (otbn_read_dmem(DMEM_N_OFFSET, readback_modulus, RSA_3072_NUM_WORDS) != 0) {
        printf("ERROR: Failed to read back modulus\n");
        return -1;
    }
    if (!compare_arrays(test_modulus, readback_modulus, RSA_3072_NUM_WORDS, "RSA Modulus")) {
        errors++;
    }

    // 2. Verify signature
    uint32_t readback_signature[RSA_3072_NUM_WORDS];
    if (otbn_read_dmem(DMEM_INOUT_OFFSET, readback_signature, RSA_3072_NUM_WORDS) != 0) {
        printf("ERROR: Failed to read back signature\n");
        return -1;
    }
    if (!compare_arrays(test_signature, readback_signature, RSA_3072_NUM_WORDS, "Signature")) {
        errors++;
    }

    // 3. Verify mode
    uint32_t readback_mode;
    if (otbn_read_dmem(DMEM_MODE_OFFSET, &readback_mode, 1) != 0) {
        printf("ERROR: Failed to read back mode\n");
        return -1;
    }
    uint32_t expected_mode = MODE_RSA_3072_MODEXP_F4;
    printf("Mode: %s (expected 0x%08x, actual 0x%08x)\n",
           (readback_mode == expected_mode) ? "MATCH" : "MISMATCH",
           expected_mode, readback_mode);
    if (readback_mode != expected_mode) {
        errors++;
    }

    printf("=== Input Verification Summary ===\n");
    printf("Total errors: %d\n", errors);
    if (errors == 0) {
        printf("SUCCESS: All input data verified correctly!\n");
    } else {
        printf("FAILED: Input data verification found %d mismatches\n", errors);
    }
    printf("\n");

    return (errors == 0) ? 0 : -1;
}

/**
 * Execute OTBN RSA verification operation
 */
static int execute_verification(void) {
    printf("Executing OTBN RSA-3072 verification...\n");

    // Debug: Check status before sending command
    uint32_t status_before = READ_REG(OTBN_STATUS_REG_ADDR);
    printf("  [DEBUG] OTBN status before execute: 0x%02x\n", status_before);
    printf("  [DEBUG] Writing 0x%02x to OTBN_CMD_REG (addr=0x%08x)\n",
           OTBN_CMD_EXECUTE, OTBN_CMD_REG_ADDR);

    // Send execute command
    WRITE_REG(OTBN_CMD_REG_ADDR, OTBN_CMD_EXECUTE);

    // Debug: Check status after sending command
    uint32_t status_after = READ_REG(OTBN_STATUS_REG_ADDR);
    printf("  [DEBUG] OTBN status after execute: 0x%02x\n", status_after);

    // Wait for completion
    if (otbn_wait_for_idle() != 0) {
        return -1;
    }

    // Check for errors
    uint32_t err_bits = READ_REG(OTBN_ERR_BITS_REG_ADDR);
    if (err_bits != 0) {
        printf("ERROR: OTBN execution failed with error bits: 0x%08x\n", err_bits);
        return -1;
    }

    printf("OTBN verification completed successfully\n");
    return 0;
}

/**
 * Check RSA verification results
 */
static int check_rsa_verification_results(void) {
    printf("Checking RSA verification results...\n");

    // Read result from DMEM inout buffer (OTBN writes decrypted/verified data here)
    uint32_t result[RSA_3072_NUM_WORDS];
    if (otbn_read_dmem(DMEM_INOUT_OFFSET, result, RSA_3072_NUM_WORDS) != 0) {
        printf("ERROR: Failed to read result from DMEM\n");
        return -1;
    }

    printf("Result from OTBN (all words):\n");
    for (int i = 0; i < RSA_3072_NUM_WORDS; i++) {
        printf("  [%2d] 0x%08x\n", i, result[i]);
    }

    // For signature verification, the result should be the PKCS#1 v1.5 padded digest
    // Format: 0x00 || 0x01 || PS || 0x00 || DigestInfo || Hash
    // where PS is padding (0xFF bytes)
    // DigestInfo for SHA-256 is a specific ASN.1 structure (19 bytes)

    // Extract the SHA-256 digest from the padded result
    // The digest is the last 32 bytes (8 words) of the result
    uint32_t extracted_digest[SHA256_DIGEST_WORDS];
    for (int i = 0; i < SHA256_DIGEST_WORDS; i++) {
        extracted_digest[i] = result[i];
    }

    printf("\nExtracted digest (first 8 words):\n");
    for (int i = 0; i < SHA256_DIGEST_WORDS; i++) {
        printf("  [%d] 0x%08x\n", i, extracted_digest[i]);
    }

    printf("\nExpected digest:\n");
    for (int i = 0; i < SHA256_DIGEST_WORDS; i++) {
        printf("  [%d] 0x%08x\n", i, test_message_digest[i]);
    }

    // Compare extracted digest with expected message digest
    if (compare_arrays(test_message_digest, extracted_digest,
                       SHA256_DIGEST_WORDS, "Message Digest")) {
        printf("\nSUCCESS: RSA-3072 signature verification PASSED!\n");
        printf("  Message: \"Hello OTBN.\"\n");
        printf("  Hash: SHA-256\n");
        printf("  Signature: RSA-3072 with PKCS#1 v1.5 padding\n");
        printf("  Verification: VALID\n");
        return 0;
    } else {
        printf("\nERROR: Signature verification FAILED - digest mismatch\n");
        return -1;
    }
}

// ============================================================================
// Main Test Function
// ============================================================================

/**
 * Main test function
 */
int main(void) {
    sep_outbound_filter_init();

    printf("======================================================================\n");
    printf("=== OTBN RSA-3072 Signature Verification Test ===\n");
    printf("======================================================================\n");
    printf("Message:           \"Hello OTBN.\"\n");
    printf("Hash Algorithm:    SHA-256\n");
    printf("Signature Format:  RSA-3072 with PKCS#1 v1.5 padding\n");
    printf("Public Exponent:   e = 65537 (F4)\n");
    printf("======================================================================\n\n");

    // Skip manual DMEM zero init - let OTBN CRC compute naturally
    // The CRC is based on IMEM + DMEM loads, not manual writes
    if (otbn_dmem_zero_init() != 0) {
        fail_and_halt(1, "OTBN DMEM zero initialization failed");
    }

    // Load OTBN RSA program
    if (otbn_load_program() != 0) {
        fail_and_halt(2, "Could not load OTBN program");
    }

    // Setup RSA verification inputs
    if (setup_rsa_verification_inputs() != 0) {
        fail_and_halt(3, "Could not setup verification inputs");
    }

    if (verify_rsa_input_data() != 0) {
        fail_and_halt(4, "Input data verification failed");
    }

    // Execute verification
    printf("Starting OTBN execution...\n");
    if (execute_verification() != 0) {
        fail_and_halt(5, "OTBN execution failed");
    }

    // Check results
    if (check_rsa_verification_results() != 0) {
        fail_and_halt(6, "Verification result check failed");
    }

    printf("\n======================================================================\n");
    printf("=== Test PASSED ===\n");
    printf("======================================================================\n");
    test_pass(0);

    while (1) {
        __asm__("wfi");
    }
}
