// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package sep_cpu_ctrl_reg_pkg;

    localparam SEP_CPU_CTRL_REG_DATA_WIDTH = 64;
    localparam SEP_CPU_CTRL_REG_MIN_ADDR_WIDTH = 13;
    localparam SEP_CPU_CTRL_REG_SIZE = 'h1008;

    typedef struct {
        logic [63:0] next;
    } sep_cpu_ctrl__REFERENCE_COUNTER__rc__in_t;

    typedef struct {
        sep_cpu_ctrl__REFERENCE_COUNTER__rc__in_t rc;
    } sep_cpu_ctrl__REFERENCE_COUNTER__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__sys_in_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__dma_data_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__alias_remap_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__filter_out_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__entropy_read_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__entropy_write_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__inbound_mailbox_timeout_int__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__outbound_mailbox_timeout_int__in_t;

    typedef struct {
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__sys_in_timeout_int__in_t sys_in_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__dma_data_timeout_int__in_t dma_data_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__alias_remap_timeout_int__in_t alias_remap_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__filter_out_timeout_int__in_t filter_out_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__entropy_read_timeout_int__in_t entropy_read_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__entropy_write_timeout_int__in_t entropy_write_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__inbound_mailbox_timeout_int__in_t inbound_mailbox_timeout_int;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__outbound_mailbox_timeout_int__in_t outbound_mailbox_timeout_int;
    } sep_cpu_ctrl__TIMEOUT_INTERRUPT__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_TEST_CTRL__sep_standalone__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_TEST_CTRL__fast_pka_en__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_TEST_CTRL__fast_sram_en__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_TEST_CTRL__fast_dccm_en__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_TEST_CTRL__fast_iccm_en__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_TEST_CTRL__fast_spi_en__in_t;

    typedef struct {
        sep_cpu_ctrl__SEP_TEST_CTRL__sep_standalone__in_t sep_standalone;
        sep_cpu_ctrl__SEP_TEST_CTRL__fast_pka_en__in_t fast_pka_en;
        sep_cpu_ctrl__SEP_TEST_CTRL__fast_sram_en__in_t fast_sram_en;
        sep_cpu_ctrl__SEP_TEST_CTRL__fast_dccm_en__in_t fast_dccm_en;
        sep_cpu_ctrl__SEP_TEST_CTRL__fast_iccm_en__in_t fast_iccm_en;
        sep_cpu_ctrl__SEP_TEST_CTRL__fast_spi_en__in_t fast_spi_en;
    } sep_cpu_ctrl__SEP_TEST_CTRL__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SMC_FUSE_SENSE_STATUS__smc_fuse_sense_done__in_t;

    typedef struct {
        sep_cpu_ctrl__SMC_FUSE_SENSE_STATUS__smc_fuse_sense_done__in_t smc_fuse_sense_done;
    } sep_cpu_ctrl__SMC_FUSE_SENSE_STATUS__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_FUSE_SENSE_STATUS__sep_fuse_sense_done__in_t;

    typedef struct {
        sep_cpu_ctrl__SEP_FUSE_SENSE_STATUS__sep_fuse_sense_done__in_t sep_fuse_sense_done;
    } sep_cpu_ctrl__SEP_FUSE_SENSE_STATUS__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_STRAPS__test_en__in_t;

    typedef struct {
        logic next;
    } sep_cpu_ctrl__SEP_STRAPS__bypass_mem_repair__in_t;

    typedef struct {
        sep_cpu_ctrl__SEP_STRAPS__test_en__in_t test_en;
        sep_cpu_ctrl__SEP_STRAPS__bypass_mem_repair__in_t bypass_mem_repair;
    } sep_cpu_ctrl__SEP_STRAPS__in_t;

    typedef struct {
        sep_cpu_ctrl__REFERENCE_COUNTER__in_t REFERENCE_COUNTER;
        sep_cpu_ctrl__TIMEOUT_INTERRUPT__in_t TIMEOUT_INTERRUPT;
        sep_cpu_ctrl__SEP_TEST_CTRL__in_t SEP_TEST_CTRL;
        sep_cpu_ctrl__SMC_FUSE_SENSE_STATUS__in_t SMC_FUSE_SENSE_STATUS;
        sep_cpu_ctrl__SEP_FUSE_SENSE_STATUS__in_t SEP_FUSE_SENSE_STATUS;
        sep_cpu_ctrl__SEP_STRAPS__in_t SEP_STRAPS;
    } sep_cpu_ctrl__in_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__pka_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__dma_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__mailbox_cg_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__fabric_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__filter_in_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__sram_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__zeroer_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__alias_remap_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__filter_out_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__ot_hmac_cg_enable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__entropy_fifo_cg_enable__out_t;

    typedef struct {
        logic [5:0] value;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__cg_hysteresis__out_t;

    typedef struct {
        sep_cpu_ctrl__CLOCK_GATE_CTRL__pka_cg_enable__out_t pka_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__dma_cg_enable__out_t dma_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__mailbox_cg_en__out_t mailbox_cg_en;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__fabric_cg_enable__out_t fabric_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__filter_in_cg_enable__out_t filter_in_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__sram_cg_enable__out_t sram_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__zeroer_cg_enable__out_t zeroer_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__alias_remap_cg_enable__out_t alias_remap_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__filter_out_cg_enable__out_t filter_out_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__ot_hmac_cg_enable__out_t ot_hmac_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__entropy_fifo_cg_enable__out_t entropy_fifo_cg_enable;
        sep_cpu_ctrl__CLOCK_GATE_CTRL__cg_hysteresis__out_t cg_hysteresis;
    } sep_cpu_ctrl__CLOCK_GATE_CTRL__out_t;

    typedef struct {
        logic [63:0] value;
        logic wr_swacc;
    } sep_cpu_ctrl__REFERENCE_COUNTER__rc__out_t;

    typedef struct {
        sep_cpu_ctrl__REFERENCE_COUNTER__rc__out_t rc;
    } sep_cpu_ctrl__REFERENCE_COUNTER__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__PKA_CTRL__pka_dpa_disable__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__PKA_CTRL__pka_noise_src__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__PKA_CTRL__pka_noise_src_valid__out_t;

    typedef struct {
        sep_cpu_ctrl__PKA_CTRL__pka_dpa_disable__out_t pka_dpa_disable;
        sep_cpu_ctrl__PKA_CTRL__pka_noise_src__out_t pka_noise_src;
        sep_cpu_ctrl__PKA_CTRL__pka_noise_src_valid__out_t pka_noise_src_valid;
    } sep_cpu_ctrl__PKA_CTRL__out_t;

    typedef struct {
        logic [47:0] value;
    } sep_cpu_ctrl__TIMEOUT_COUNT__data__out_t;

    typedef struct {
        sep_cpu_ctrl__TIMEOUT_COUNT__data__out_t data;
    } sep_cpu_ctrl__TIMEOUT_COUNT__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__sys_in_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__dma_data_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__alias_remap_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__filter_out_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__entropy_read_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__entropy_write_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__inbound_mailbox_timeout_en__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__outbound_mailbox_timeout_en__out_t;

    typedef struct {
        sep_cpu_ctrl__TIMEOUT_ENABLE__sys_in_timeout_en__out_t sys_in_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__dma_data_timeout_en__out_t dma_data_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__alias_remap_timeout_en__out_t alias_remap_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__filter_out_timeout_en__out_t filter_out_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__entropy_read_timeout_en__out_t entropy_read_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__entropy_write_timeout_en__out_t entropy_write_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__inbound_mailbox_timeout_en__out_t inbound_mailbox_timeout_en;
        sep_cpu_ctrl__TIMEOUT_ENABLE__outbound_mailbox_timeout_en__out_t outbound_mailbox_timeout_en;
    } sep_cpu_ctrl__TIMEOUT_ENABLE__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__sys_in_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__dma_data_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__alias_remap_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__filter_out_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__entropy_read_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__entropy_write_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__inbound_mailbox_timeout_clear__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__outbound_mailbox_timeout_clear__out_t;

    typedef struct {
        sep_cpu_ctrl__TIMEOUT_CLEAR__sys_in_timeout_clear__out_t sys_in_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__dma_data_timeout_clear__out_t dma_data_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__alias_remap_timeout_clear__out_t alias_remap_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__filter_out_timeout_clear__out_t filter_out_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__entropy_read_timeout_clear__out_t entropy_read_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__entropy_write_timeout_clear__out_t entropy_write_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__inbound_mailbox_timeout_clear__out_t inbound_mailbox_timeout_clear;
        sep_cpu_ctrl__TIMEOUT_CLEAR__outbound_mailbox_timeout_clear__out_t outbound_mailbox_timeout_clear;
    } sep_cpu_ctrl__TIMEOUT_CLEAR__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__sys_in_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__dma_data_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__alias_remap_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__filter_out_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__entropy_read_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__entropy_write_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__inbound_mailbox_timeout_mode__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__TIMEOUT_MODE__outbound_mailbox_timeout_mode__out_t;

    typedef struct {
        sep_cpu_ctrl__TIMEOUT_MODE__sys_in_timeout_mode__out_t sys_in_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__dma_data_timeout_mode__out_t dma_data_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__alias_remap_timeout_mode__out_t alias_remap_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__filter_out_timeout_mode__out_t filter_out_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__entropy_read_timeout_mode__out_t entropy_read_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__entropy_write_timeout_mode__out_t entropy_write_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__inbound_mailbox_timeout_mode__out_t inbound_mailbox_timeout_mode;
        sep_cpu_ctrl__TIMEOUT_MODE__outbound_mailbox_timeout_mode__out_t outbound_mailbox_timeout_mode;
    } sep_cpu_ctrl__TIMEOUT_MODE__out_t;

    typedef struct {
        logic [55:0] value;
    } sep_cpu_ctrl__SEP_GLOBAL_BASE_ADDR__addr__out_t;

    typedef struct {
        sep_cpu_ctrl__SEP_GLOBAL_BASE_ADDR__addr__out_t addr;
    } sep_cpu_ctrl__SEP_GLOBAL_BASE_ADDR__out_t;

    typedef struct {
        logic [55:0] value;
    } sep_cpu_ctrl__SEP_LOCAL_BASE_ADDR__addr__out_t;

    typedef struct {
        sep_cpu_ctrl__SEP_LOCAL_BASE_ADDR__addr__out_t addr;
    } sep_cpu_ctrl__SEP_LOCAL_BASE_ADDR__out_t;

    typedef struct {
        logic [31:0] value;
    } sep_cpu_ctrl__SEP_REGION_SIZE__size__out_t;

    typedef struct {
        sep_cpu_ctrl__SEP_REGION_SIZE__size__out_t size;
    } sep_cpu_ctrl__SEP_REGION_SIZE__out_t;

    typedef struct {
        logic [55:0] value;
    } sep_cpu_ctrl__SMU_GLOBAL_BASE_ADDR__addr__out_t;

    typedef struct {
        sep_cpu_ctrl__SMU_GLOBAL_BASE_ADDR__addr__out_t addr;
    } sep_cpu_ctrl__SMU_GLOBAL_BASE_ADDR__out_t;

    typedef struct {
        logic [31:0] value;
    } sep_cpu_ctrl__SMU_REGION_SIZE__size__out_t;

    typedef struct {
        sep_cpu_ctrl__SMU_REGION_SIZE__size__out_t size;
    } sep_cpu_ctrl__SMU_REGION_SIZE__out_t;

    typedef struct {
        logic [3:0] value;
    } sep_cpu_ctrl__RAS_BANK_INFO__bank_chip__out_t;

    typedef struct {
        logic [3:0] value;
    } sep_cpu_ctrl__RAS_BANK_INFO__bank_instance__out_t;

    typedef struct {
        sep_cpu_ctrl__RAS_BANK_INFO__bank_chip__out_t bank_chip;
        sep_cpu_ctrl__RAS_BANK_INFO__bank_instance__out_t bank_instance;
    } sep_cpu_ctrl__RAS_BANK_INFO__out_t;

    typedef struct {
        logic [31:0] value;
    } sep_cpu_ctrl__SEP_SW_DEBUG__sep_sw_debug__out_t;

    typedef struct {
        sep_cpu_ctrl__SEP_SW_DEBUG__sep_sw_debug__out_t sep_sw_debug;
    } sep_cpu_ctrl__SEP_SW_DEBUG__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__SEP_NMI_VEC_nmi_vec_a3690e40__rsvd__out_t;

    typedef struct {
        logic [30:0] value;
    } sep_cpu_ctrl__SEP_NMI_VEC_nmi_vec_a3690e40__nmi_vec_swwel_dccc9344__out_t;

    typedef struct {
        sep_cpu_ctrl__SEP_NMI_VEC_nmi_vec_a3690e40__rsvd__out_t rsvd;
        sep_cpu_ctrl__SEP_NMI_VEC_nmi_vec_a3690e40__nmi_vec_swwel_dccc9344__out_t nmi_vec;
    } sep_cpu_ctrl__SEP_NMI_VEC_nmi_vec_a3690e40__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__SEP_NMI_VEC_LOCK__lock__out_t;

    typedef struct {
        sep_cpu_ctrl__SEP_NMI_VEC_LOCK__lock__out_t lock;
    } sep_cpu_ctrl__SEP_NMI_VEC_LOCK__out_t;

    typedef struct {
        logic [1:0] value;
    } sep_cpu_ctrl__EXT_TRNG_SRC_SEL_sel_c607e53d__sel_swwel_5b08e6ad__out_t;

    typedef struct {
        sep_cpu_ctrl__EXT_TRNG_SRC_SEL_sel_c607e53d__sel_swwel_5b08e6ad__out_t sel;
    } sep_cpu_ctrl__EXT_TRNG_SRC_SEL_sel_c607e53d__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__EXT_TRNG_SRC_SEL_LOCK__lock__out_t;

    typedef struct {
        sep_cpu_ctrl__EXT_TRNG_SRC_SEL_LOCK__lock__out_t lock;
    } sep_cpu_ctrl__EXT_TRNG_SRC_SEL_LOCK__out_t;

    typedef struct {
        logic value;
    } sep_cpu_ctrl__KM_WIPE_CTRL__wipe_state__out_t;

    typedef struct {
        sep_cpu_ctrl__KM_WIPE_CTRL__wipe_state__out_t wipe_state;
    } sep_cpu_ctrl__KM_WIPE_CTRL__out_t;

    typedef struct {
        sep_cpu_ctrl__CLOCK_GATE_CTRL__out_t CLOCK_GATE_CTRL;
        sep_cpu_ctrl__REFERENCE_COUNTER__out_t REFERENCE_COUNTER;
        sep_cpu_ctrl__PKA_CTRL__out_t PKA_CTRL;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_DMA;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_SYS_IN;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_MAILBOX_INBOUND;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_MAILBOX_OUTBOUND;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_ENTROPY_WRITE;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_ENTROPY_READ;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_FILTER_OUT;
        sep_cpu_ctrl__TIMEOUT_COUNT__out_t TIMEOUT_COUNT_ALIAS_REMAP;
        sep_cpu_ctrl__TIMEOUT_ENABLE__out_t TIMEOUT_ENABLE;
        sep_cpu_ctrl__TIMEOUT_CLEAR__out_t TIMEOUT_CLEAR;
        sep_cpu_ctrl__TIMEOUT_MODE__out_t TIMEOUT_MODE;
        sep_cpu_ctrl__SEP_GLOBAL_BASE_ADDR__out_t SEP_GLOBAL_BASE_ADDR;
        sep_cpu_ctrl__SEP_LOCAL_BASE_ADDR__out_t SEP_LOCAL_BASE_ADDR;
        sep_cpu_ctrl__SEP_REGION_SIZE__out_t SEP_REGION_SIZE;
        sep_cpu_ctrl__SMU_GLOBAL_BASE_ADDR__out_t SMU_GLOBAL_BASE_ADDR;
        sep_cpu_ctrl__SMU_REGION_SIZE__out_t SMU_REGION_SIZE;
        sep_cpu_ctrl__RAS_BANK_INFO__out_t RAS_BANK_INFO;
        sep_cpu_ctrl__SEP_SW_DEBUG__out_t SEP_SW_DEBUG;
        sep_cpu_ctrl__SEP_NMI_VEC_nmi_vec_a3690e40__out_t SEP_NMI_VEC;
        sep_cpu_ctrl__SEP_NMI_VEC_LOCK__out_t SEP_NMI_VEC_LOCK;
        sep_cpu_ctrl__EXT_TRNG_SRC_SEL_sel_c607e53d__out_t EXT_TRNG_SRC_SEL;
        sep_cpu_ctrl__EXT_TRNG_SRC_SEL_LOCK__out_t EXT_TRNG_SRC_SEL_LOCK;
        sep_cpu_ctrl__KM_WIPE_CTRL__out_t KM_WIPE_CTRL;
    } sep_cpu_ctrl__out_t;
endpackage
